### ISSUE TITLE
es.update failed on ES7.2.0.....

### ISSUE THREAD

**Issue by loveJasmine** [elastic/elasticsearch-py#1042]
from datetime import datetime
from elasticsearch import Elasticsearch
es = Elasticsearch()
print(es)
es.indices.create(index='my-index', ignore=400)

data = {'title': 'hello world', 'url': 'http://view.news.qq.com/zt2011/usa_iraq/index.htm'}
es.create(index='my-index', doc_type='politics', id=1, body=data)
data2 = {'title': 'hello world', 'url': 'http://view.news.qq.com/zt2011/usa_iraq/index.htm','date': '2011-12-16'}
es.update(index='my-index', doc_type='politics', id=1, body=data2)

++++++it report++++
G:\ub16_prj\bumblebee\ES>python yk-demo---elasticsearch-py.py
<Elasticsearch([{}])>
POST http://localhost:9200/my-index/politics/1/_update [status:400 request:0.001s]
Traceback (most recent call last):
  File "yk-demo---elasticsearch-py.py", line 38, in <module>
    es.update(index='my-index', doc_type='politics', id=1, body=data2)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\elasticsearch\client\utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\elasticsearch\client\__init__.py", line 527, in update
    doc_type, id, '_update'), params=params, body=body)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\elasticsearch\transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 129, in perform_request
    self._raise_error(response.status, raw_data)
  File "C:\Users\andyy\AppData\Local\Programs\Python\Python37\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'x_content_parse_exception', '[1:2] [UpdateRequest] unknown field [title], parser not found')

G:\ub16_prj\bumblebee\ES>
G:\ub16_prj\bumblebee\ES>

**Comment by xujiang1** [comment]
from elasticsearch import Elasticsearch


class Search(object):

    def __init__(self):
        self.es = Elasticsearch("112.74.185.44:9200")

    def create_index(self):
        result = self.es.indices.create(index='news', ignore=400)
        print(result)

    def delete_index(self):
        result = self.es.indices.delete(index='news', ignore=[400, 404])
        print(result)

    def insert_data(self):
        data = {'title': '美国留给伊拉克的是个烂摊子吗', 'url': 'http://view.news.qq.com/zt2011/usa_iraq/index.htm'}
        result = self.es.create(index='news', id=1, body=data)
        print(result)

    def index_data(self):
        data = {'title': '美国留给伊拉克的是个烂摊子吗', 'url': 'http://view.news.qq.com/zt2011/usa_iraq/index.htm'}
        result = self.es.index(index='news', body=data)
        print(result)

    def update_data(self):
        data = {'title': '美国留给伊拉克的是个烂摊子吗', 'url': 'http://view.news.qq.com/zt2011/usa_iraq/index.htm',
                'date': '2011-12-16'}
        result = self.es.update(index='news', id=1, body=data, params={"retry_on_conflict": 'true'})
        print(result)


search = Search()
search.update_data()
++++++it report++++
C:\Users\xuzhu\.virtualenvs\flaskserver-PKgKgxc4\Scripts\python.exe C:/Users/xuzhu/Desktop/project/flaskserver/search_demo.py
Traceback (most recent call last):
  File "C:/Users/xuzhu/Desktop/project/flaskserver/search_demo.py", line 35, in <module>
    search.update_data()
  File "C:/Users/xuzhu/Desktop/project/flaskserver/search_demo.py", line 30, in update_data
    result = self.es.update(index='news', id=1, body=data, params={"retry_on_conflict": 'true'})
  File "C:\Users\xuzhu\.virtualenvs\flaskserver-PKgKgxc4\lib\site-packages\elasticsearch\client\utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "C:\Users\xuzhu\.virtualenvs\flaskserver-PKgKgxc4\lib\site-packages\elasticsearch\client\__init__.py", line 652, in update
    "POST", _make_path(index, doc_type, id, "_update"), params=params, body=body
  File "C:\Users\xuzhu\.virtualenvs\flaskserver-PKgKgxc4\lib\site-packages\elasticsearch\transport.py", line 350, in perform_request
    timeout=timeout,
  File "C:\Users\xuzhu\.virtualenvs\flaskserver-PKgKgxc4\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "C:\Users\xuzhu\.virtualenvs\flaskserver-PKgKgxc4\lib\site-packages\elasticsearch\connection\base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Failed to parse int parameter [retry_on_conflict] with value [true]')

**Comment by whbjzzwjxq** [comment]
the same problem as yours 
met elasticsearch.exceptions.RequestError: RequestError(400, 'x_content_parse_exception', '[1:2] [UpdateRequest] unknown field [id], parser not found')

while using the bulk_update method

**Comment by whbjzzwjxq** [comment]
not bug
attention that the update API's syntax is different from the create API:
see: https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-bulk.html example
the update_body should be {"doc": create_body}

**Comment by HonzaKral** [comment]
`retry_on_conflict` requires a number, not a boolean like you passed in, that is the error mentioned.
