### ISSUE TITLE
exists() raises a HTTP 400 without additional detail

### ISSUE THREAD

**Issue by bastbnl** [elastic/elasticsearch-py#1053]
Hi,

I'm using `elasticsearch==7.0.5` on python 3.7.4 using my poor man's 3 node elasticsearch cluster and I'm seeing curious behavior when using `exists`. Elasticsearch appears to raise an HTTP 400 error without additional detail when alias is set to multiple indices without any additional configuration. Here's a small log:

```
>>> es.get(index='emoji-brwnppr.dev', id='fff')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 501, in get
    "GET", _make_path(index, doc_type, id), params=params
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', "Alias [emoji-brwnppr.dev] has more than one indices associated with it [[emoji-brwnppr.dev-2934d9a04900b50407f51120b93e3c647e5771e1, emoji-brwnppr.dev-4_1_0]], can't execute a single index op")
```

This error is pretty good. The error raised by `exists` is a bit different though:
```
>>> es.exists(index='emoji-brwnppr.dev', id='fff')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 411, in exists
    "HEAD", _make_path(index, doc_type, id), params=params
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/transport.py", line 350, in perform_request
    timeout=timeout,
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "/var/www/brownpapersession/dev/env/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, '')
```

The `RequestError` disappeared right after I DELETEd one of the indices the alias was linked to. I would've expected the same error raised by the `get`.

The cluster consists of 3 nodes, each of which are running elasticsearch 7.4.2.
```
{
  "name" : "ams1-2",
  "cluster_name" : "brwnppr",
  "cluster_uuid" : "vLBewzxMRgqO7da2DGWjJQ",
  "version" : {
    "number" : "7.4.2",
    "build_flavor" : "default",
    "build_type" : "deb",
    "build_hash" : "2f90bbf7b93631e52bafb59b3b049cb44ec25e96",
    "build_date" : "2019-10-28T20:40:44.881551Z",
    "build_snapshot" : false,
    "lucene_version" : "8.2.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}
```

This does not seem to be related to the elasticsearch-py module - but I didn't test if the same thing happens when I use a different elasticsearch-py version.

**Comment by HonzaKral** [comment]
The problem is that `exists` is using the `HEAD` http method which means that Elasticsearch doesn't actually return a body that could contain the details of the exception. Unfortunately there is nothing we can do there.

**Comment by bastbnl** [comment]
Thanks for explaining. I guess we could add documentation to save the next user some time. I'll be happy to create a pr @HonzaKral
