### ISSUE TITLE
During scan in elasticsearch I got unicoderror

### ISSUE THREAD

**Issue by ZeusFSX** [elastic/elasticsearch-py#1055]
The version of elasticsearch-py == 6.3.1
Python version 3.7.4
````
GET http://0.0.0.0:9200/forums/live/_search?scroll=5m&size=1000 [status:N/A request:0.714s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 174, in perform_request
    raw_data = response.data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 272915: invalid continuation byte
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 174, in perform_request
    raw_data = response.data.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xed in position 272915: invalid continuation byte

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zeusfsx/Work/streamua/main.py", line 67, in main_loop
    res = load.get_news(config.INPUT, request=kw)
  File "/Users/zeusfsx/Work/streamua/load.py", line 69, in get_news
    all_data += data
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/__init__.py", line 364, in scan
    request_timeout=request_timeout, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/__init__.py", line 660, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 181, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError('utf-8' codec can't decode byte 0xed in position 272915: invalid continuation byte) caused by: UnicodeDecodeError('utf-8' codec can't decode byte 0xed in position 272915: invalid continuation byte)

````

**Comment by HonzaKral** [comment]
This looks like you have a document in Elasticsearch that contains incorrect unicode. Unfortunately this is a known issue with Elasticssearch where it doesn't validate the input: https://github.com/elastic/elasticsearch/issues/9538

You can see a workaround for this issue at https://github.com/elastic/elasticsearch-py/issues/370

Sorry about the inconvenience.
