### ISSUE TITLE
it seems like client request will be timeout  first  request with everyday

### ISSUE THREAD

**Issue by francis12** [elastic/elasticsearch-py#1065]
the first request is timeout with everyday，and the next request is normal。
ElasticSearch version is 7.*
**follows is the traceback** 
```
[2019-11-28 09:48:57,868][ThreadPoolExecutor-0_4:140670823548672][task_id:elasticsearch][base.py:150][WARNING][GET http://127.0.0.1:9200/_cluster/health [status:N/A request:60.043s]]
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 416, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 1321, in getresponse
    response.begin()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 296, in begin
    version, status, reason = self._read_status()
  File "/usr/local/python3/lib/python3.7/http/client.py", line 257, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/python3/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 238, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 720, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/util/retry.py", line 376, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 672, in urlopen
    chunked=chunked,
  File "/usr/local/python3/lib/python3.7/site-packages/urllib3/connectionpool.py", line 423, in _make_request
```

**Comment by HonzaKral** [comment]
Hi, this looks like some weird behavior on your network as the request is taking over a minute which it really shouldn't. Unfortunately there isn't anything we can do about that as it is external to python.
