### ISSUE TITLE
elasticsearch 500  general_script_exception

### ISSUE THREAD

**Issue by xingzhoupy** [elastic/elasticsearch-py#1092]
Hi,why error
elasticsearch：7.5.0
elasticsearch-py：7.1.0
Thanks
Traceback (most recent call last):
  File "D:/pySpace/nfdw/zdbk/zubk_algorithm/zubk_algorithm/helpers.py", line 125, in <module>
    main()
  File "D:/pySpace/nfdw/zdbk/zubk_algorithm/zubk_algorithm/helpers.py", line 121, in main
    update_similar(documents_ids, simHashs, sim_dict)
  File "D:\pySpace\nfdw\zdbk\zubk_algorithm\zubk_algorithm\service.py", line 51, in update_similar
    es.es_update_simHash(id=ids[i], simHash=simHash)
  File "D:\pySpace\nfdw\zdbk\zubk_algorithm\zubk_algorithm\es_model.py", line 110, in es_update_simHash
  File "D:\pySpace\nfdw\zdbk\zubk_algorithm\venv\lib\site-packages\elasticsearch\client\utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "D:\pySpace\nfdw\zdbk\zubk_algorithm\venv\lib\site-packages\elasticsearch\client\__init__.py", line 932, in update_by_query
    "POST", _make_path(index, "_update_by_query"), params=params, body=body
  File "D:\pySpace\nfdw\zdbk\zubk_algorithm\venv\lib\site-packages\elasticsearch\transport.py", line 358, in perform_request
    timeout=timeout,
  File "D:\pySpace\nfdw\zdbk\zubk_algorithm\venv\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 257, in perform_request
    self._raise_error(response.status, raw_data)
  File "D:\pySpace\nfdw\zdbk\zubk_algorithm\venv\lib\site-packages\elasticsearch\connection\base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(500, 'general_script_exception', '[script] Too many dynamic script compilations within, max: [75/5m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting')

**Comment by HonzaKral** [comment]
Hi, you are using scripts too much since elasticsearch has a limit for how many new scripts are compiled at any time - the limit is shown in the error as 75 compilations in a 5 minute window.

To make sure you are not triggering this it is important to use parameters.

All is explained in https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting-using.html#prefer-params

Hope this helps!
