### ISSUE TITLE
Freeze API throws RequestError

### ISSUE THREAD

**Issue by justinbass** [elastic/elasticsearch-py#1100]
Elasticsearch (server) version 7.1
python 3.7, elasticsearch (client) version 7.5.1, urllib3 version 1.24.1

Using the freeze api does not work. Request seems to require a body, which is not supplied. Also note that the docs are broken (https://elasticsearch-py.readthedocs.io/en/master/api.html#indices) - this page doesn't exist: https://www.elastic.co/guide/en/elasticsearch/reference/current/frozen.html 

Code:
indices_client = elasticsearch.client.IndicesClient(es_client)
indices_client.freeze(index_name)

Note that this is working for a dozen other api's called.

2020-02-03 19:06:41,337 - WARNING - POST https://.../_freeze [status:400 request:0.084s]
Traceback (most recent call last):
  ...
  File
    indices_client.freeze(index_name)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/client/indices.py", line 1160, in freeze
    "POST", _make_path(index, "_freeze"), params=params
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/http_requests.py", line 163, in perform_request
    self._raise_error(response.status_code, raw_data)
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.RequestError: RequestError(400, 'parse_exception', 'request body is required')

**Comment by alexk307** [comment]
Hi @justinbass. I'm having trouble reproducing this issue with the details you have provided.

```
Python 3.7.6 (default, Dec 30 2019, 19:38:28)
[Clang 11.0.0 (clang-1100.0.33.16)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import elasticsearch
>>> elasticsearch.__version__
(7, 5, 1)
>>> es = elasticsearch.Elasticsearch(cloud_id="<REDACTED>")
>>> ind_client = elasticsearch.client.IndicesClient(es)
>>> ind_client.freeze('.security-7')
{'acknowledged': True, 'shards_acknowledged': True}
>>>
```

Can you possibly provide some more context around your code? I'll look into the docs in the meantime.

**Comment by alexk307** [comment]
No problem! To be clear, my version of elasticsearch-py was `7.5.1`. I tested this with an Elasticsearch server running 7.1.0 like you did.
