### ISSUE TITLE
es search with size 1 crashes

### ISSUE THREAD

**Issue by dpgaspar** [elastic/elasticsearch-py#1173]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.5.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 7.5.1

**Description of the problem including expected versus actual behavior**:

When running:
```
from elasticsearch import Elasticsearch
es = Elasticsearch('localhost')
es.search("kibana_sample_data_flights", size=1)
```

I get:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/dpgaspar/workarea/preset/elasticsearch-dbapi/venv/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 84, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/dpgaspar/workarea/preset/elasticsearch-dbapi/venv/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 1548, in search
    "GET", _make_path(index, doc_type, "_search"), params=params, body=body
  File "/home/dpgaspar/workarea/preset/elasticsearch-dbapi/venv/lib/python3.6/site-packages/elasticsearch/transport.py", line 358, in perform_request
    timeout=timeout,
  File "/home/dpgaspar/workarea/preset/elasticsearch-dbapi/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 261, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/dpgaspar/workarea/preset/elasticsearch-dbapi/venv/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 182, in _raise_error
    status_code, error_message, additional_info
elasticsearch.exceptions.TransportError: TransportError(500, 'json_parse_exception', "Unrecognized token 'kibana_sample_data_flights': was expecting ('true', 'false' or 'null')\n at [Source: org.elasticsearch.transport.netty4.ByteBufStreamInput@16a3a10d; line: 1, column: 53]")

```

Related issues: 
https://github.com/preset-io/elasticsearch-dbapi/issues/19
https://github.com/preset-io/elasticsearch-dbapi/issues/20

Note: Works fine on elasticsearch-py 7.1.0 for example

**Comment by dpgaspar** [comment]
Found out what the problem was:
I need to use:
```
es.search(index="kibana_sample_data_flights", size=1)
```
instead of
```
es.search("kibana_sample_data_flights", size=1)
```
