### ISSUE TITLE
/_cluster/health/<index>?wait_for_status=3h times out after 5 minutes

### ISSUE THREAD

**Issue by aldenstpage** [elastic/elasticsearch-py#1234]
**Elasticsearch version** 7.6.2):

**`elasticsearch-py` version**: 7.0.0 

**Description of the problem including expected versus actual behavior**:
I have a piece of infrastructure that relies on /_cluster/health/<index> with `wait_for_status=3h`. After I finish recreating my index, I turn replica shards back on, and then wait for the status of the index to switch to green. This index is fairly large, which means it can be over an hour before the new index becomes healthy, so I set the cap at three hours. However, elasticsearch-py times out after 5 minutes instead. My guess is that this library caps the urllib timeout somewhere, breaking long-running healthchecks.

Here's the corresponding elasticsearch-py call:
```
es.cluster.health(
    index=write_index,
    wait_for_status='green',
    timeout="3h"
)
```

It's called right after this "Waiting for replica shards. . ." log message. You can see from the timestamps that three hours has not passed.
```
2020-05-09 02:31:20,966 INFO indexer.py:331 - Waiting for replica shards. . .
2020-05-09 02:36:20,992 WARNING base.py:212 - GET <cluster endpoint removed>/_cluster/health/image-e94697a961ca49d7a25e28fc3deb077c?timeout=3h&wait_for_status=green [status:N/A request:300.025s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/usr/local/lib/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/lib/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/local/lib/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/local/lib/python3.7/http/client.py", line 267, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/local/lib/python3.7/socket.py", line 589, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out
```

**Steps to reproduce**:
Call `es.cluster.health(index=your_test_index, wait_for_status='red', timeout="3h")` and watch it time out after five minutes.

**Comment by aldenstpage** [comment]
I see now that this was an issue in our own code; I initialized the Elasticsearch connection with the timeout set. I misunderstood the constructor, I thought timeout was the connection timeout.
