### ISSUE TITLE
Wrong transport (HTTP vs. HTTPS) to sniffed nodes under some conditions

### ISSUE THREAD

**Issue by pisto** [elastic/elasticsearch-py#1276]
**Elasticsearch version**

7.7.0

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**: 

7.6.0

**Description of the problem including expected versus actual behavior**:

Connection sniffing does not query for the transport type to connect to autodiscovered nodes. In fact, the autodiscovery is [implemented by querying the `_nodes/_all/http` API](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L242), which does not return SSL transport info. This means that the new connections in the pool use the HTTP transport, unless the `Elasticsearch` object has been initialized with additional explicit ssl configurations, such as `use_ssl=True` or `ssl_context`. This is inconsistent with the [automatic transport resolution of the seed nodes](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/utils.py#L42-L44), where the URL scheme determines whether HTTP or HTTPS is used. In practice, if the `Elasticsearch` object is initialized with just an `https://` URL and with `sniff_on_start=True` and no other SSL-related options, a `ConnectionError` is eventually thrown at the first API request. Here is an excerpt of a debug output to demonstrate the issue:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): 172.16.176.5:9200
DEBUG:urllib3.connectionpool:https://172.16.176.5:9200 "GET /_nodes/_all/http HTTP/1.1" 200 3320
INFO:elasticsearch:GET https://172.16.176.5:9200/_nodes/_all/http [status:200 request:0.722s]
DEBUG:elasticsearch:> None
DEBUG:elasticsearch:< {"_nodes":{"total":5,"successful":5,"failed":0},"cluster_name":"the-cluster","nodes":{"hAkbsPIeQpqYjfr1Qw0aCg":{"name":"elastic-master-2-01","transport_address":"172.16.176.5:9300","host":"172.16.176.5","ip":"172.16.176.5","version":"7.7.0","build_flavor":"default","build_type":"rpm","build_hash":"81a1e9eda8e6183f5237786246f6dced26a10eaf","roles":["ingest","master","transform","data","remote_cluster_client","ml"],"attributes":{"ml.machine_memory":"16806506496","xpack.installed":"true","zone":"2","transform.node":"true","ml.max_open_jobs":"20"},"http":{"bound_address":["[::1]:9200","127.0.0.1:9200","[fe80::20d:3aff:fe3a:ad15]:9200","172.16.176.5:9200"],"publish_address":"172.16.176.5:9200","max_content_length_in_bytes":104857600}},"5ezKWqPzTni86qCbagoCAQ":{"name":"elastic-master-1-01","transport_address":"172.16.176.4:9300","host":"172.16.176.4","ip":"172.16.176.4","version":"7.7.0","build_flavor":"default","build_type":"rpm","build_hash":"81a1e9eda8e6183f5237786246f6dced26a10eaf","roles":["ingest","master","transform","data","remote_cluster_client","ml"],"attributes":{"ml.machine_memory":"16806506496","ml.max_open_jobs":"20","xpack.installed":"true","zone":"1","transform.node":"true"},"http":{"bound_address":["[::1]:9200","127.0.0.1:9200","172.16.176.4:9200","[fe80::20d:3aff:fe39:8a93]:9200"],"publish_address":"172.16.176.4:9200","max_content_length_in_bytes":104857600}},"aZgQkzYtRL-CslZE5S3FAQ":{"name":"elastic-master-3-01","transport_address":"172.16.176.6:9300","host":"172.16.176.6","ip":"172.16.176.6","version":"7.7.0","build_flavor":"default","build_type":"rpm","build_hash":"81a1e9eda8e6183f5237786246f6dced26a10eaf","roles":["ingest","master","remote_cluster_client","ml"],"attributes":{"ml.machine_memory":"8350789632","ml.max_open_jobs":"20","xpack.installed":"true","zone":"3","transform.node":"false"},"http":{"bound_address":["[::1]:9200","127.0.0.1:9200","172.16.176.6:9200","[fe80::20d:3aff:fe44:627]:9200"],"publish_address":"172.16.176.6:9200","max_content_length_in_bytes":104857600}},"Xwwys75hRrGJGLDBwAgKKw":{"name":"elastic-data-2-01","transport_address":"172.16.176.8:9300","host":"172.16.176.8","ip":"172.16.176.8","version":"7.7.0","build_flavor":"default","build_type":"rpm","build_hash":"81a1e9eda8e6183f5237786246f6dced26a10eaf","roles":["ingest","transform","data","remote_cluster_client","ml"],"attributes":{"ml.machine_memory":"16806506496","ml.max_open_jobs":"20","xpack.installed":"true","zone":"2","transform.node":"true"},"http":{"bound_address":["[fe80::20d:3aff:fe26:ca74]:9200","[::1]:9200","127.0.0.1:9200","172.16.176.8:9200"],"publish_address":"172.16.176.8:9200","max_content_length_in_bytes":104857600}},"D2a6y70lR9WDVjiGD23jQQ":{"name":"elastic-data-1-01","transport_address":"172.16.176.7:9300","host":"172.16.176.7","ip":"172.16.176.7","version":"7.7.0","build_flavor":"default","build_type":"rpm","build_hash":"81a1e9eda8e6183f5237786246f6dced26a10eaf","roles":["ingest","transform","data","remote_cluster_client","ml"],"attributes":{"ml.machine_memory":"16806506496","ml.max_open_jobs":"20","xpack.installed":"true","zone":"1","transform.node":"true"},"http":{"bound_address":["[fe80::20d:3aff:fe24:a641]:9200","[::1]:9200","127.0.0.1:9200","172.16.176.7:9200"],"publish_address":"172.16.176.7:9200","max_content_length_in_bytes":104857600}}}}
DEBUG:urllib3.connectionpool:Starting new HTTP connection (1): 172.16.176.5:9200
WARNING:elasticsearch:GET http://172.16.176.5:9200/logstash-* [status:N/A request:0.063s]
Traceback (most recent call last):
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib64/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
http.client.RemoteDisconnected: Remote end closed connection without response
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 229, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 725, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/util/retry.py", line 379, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/packages/six.py", line 734, in reraise
    raise value.with_traceback(tb)
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 677, in urlopen
    chunked=chunked,
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 426, in _make_request
    six.raise_from(e, None)
  File "<string>", line 3, in raise_from
  File "/home/test/src/es-lib/venv/lib64/python3.7/site-packages/urllib3/connectionpool.py", line 421, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib64/python3.7/http/client.py", line 1344, in getresponse
    response.begin()
  File "/usr/lib64/python3.7/http/client.py", line 306, in begin
    version, status, reason = self._read_status()
  File "/usr/lib64/python3.7/http/client.py", line 275, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
DEBUG:elasticsearch:> None
WARNING:elasticsearch:Connection <Urllib3HttpConnection: http://172.16.176.5:9200> has failed for 1 times in a row, putting on 60 second timeout.
```
Note that all the nodes in this cluster are configured to use SSL.

**Steps to reproduce**:
```
Elasticsearch(['https://some-node:9200'], sniff_on_start=True, http_auth=('user', 'password')).cluster.health()
```
and watch it fail with (eventually):
```
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))) caused by: ProtocolError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))
```

**Comment by Fushengliangnian** [comment]
I had the same problem, but I didn't use SSL.
If there is any result, I hope you can inform me.
Thank!
