### ISSUE TITLE
ReadTimeoutError raised while calling es.indices.optimize(index='', wait_for_merge=True)

### ISSUE THREAD

**Issue by shihpeng** [elastic/elasticsearch-py#129]
I am using the following code to optimize indices after indexing my documents. However, a `ReadTimeoutError` was raised, but there is no any option that I can change the connection timeout setting.

```
es.indices.optimize(index='', wait_for_merge=True)
```

The backtrace of the raised error:

```

Traceback (most recent call last):
  File "./main.py", line 249, in <module>
    main()
  File "./main.py", line 240, in main
    es.indices.optimize(index='', wait_for_merge=True)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 67, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elasticsearch/client/indices.py", line 734, in optimize
    _, data = self.transport.perform_request('POST', _make_path(index, '_optimize'), params=params)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elasticsearch/transport.py", line 276, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/Cellar/python/2.7.6/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 51, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10)) caused by: ReadTimeoutError(HTTPConnectionPool(host='localhost', port=9200): Read timed out. (read timeout=10))
```

**Comment by lockwooddev** [comment]
On elasticsearch 2.3.5 and python client (2.3) using the same endpoint, now called Force Merge, passing the `wait_for_merge` is still ignored and will eventually throw a ReadTimeoutError. 

Also note that there is no such parameter for elasticsearch judging from the documentation.
https://www.elastic.co/guide/en/elasticsearch/reference/2.3/indices-forcemerge.html

For now I will just try to catch the exception, as the operation is performed anyways.
