### ISSUE TITLE
Getting a JSONDecodeError 'Unterminated string starting at: ...' when hitting an AWS API Gateway that proxies to an elx

### ISSUE THREAD

**Issue by lslee714** [elastic/elasticsearch-py#1345]
**Elasticsearch version** (`bin/elasticsearch --version`): 7.8.1

**`elasticsearch-py` version (`elasticsearch.__versionstr__`)**:  7.8.1

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:
Hitting search with a specific query returns a JSONDecodeError shown in the title when it looks like it's trying to deserialize the response. The stack trace is 

```
Traceback (most recent call last):
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/elasticsearch/serializer.py", line 97, in loads
    return json.loads(s)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/simplejson/__init__.py", line 525, in loads
    return _default_decoder.decode(s)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/simplejson/decoder.py", line 370, in decode
    obj, end = self.raw_decode(s)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/simplejson/decoder.py", line 400, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
simplejson.errors.JSONDecodeError: Unterminated string starting at: line 1 column 7823 (char 7822)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/flask_jwt_extended/view_decorators.py", line 103, in wrapper
    return fn(*args, **kwargs)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/resources/marketplace.py", line 27, in get
    res = view_mode_to_fn[view_mode](**request_args)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/resources/marketplace.py", line 46, in get_default_view_data
    categories = marketplace_es.get_categories(user.preference.materials_vendor_ids)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/elastic/marketplace_search.py", line 49, in get_categories
    raw_result = self.app.elasticsearch.search(index=self.INDEX_NAME, body=categories_query)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 139, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/elasticsearch/client/__init__.py", line 1479, in search
    return self.transport.perform_request(
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 384, in perform_request
    data = self.deserializer.loads(
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/elasticsearch/serializer.py", line 143, in loads
    return deserializer.loads(s)
  File "/home/luke/Projects/takeoffs/takeoffs-app/server/venv/lib/python3.8/site-packages/elasticsearch/serializer.py", line 99, in loads
    raise SerializationError(s, e)
elasticsearch.exceptions.SerializationError: ('{"some-real-json-i-expect ..." } occured while trying to proxy to: materials-es-proxy.takeoffs.io/allproductprices/_search', JSONDecodeError('Unterminated string starting at: line 1 column 7823 (char 7822)'))

```

It's worth noting when I run the AWS lambda proxy locally, it works fine, which sort of leads me to believe it's related to something in AWS, still working through this with them too. The reason I still think it may be related to elasticsearch-py library is because hitting the AWS proxy with postman, curl and even the python `requests` library, it works fine.

**Steps to reproduce**:
Obviously, it's not trivial to mock up all the parts for reproducing it. However, we made a temp api key to the proxy that should allow you direct access and direct copy of what I'm doing. Please let me know what you think about this and I'm happy to share it. Here's a script, you can just fill in the "x-api-key" value once I share it.

```
from elasticsearch import Elasticsearch

es = Elasticsearch(
    '',
    headers = {
        'x-api-key': '',
    }
)


body = {
    "query": {
        "bool": {
            "must": [
                {
                    "match": {
                        "vendor_id": 103
                    }
                }
            ]
        }
    },
    "aggs": {
		"category.keyword": {
			"terms": {
				"field": "category.keyword",
				"size": 1000,
				"order": {
					"_key": "asc"
				}
			}
		}
	}
}


if __name__ == '__main__':

    with_es = es.search(index='allproductprices', body=body)
    print('RESPONSE', with_es)
```

**Comment by sethmlarson** [comment]
This is likely an issue with the AWS API Gateway, the client is tested against only the Elasticsearch API so if it receives something that isn't JSON it's likely to give an error like this. If it's possible you could turn on logging via:

```python
import logging
logger = logging.getLogger("elasticsearch.trace")
logger.addHandler(logging.StreamHandler())
logger.setLevel(logging.DEBUG)

... <do the query here>
```

From here you can see what the HTTP response body looks like before its fed to the Deserializer. This will likely give you a clue what AWS is returning that's making the library unhappy.

**Comment by lslee714** [comment]
Thanks for the quick response and handy snippet. So it looks like you're correct if I'm reading this correctly:

```
curl -H 'Content-Type: application/json' -XPOST 'http://localhost:9200/allproductprices/_search?pretty' -d '{
  "aggs": {
    "category.keyword": {
      "terms": {
        "field": "category.keyword",
        "order": {
          "_key": "asc"
        },
        "size": 1000
      }
    }
  },
  "query": {
    "bool": {
      "must": [
        {
          "match": {
            "vendor_id": 103
          }
        }
      ]
    }
  }
}'
#[200] (0.642s)
#{"took":13,"timed_out":false,"_shards":{"total":1,"successful":1,"skipped":0,"failed":0},"hits":{"total":{"value":10000,"relation":"gte"},"max_score":1.0,"hits":[{"_index":"allproductprices","_type":"_doc","_id":"5db861ff877b35000bff99a1","_score":1.0,"_source":{"sub_category":"Accessories","diameter":null,"height":96.0,"store_product_id":"301315646","package_depth":null,"color":null,"has_package_dimension":null,"package_height":null,"location_name":"Arvada, Colorado","store_url":"https://www.homedepot.com/p/AFCO-6-in-x-8-ft-Wicker-Non-Tapered-Fluted-Round-Shaft-Load-Bearing-Endura-Aluminum-Column-EA0608ANFSDTUTU/301315646","last_updated":"2020-07-20T04:24:47.504Z","depth":6.0,"description":"Endura-Aluminum columns are a solid choice for your home improvement needs. Durable and beautiful, these columns add incredible value to your home. In addition, they are virtually maintenance-free, easy to install and have the option of load-bearing capabilities, all at the fraction of the cost of traditional columns.\tMax load-bearing capacity of 20,000 lbs.. Can be trimmed to exact height. Virtually maintenance-free with a durable powder coat finish. Perfect for residential and commercial applications. Great choice to use on remodels and new construction projects","type":null,"finish":null,"weight_unit":null,"material_store_id":"301315646_Hom","depth_unit":"inches","color_finish_family":null,"sub_category_id":null,"price":161.33,"vendor_id":103,"volume":null,"product_name":"6 in. x 8 ft. Wicker Non-Tapered Fluted Round Shaft Load-Bearing Endura-Aluminum Column","width_unit":"inches","product_sku":null,"returnable":"180-day","diameter_unit":null,"material":"aluminum","currency":"USD","product_unit":null,"warranty":null,"id":48606,"display_name":null,"width":6.0,"wood_species":null,"weight":null,"model_name":null,"for_estimation":false,"@version":"1","store_name":"HomeDepot","category":"Columns","is_easy_to_carry":null,"package_width":null,"takeoffs_product_id":"301315646_arvada_colorado_Hom","category_id":null,"series_name":null,"source":null,"brand":null,"category_name":null,"manufacturer_number":null,"product_image_url":"https://images.homedepot-static.com/productImages/0871e4d3-d99d-4d83-bf47-50e1097634a4/svn/afco-caps-bases-accessories-ea0608anfsdtutu-64_400_compressed.jpg","height_unit":"inches","product_id":"5db861ff877b35000bff99a1","contract_price":null,"details_id":null,"manufacturer_color_finish":null,"package_quantity":null,"size":null,"@timestamp":"2020-07-28T23:38:58.099Z","product_images":["https://images.homedepot-static.com/productImages/0871e4d3-d99d-4d83-bf47-50e1097634a4/svn/afco-caps-bases-accessories-ea0608anfsdtutu-64_1000.jpg"],"discount_details":null}},{"_index":"allproductprices","_type":"_doc","_id":"5db861fa877b35000bff9993","_score":1.0,"_source":{"sub_category":"Accessories","diameter":null,"height":108.0,"store_product_id":"301316415","package_depth":null,"color":null,"has_package_dimension":null,"package_height":null,"location_name":"Arvada, Colorado","store_url":"https://www.homedepot.com/p/AFCO-7-1-2-in-x-9-ft-Wicker-Non-Tapered-Fluted-Square-Shaft-Endura-Aluminum-Column-EA0809INFSDTUTU/301316415","last_updated":"2020-07-20T04:24:41.242Z","depth":7.5,"description":"Endura-Aluminum columns are a solid choice for your home improvement needs. Durable and beautiful, these columns add incredible value to your home. In addition, they are virtually maintenance-free, easy to install and have the option of load-bearing capabilities, all at the fraction of the cost of traditional columns.\tCan be trimmed to exact height. Virtually maintenance-free with a durable powder coat finish. Perfect for residential and commercial applications. Great choice to use on remodels and new construction projects. For post wrap installation","type":null,"finish":null,"weight_unit":null,"material_store_id":"301316415_Hom","depth_unit":"inches","color_finish_family":null,"sub_category_id":null,"price":329.23,"vendor_id":103,"volume":null,"product_name":"7-1/2 in. x 9 ft. Wicker Non-Tapered Fluted Square Shaft Endura-Aluminum Column","width_unit":"inches","product_sku":null,"returnable":"180-day","diameter_unit":null,"material":"aluminum","currency":"USD","product_unit":null,"warranty":null,"id":48602,"display_name":null,"width":7.5,"wood_species":null,"weight":null,"model_name":null,"for_estimation":false,"@version":"1","store_name":"HomeDepot","category":"Columns","is_easy_to_carry":null,"package_width":null,"takeoffs_product_id":"301316415_arvada_colorado_Hom","category_id":null,"series_name":null,"source":null,"brand":null,"category_name":null,"manufacturer_number":null,"product_image_url":"https://images.homedepot-static.com/productImages/dc326fae-ffe8-49ae-b1e8-979f215b026b/svn/afco-caps-bases-accessories-ea0809infsdtutu-64_400_compressed.jpg","height_unit":"inches","product_id":"5db861fa877b35000bff9993","contract_price":null,"details_id":null,"manufacturer_color_finish":null,"package_quantity":null,"size":null,"@timestamp":"2020-07-28T23:38:58.100Z","product_images":["https://images.homedepot-static.com/productImages/dc326fae-ffe8-49ae-b1e8-979f215b026b/svn/afco-caps-bases-accessories-ea0809infsdtutu-64_1000.jpg"],"discount_details":null}},{"_index":"allproductprices","_type":"_doc","_id":"5e9364369ff764000bc76690","_score":1.0,"_source":{"sub_category":"Accessories","diameter":null,"height":null,"store_product_id":null,"package_depth":null,"color":null,"has_package_dimension":null,"package_height":null,"location_name":"Arvada, Colorado","store_url":"https://www.homedepot.com/p/AFCO-3-1-2-in-x-10-ft-Wicker-Non-Tapered-Fluted-Square-Shaft-Load-Bearing-Endura-Aluminum-Column-EA0410ENFSDTUTU/301316349","last_updated":null,"depth":null,"description":null,"type":null,"finish":null,"weight_unit":null,"material_store_id":null,"depth_unit":null,"color_finish_family":null,"sub_category_id":null,"price":177.69,"vendor_id":103,"volume":null,"product_name":"3-1/2 in. x 10 ft. Wicker Non-Tapered Fluted Square Shaft Load-Bearing Endura-Aluminum Column","width_unit":null,"product_sku":null,"returnable":null,"diameter_unit":null,"material":null,"currency":"USD","product_unit":null,"warranty":null,"id":null,"display_name":null,"width":null,"wood_species":null,"weight":null,"model_name":null,"for_estimation":false,"@version":"1","store_name":"HomeDepot","category":"Columns","is_easy_to_carry":null,"package_width":null,"takeoffs_product_id":"301316349_arvada_colorado_Hom","category_id":null,"series_name":null,"source":null,"brand":null,"category_name":null,"manufacturer_number":null,"product_image_url":"https://images.homedepot-static.com/productImages/dc326fae-ffe8-49ae-b1e8-979f215b026b/svn/afco-caps-bases-accessories-ea0410enfsdtutu-64_400_compressed.jpg","height_unit":null,"product_id":"5e9364369ff764000bc76690","contract_price":null,"details_id":null,"manufacturer_color_finish":null,"package_quantity":null,"size":null,"@timestamp":"2020-07-28T23:38:58.120Z","product_images":null,"discount_details":null}},{"_index":"allproductprices","_type":"_doc","_id":"5ef3a284eacbf93a5a910e69","_score":1.0,"_source":{"sub_category":"Accessories","diameter":null,"height":108.0,"store_product_id":"301315560","package_depth":null,"color":null,"has_package_dimension":null,"package_height":null,"location_name":"Arvada, Colorado","store_url":"https://www.homedepot.com/p/AFCO-5-1-2-in-x-9-ft-Wicker-Non-Tapered-Square-Shaft-Load-Bearing-Endura-Aluminum-Wellington-Style-Column-EA0609ENPSFWEWE/301315560","last_updated":"2020-07-20T04:20:32.834Z","depth":5.5,"description":"Endura-Aluminum columns are a solid choice for your home improvement needs. Durable and beautiful, these columns add incredible value to your home. In addition, they are virtually maintenance-free, easy to install and have the option of load-bearing capabilities, all at the fraction of the cost of traditional columns.Error occured while trying to proxy to: our-proxy-domain-name.io/allproductprices/_search
```

It looks like the proxy is trying to proxy to port 9200 and it returns that response above with the `Error occured while trying to proxy to: our-proxy-domain-name.io/allproductprices/_search` as part of the response which causes the deserializer to fail?

If so, I'll continue my chat w/ AWS and close this, unless you have other ideas!

**Comment by sethmlarson** [comment]
Yeah this is definitely an AWS issue, they're truncating the JSON response with that text error message. I'd continue the discussion with them.

**Comment by lslee714** [comment]
Thanks Seth, still odd using `requests` directly doesnt seem to error though :confused:

**Comment by sethmlarson** [comment]
It should error if you call Response.json() since it's not valid JSON.

**Comment by lslee714** [comment]
That's the thing, it doesn't error and I'm have a valid dictionary with it and my downstream parsing of it works 

```
        #TODO try and see if we can use the elasticsearch client, currently getting malformed response from aws
        #This is a hack to move forward for now
        res =  requests.post(f"{elastisearch_proxy}/{self.INDEX_NAME}/_search", headers={
            'x-api-key': api_key
        }, json=categories_query)
        raw_result = res.json()
        buckets = raw_result['aggregations']['category.keyword']['buckets']
        ... do the parsing ...
``` 

I submitted the logs of it I have to the open ticket on AWS I made earlier to see if they find anything.
