### ISSUE TITLE
Message send multiple times?

### ISSUE THREAD

**Issue by xlr-8** [elastic/elasticsearch-py#165]
Hello,

I'm facing a weird situation when I try to restore a snapshot on a freshly created es-cluster, it tells me that a restore action is already running (?!). This is the only cluster in which it happens - as I have multiple environment working fine with the same script/version - , and it was working fine still until 6 days ago.

The script waits for the cluster to response that its 3 nodes are ready, and then create a repository then restore data from S3:

<pre>
2014-12-15 08:12:22,153 [CRITICAL] - Retrieving cluster status failed: ConnectionError(('Connection aborted.', BadStatusLine("''",))) caused by: ProtocolError(('Connection aborted.', BadStatusLine("''",)))
Waiting for elastic search cluster to be ready...
2014-12-15 08:12:52,202 [INFO] - Cluster search-cluster READY
2014-12-15 08:12:52,611 [INFO] - Repository snap-repo successfully created
Traceback (most recent call last):
  File "./script.py", line 358, in <module>
    DATA, REGION, args.restore) is False:
  File "./script.py", line 281, in create_env
    if es.create_repository() is False or es.restore_snapshot() is False:
  File "snapshot_elasticsearch.py", line 255, in restore_snapshot
    master_timeout=self.search_timeout, wait_for_completion=True)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 68, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/snapshot.py", line 114, in restore
    repository, snapshot, '_restore'), params=params, body=body)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 284, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 55, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.py", line 97, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(503, u'RemoteTransportException[[search-node-01][inet[/xxx.xxx.xxx.xxx:9300]][cluster/snapshot/restore]]; nested: ConcurrentSnapshotExecutionException[[bucket:snap] Restore process is already running in this cluster]; ')
</pre>

The version of pip & Python:

<pre>
# python --version
Python 2.7.3
# pip freeze | grep -i elastic
elasticsearch==1.2.0
elasticsearch-curator==2.0.0
</pre>

The version of elasticsearch on the client & version of python:

<pre>
# dpkg -l | grep elasticsearch
ii  elasticsearch                      1.2.2                         all          Open Source, Distributed, RESTful Search Engine
# python --version
Python 2.7.3
</pre>

I fee like mutliple messages could be sent to the cluster, because after rechecking the code, I'm creating the repository and restoring only once in an 'if' and exiting if it fails.

I have been unable to reproduce this issue, which makes it harder to debug.

Any help would be much appreciated :)

Thank for the good work,

Cheers,

**Comment by xlr-8** [comment]
Okay, thank you!
