### ISSUE TITLE
when I use elstic 8.01. I got this:

### ISSUE THREAD

**Issue by fishmisswater** [elastic/elasticsearch-py#1931]
DeprecationWarning: Passing transport options in the API method is deprecated. Use 'Elasticsearch.options()' instead.
  helpers.bulk(es,actions,request_timeout=60)

code:`helpers.bulk(es,actions,request_timeout=60)`
It's normal when I use elstic 7.*

**Comment by sethmlarson** [comment]
Yeah, since `request_timeout` is a transport option (instead of an API option) you can do this:

```python
helpers.bulk(es.options(request_timeout=60), actions)
```

Hope that answers your question.

**Comment by fishmisswater** [comment]
thank you bro. Unfortunately, there still have error:

`Traceback (most recent call last):
  File "E:\code\py\my\data\elk_qq.py", line 34, in <module>
    helpers.bulk(es.options(request_timeout=60), actions)
  File "C:\python3\lib\site-packages\elasticsearch\helpers\actions.py", line 524, in bulk
    for ok, item in streaming_bulk(
  File "C:\python3\lib\site-packages\elasticsearch\helpers\actions.py", line 438, in streaming_bulk
    for data, (ok, info) in zip(
  File "C:\python3\lib\site-packages\elasticsearch\helpers\actions.py", line 355, in _process_bulk_chunk
    yield from gen
  File "C:\python3\lib\site-packages\elasticsearch\helpers\actions.py", line 291, in _process_bulk_chunk_error
    raise error
  File "C:\python3\lib\site-packages\elasticsearch\helpers\actions.py", line 339, in _process_bulk_chunk
    resp = client.bulk(*args, operations=bulk_actions, **kwargs)  # type: ignore[arg-type]
  File "C:\python3\lib\site-packages\elasticsearch\_sync\client\utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "C:\python3\lib\site-packages\elasticsearch\_sync\client\__init__.py", line 673, in bulk
    return self.perform_request(  # type: ignore[return-value]
  File "C:\python3\lib\site-packages\elasticsearch\_sync\client\_base.py", line 321, in perform_request
    raise HTTP_EXCEPTIONS.get(meta.status, ApiError)(
elasticsearch.BadRequestError: BadRequestError(400, 'illegal_argument_exception', 'Action/metadata line [1] contains an unknown parameter [_type]')
`

**Comment by sethmlarson** [comment]
@fishmisswater v8.0 has removed support for document types, what are you passing in via `actions`? Do those items contain a `_type` key?

**Comment by fishmisswater** [comment]
Yes! that is! thank you very much!
