### ISSUE TITLE
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection...

### ISSUE THREAD

**Issue by pylemonorg** [elastic/elasticsearch-py#2041]
# question
In the case of the version environment of python3.9.5, the latest version and multiple historical version packages cannot run normally. The same code runs without problems in python3.6.5. I do not know how to solve this？

> normal operating environment：python3.6.5  elasticsearch==7.9.1 windows10&centos7
> Running the wrong environment: python3.9.5 elasticsearch==7.9.1 windows11

## code
```python
from elasticsearch import Elasticsearch
es = Elasticsearch(
    ['xxxxxx.aliyuncs.com'],
    port=9200,
    http_auth=('user', 'pwd'),
)
print(es.info())
es.close()
```

## Error log
```txt
Traceback (most recent call last):
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Apps\python39\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\Apps\python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Apps\python39\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 245, in perform_request
    response = self.pool.urlopen(
  File "D:\Apps\python39\lib\site-packages\urllib3\connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "D:\Apps\python39\lib\site-packages\urllib3\util\retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Apps\python39\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "D:\Apps\python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Apps\python39\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\Apps\python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Apps\python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Apps\python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Apps\python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "D:\Apps\python39\lib\http\client.py", line 948, in send
    self.connect()
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x000001C9ECA18460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Apps\python39\lib\site-packages\elasticsearch\transport.py", line 390, in perform_request
    raise e
  File "D:\Apps\python39\lib\site-packages\elasticsearch\transport.py", line 358, in perform_request
    status, headers_response, data = connection.perform_request(
  File "D:\Apps\python39\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 258, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x000001C9ECA18460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x000001C9ECA18460>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed)

Process finished with exit code 1
```

**Comment by pylemonorg** [comment]
# question
I use the same version of python and all packages, and found that only win11 cannot run, and the system environment of centos7 and win10 can run normally!

## code
```python
from elasticsearch import Elasticsearch

es = Elasticsearch(
    ['http://user:pwd@xxxxx.aliyuncs.com:9200'],
)
print(es.info())
es.close()
```

## win11 error log
```txt
Traceback (most recent call last):
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "D:\Apps\python39\lib\site-packages\urllib3\util\connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "D:\Apps\python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Apps\python39\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 251, in perform_request
    response = self.pool.urlopen(
  File "D:\Apps\python39\lib\site-packages\urllib3\connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "D:\Apps\python39\lib\site-packages\urllib3\util\retry.py", line 525, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "D:\Apps\python39\lib\site-packages\urllib3\packages\six.py", line 770, in reraise
    raise value
  File "D:\Apps\python39\lib\site-packages\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "D:\Apps\python39\lib\site-packages\urllib3\connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "D:\Apps\python39\lib\http\client.py", line 1253, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "D:\Apps\python39\lib\http\client.py", line 1299, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "D:\Apps\python39\lib\http\client.py", line 1248, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "D:\Apps\python39\lib\http\client.py", line 1008, in _send_output
    self.send(msg)
  File "D:\Apps\python39\lib\http\client.py", line 948, in send
    self.connect()
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 205, in connect
    conn = self._new_conn()
  File "D:\Apps\python39\lib\site-packages\urllib3\connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x0000023EECB6A6A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python_demo\spider_demo\opinion_article_spider\news_spider\news_spider\junk\es 测试.py", line 16, in <module>
    print(es.info())
  File "D:\Apps\python39\lib\site-packages\elasticsearch\client\utils.py", line 168, in _wrapped
    return func(*args, params=params, headers=headers, **kwargs)
  File "D:\Apps\python39\lib\site-packages\elasticsearch\client\__init__.py", line 294, in info
    return self.transport.perform_request(
  File "D:\Apps\python39\lib\site-packages\elasticsearch\transport.py", line 413, in perform_request
    raise e
  File "D:\Apps\python39\lib\site-packages\elasticsearch\transport.py", line 381, in perform_request
    status, headers_response, data = connection.perform_request(
  File "D:\Apps\python39\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 264, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x0000023EECB6A6A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x0000023EECB6A6A0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed)
```

**Comment by linhChi2208** [comment]
Hello, I have the same problem. I use win11. Did you find the solution for this problem? Thank you.
