### ISSUE TITLE
Error connecting from a container to a local elasticsearch cluster:<SSLV3_ALERT_ILLEGAL_PARAMETER>

### ISSUE THREAD

**Issue by vivek87799** [elastic/elasticsearch-py#2124]
**Elasticsearch 8.5.2**:

**`elasticsearch-py` version (`8.5.3`)**: 
**`python` version (`3.9`)**: 
**`openjdk` version (`1.8.0_352 `)**: 

**Not able to establish a connection from a container node running ubuntu:jammy to the elasticsearch server hosted on a separate container in the same network**:

**Steps to reproduce**:
1) Used the official docker-compose.yml provided in the documentation to spin up the elasticsearch servers. (able to connect and index documents from the host machine using elasticsearch-py)
2) Using elasticsearch-py to connect to the elasticsearch server from another docker container 
3) Enabled additional SSL/TLS versions on  JDK by removing SSLv3, TLSv1, TLSv1.1 from jdk.tls.disabledAlgorithms in java.securities
4) Appened the ca.crt generated under config/certs/ca/ into the certifi

```
>>> import certifi
>>>client = Elasticsearch("https://container_name:9200", basic_auth=("elastic", "elasticpassword"), verify_certs=True,)
>>>client.info()

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
    return api(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/__init__.py", line 2296, in info
    return self.perform_request(  # type: ignore[return-value]
  File "/usr/local/lib/python3.10/dist-packages/elasticsearch/_sync/client/_base.py", line 286, in perform_request
    meta, resp_body = self.transport.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_transport.py", line 329, in perform_request
    meta, raw_data = node.perform_request(
  File "/usr/local/lib/python3.10/dist-packages/elastic_transport/_node/_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: SSLV3_ALERT_ILLEGAL_PARAMETER] sslv3 alert illegal parameter (_ssl.c:997)))

```

**Comment by vivek87799** [comment]
### Solution:
```
cp ca.crt /usr/local/share/ca-certificates/
chmod 644 /usr/local/share/ca-certificates/ca.crt
update-ca-certificates
```
