### ISSUE TITLE
elastic_transport.TlsError: TLS error caused by: TlsError

### ISSUE THREAD

**Issue by leizhu1989** [elastic/elasticsearch-py#2178]
hello, author

my environment：
system：windows11
python：3.7
elasticsearch：8.1.2
elasticsearch-py：8.1.2
elastic-transport：8.1.2

when I run demo：
from elasticsearch import Elasticsearch

es = Elasticsearch(
    "https://localhost:9200"
)
resp = es.info()
print (resp)

I got this error：
Traceback (most recent call last):
  File "test_first.py", line 7, in <module>
    resp = es.info()
  File "D:\project\Elasticsearch\elasticsearch-py\elasticsearch\_sync\client\utils.py", line 404, in wrapped
    return api(*args, **kwargs)
  File "D:\project\Elasticsearch\elasticsearch-py\elasticsearch\_sync\client\__init__.py", line 2249, in info
    "GET", __path, params=__query, headers=__headers
  File "D:\project\Elasticsearch\elasticsearch-py\elasticsearch\_sync\client\_base.py", line 295, in perform_request
    client_meta=self._client_meta,
  File "C:\Users\zhulei\.conda\envs\nlp_sentence_0\lib\site-packages\elastic_transport\_transport.py", line 334, in perform_request
    request_timeout=request_timeout,
  File "C:\Users\zhulei\.conda\envs\nlp_sentence_0\lib\site-packages\elastic_transport\_node\_http_urllib3.py", line 199, in perform_request
    raise err from None
elastic_transport.TlsError: TLS error caused by: TlsError(TLS error caused by: SSLError([SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1091)))

is ssl version wrong? what should I do

**Comment by ezimuel** [comment]
@leizhu1989 Starting with Elasticsearch 8 we introduced a [security by default](https://www.elastic.co/blog/introducing-simplified-elastic-stack-security) approach. That means you need to connect using TLS and providing authorization (i.e. certificate). You can read how to connect to a self managed Elasticsearch in the [documentation](https://www.elastic.co/guide/en/elasticsearch/client/python-api/current/connecting.html#connect-self-managed-new). Let me know if you need more help, thanks!

**Comment by leizhu1989** [comment]
I will try again , Thank you for your reply!

**Comment by ffletcherr** [comment]
try this if you have elastic on a host and don't have port:
```
pip install elasticsearch7
```

```python
# your python script
from elasticsearch7 import Elasticsearch


client = Elasticsearch(
    "https://elastic:your_password@your_elastic_host.com",
)

client.info()
```

**Comment by pquentin** [comment]
For reference, `WRONG_VERSION_NUMBER` usually means that you're trying to connect to an HTTP endpoint using HTTPS. The fix in your case is to specify `http://localhost:9200` instead of `https://localhost:9200`.
