### ISSUE TITLE
Exception OverflowError: int too large to convert to float

### ISSUE THREAD

**Issue by keklick1337** [elastic/elasticsearch-py#2262]
Elasticsearch 8.7.1 from dockerhub

elasticsearch-py __versionstr__ = "8.7.0"

Description:
When i index document by cURL, i don't have any problems, but, when i tried to index by python, i got an exception:
```
Traceback (most recent call last):
  File "/code/logs_server.py", line 117, in parsePasswordstxt
     elworker.addDocument(elastic_document)
   File "/code/lib/elastic_lib.py", line 64, in addDocument
    self.client_elastic.index(index=self.index_name, id=recordhash, document=document, op_type='create')                                                                                           File "/usr/local/lib/python3.11/site-packages/elasticsearch/_sync/client/utils.py", line 414, in wrapped
     return api(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elasticsearch/_sync/client/__init__.py", line 2316, in index
    return self.perform_request(  # type: ignore[return-value]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                     File "/usr/local/lib/python3.11/site-packages/elasticsearch/_sync/client/_base.py", line 285, in perform_request
    meta, resp_body = self.transport.perform_request(
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/elastic_transport/_transport.py", line 413, in perform_request                                                                                       self.node_pool.mark_dead(node)
  File "/usr/local/lib/python3.11/site-packages/elastic_transport/_node_pool.py", line 242, in mark_dead
    self._dead_node_backoff_factor * (2 ** (consecutive_failures - 1)),
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
OverflowError: int too large to convert to float
```

I have 550 million documents in index, and i got this error today. I don't know how to reproduce it.

Values dump from exception:
```python
consecutive_failures = 13292
self._dead_node_backoff_factor = 1.0
self._max_dead_node_backoff = 30.0
node.config: NodeConfig(scheme='http',
                        host='dataleakelastic',
                        port=9200,
                        path_prefix='',
                        headers={
                            'authorization': 'Basic <hidden>',
                            'user-agent': 'elasticsearch-py/8.7.0 (Python/3.11.3; elastic-transport/8.4.0)'
                            },
                        connections_per_node=10,
                        request_timeout=10.0,
                        http_compress=False,
                        verify_certs=True,
                        ca_certs=None,
                        client_cert=None,
                        client_key=None,
                        ssl_assert_hostname=None,
                        ssl_assert_fingerprint=None,
                        ssl_version=None,
                        ssl_context=None,
                        ssl_show_warn=True,
                        _extras={}
                    )
```

Help me please, why consecutive_failures is too big? Everything with my Elasticsearch is ok, and i can add documents by cURL .

**Comment by shimasima2323** [comment]
I see the same error, i use ```create``` method, on some existing document this function should raise ```ConflictError```, but raises:
```OverflowError: int too large to convert to float```
i use elasticsearch 8.8.1 with python client 8.8.0

**Comment by keklick1337** [comment]
for hotfix i changed 

```python
        timeout = min(
            self._dead_node_backoff_factor * (2 ** (consecutive_failures - 1)),
            self._max_dead_node_backoff,
        )
```

to 
```python
        if consecutive_failures > 5:
            consecutive_failures = 5
        timeout = min(
            self._dead_node_backoff_factor * (2 ** (consecutive_failures - 1)),
            self._max_dead_node_backoff,
        )
```

in `/usr/local/lib/python3.11/site-packages/elastic_transport/_node_pool.py` file

**Comment by N0vel** [comment]
The same issue on elastic 8.8.2 and client elasticsearch[async]==8.8.2, but a slightly different case: when ElasticSearch node died and then was fixed, the service cannot mark the node as dead due to this overflow error and the node is considered healthy and stays in the connection pool. It leads to consecutive failed calls to a dead node until the client is restarted.

**Comment by JoshMock** [comment]
Thanks for reporting this, everyone. :black_heart: Seems like the following transport code needs to set the backoff value to `self._max_dead_node_backoff` when it catches an `OverflowError`. I'll see about making a quick fix there.

https://github.com/elastic/elastic-transport-python/blob/2d74209c71fd3db5683a38d9d2a2e39f5af674e4/elastic_transport/_node_pool.py#L241-L244

**Comment by JoshMock** [comment]
[elastic-transport 8.4.1](https://github.com/elastic/elastic-transport-python/releases/tag/v8.4.1) has been published to PyPI, which should resolve this issue. Please feel free to reopen if the issue persists after a fresh install.
