### ISSUE TITLE
ping throws exception instead of just returning "False"

### ISSUE THREAD

**Issue by beomagi** [elastic/elasticsearch-py#239]
I'm using the following construct with python 3.4:

\>\>\> es = Elasticsearch("not_a_server")
\>\>\> es.ping()

HEAD http://not_a_server:9200/ [status:N/A request:0.005s]
Traceback (most recent call last):
  File "/appserver/python/lib/python3.4/site-packages/urllib3-1.8-py3.4.egg/urllib3/connectionpool.py", line 485, in urlopen
    body=body, headers=headers)
  File "/appserver/python/lib/python3.4/site-packages/urllib3-1.8-py3.4.egg/urllib3/connectionpool.py", line 283, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/appserver/python/lib/python3.4/http/client.py", line 1066, in request
    self._send_request(method, url, body, headers)
  File "/appserver/python/lib/python3.4/http/client.py", line 1104, in _send_request
    self.endheaders(body)
  File "/appserver/python/lib/python3.4/http/client.py", line 1062, in endheaders
    self._send_output(message_body)
  File "/appserver/python/lib/python3.4/http/client.py", line 907, in _send_output
    self.send(msg)
  File "/appserver/python/lib/python3.4/http/client.py", line 842, in send
    self.connect()
  File "/appserver/python/lib/python3.4/site-packages/urllib3-1.8-py3.4.egg/urllib3/connection.py", line 103, in connect
    conn = self._new_conn()
  File "/appserver/python/lib/python3.4/site-packages/urllib3-1.8-py3.4.egg/urllib3/connection.py", line 90, in _new_conn
    *extra_args
  File "/appserver/python/lib/python3.4/socket.py", line 491, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/appserver/python/lib/python3.4/socket.py", line 530, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:
...
...
...
.... several pages of exceptions

Even suppressing these doesn't work, though I shouldn't.

**Comment by HonzaKral** [comment]
When I try to replicate this I get the exception as well but I get returned `False` correctly - the stacktrace is just part of logging.

Can you please verify if that's the case for you as well?

Thanks!

**Comment by beomagi** [comment]
Thanks for responding!

Yes, it does return false for me too.

On trying to suppress the exception, which I guess should be within the function, I still get the exception output.

**Comment by HonzaKral** [comment]
That's just logging, not actual output. You can configure the logging to ignore the warning messages or just redirect it to a file. `elasticsearch-py` uses the standard logging library in python (https://docs.python.org/3/howto/logging.html) so you can simply use configuration to hide the output.

Either way it doesn't affect behavior, it's just logging output so I will close this issue.

**Comment by beomagi** [comment]
Thanks!
