### ISSUE TITLE
low-level error on bulk helper

### ISSUE THREAD

**Issue by vchalmel** [elastic/elasticsearch-py#2617]
I receive an error I didn't have previously on any bulk index I'm doing, and it's apparently the only thing not working on my connection, I can otherwise ping, query etc.

**Elasticsearch version 8.14.1:

**`elasticsearch-py` version 8.14.3: 

Please make sure the major version matches the Elasticsearch server you are running.

**Description of the problem including expected versus actual behavior**:

Exception on bulk index 

```Traceback (most recent call last):
  File "/home/vch/Pycharm/plugins/python-ce/helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
  File "/home/vch/PycharmProjects/analyseDCE/venv/lib/python3.11/site-packages/elasticsearch/helpers/actions.py", line 521, in bulk
    for ok, item in streaming_bulk(
  File "/home/vch/PycharmProjects/analyseDCE/venv/lib/python3.11/site-packages/elasticsearch/helpers/actions.py", line 409, in streaming_bulk
    client = client.options()
             ^^^^^^^^^^^^^^^^
  File "/home/vch/PycharmProjects/analyseDCE/venv/lib/python3.11/site-packages/elasticsearch/_sync/client/__init__.py", line 509, in options
    client = type(self)(_transport=self.transport)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ClientElastic.__init__() got an unexpected keyword argument '_transport'
```

**Steps to reproduce**:

I use the following code for my class (I removed anything not useful for this issue) :

```
ELASTIC_CONFIG = {'hosts': os.environ.get("ELASTICSEARCH_URL"),
                  'basic_auth': (os.environ.get("ELASTICSEARCH_USER"), os.environ.get("ELASTICSEARCH_PASSWORD")),
                  'verify_certs': False,
                  'ssl_show_warn': False}


def ping_elasticsearch(config_dict: Dict[str, Any] = None) -> int:
    if config_dict is None:
        config_dict = ELASTIC_CONFIG

    with Elasticsearch(**config_dict) as elastic_dce:
        try:
            elastic_dce.ping()
            return 0
        except Exception as any_exception:
            return 1


class ClientElastic(Elasticsearch):
    index_name: str = os.environ.get("ELASTICSEARCH_INDEX")

    def __init__(self, config_dict: Dict[str, Any] = None) -> None:
        if config_dict is None:
            config_dict = ELASTIC_CONFIG
        Elasticsearch.__init__(self, **config_dict)

    def __enter__(self) -> "ClientElastic":
        return self

    def __exit__(self, *_: Any):
        self.close()

    def index_document(self,
                  data: Dict[str, Any],
                  raise_on_error: bool = False,
                  stats_only: bool = True) -> int:
        try:
            success, errors = helpers.bulk(client=self,
                                           actions=[{'_op_type': 'index',
                                                     '_index': ClientElastic.index_name, **element}
                                                    for element in data],
                                           stats_only=stats_only,
                                           raise_on_error=raise_on_error)

            if errors and ((isinstance(errors, int) and errors > 0) or (isinstance(errors, list) and len(errors) > 0)):
                return 1
            else:
                return 0

        except Exception as any_exception:
           raise any_exception
```

I get the issue when using the function index_document() but also when instantiating the class and passing the instance when manually calling helpers.bulk(client, etc.)

**Comment by vchalmel** [comment]
Solved, I needed to add kwargs to my super constructor call to avoid the injection of unexpected keword arguments by elasticsearch/_sync/client/__init__.py

**Comment by pquentin** [comment]
Glad that you solved it. Also note that we do not specifically design the client to be subclassed. Following [composition over inheritance](https://en.wikipedia.org/wiki/Composition_over_inheritance), you could design your code like this instead:

```python3
ELASTIC_CONFIG = {
    'hosts': os.environ.get("ELASTICSEARCH_URL"),
    'basic_auth': (os.environ.get("ELASTICSEARCH_USER"), os.environ.get("ELASTICSEARCH_PASSWORD")),
    'verify_certs': False,
    'ssl_show_warn': False,
}

class ClientElastic(Elasticsearch):
    index_name: str = os.environ.get("ELASTICSEARCH_INDEX")

    def __init__(self, config_dict: Dict[str, Any] = None) -> None:
        if config_dict is None:
            config_dict = ELASTIC_CONFIG
        self.client = Elasticsearch(**config_dict)

    def __enter__(self) -> "ClientElastic":
        return self

    def __exit__(self, *_: Any):
        self.client.close()

    def index_document(self, ...) -> int:
        helpers.bulk(self.client, ...)
```
