### ISSUE TITLE
Version 2.1 "sniff_on_start" failure. 

### ISSUE THREAD

**Issue by KsaRedFx** [elastic/elasticsearch-py#293]
Using any form of sniff with your ElasticSearch connection parameters results in it timing out almost immediately and failing to connect. Previous versions of this driver (1.6) worked fine. 

Using the default configuration found in the docs 
http://elasticsearch-py.readthedocs.org/en/master/index.html#sniffing

```py
# you can also sniff periodically and/or after failure:
es = Elasticsearch(["seed1", "seed2"], sniff_on_start=True, sniff_on_connection_fail=True, sniffer_timeout=60)
```

Any combination of these parameters fails

**Comment by HonzaKral** [comment]
I cannot replicate this issue, would you mind pasting somewhere the exception and running `1.6` and `2.1` versions on the same environment? There has been no change to the code managing the sniffing or connection handling between 1.6 and 2.1.

As a work around you can also make the sniff timeout larger by setting the `timeout` parameter of the client to a higher value.

**Comment by KsaRedFx** [comment]
The `1.6` version operates without issue.
The `2.1` version gives this exception;

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "core/pooling.py", line 6, in <module>
    es = elasticsearch.Elasticsearch(**config.db.elastic)
  File
"/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py",
line 150, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py",
line 130, in __init__
    self.sniff_hosts(True)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py",
line 237, in sniff_hosts
    raise TransportError("N/A", "Unable to sniff hosts - no viable hosts
found.")
elasticsearch.exceptions.TransportError: TransportError(N/A, 'Unable to
sniff hosts - no viable hosts found.')
```

The exact config it is given is as follows:
```json
        "elastic": {
            "hosts": "localhost",
            "sniff_on_start": true,
            "sniff_on_connection_fail": true,
            "sniffer_timeout": 60,
            "timeout": 60,
        }
```

Changing timeout does nothing.
If I remove sniff_on_start then when the connection fails it raises the
same error.

I am able to do a CURL for the HTTP call it is making.

```json
{
  "cluster_name" : "matrix.master",
  "nodes" : {
    "keIhPnGaTtS3iyLC-u_cgQ" : {
      "name" : "matrix-es0",
      "transport_address" : "<HOST 1>:9300",
      "host" : "<HOST 1>",
      "ip" : "<HOST 1>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 1>:9200",
      "attributes" : {
        "master" : "true"
      }
    },
    "M1lrcH-GTVm0YRnae-3Stw" : {
      "name" : "nostalgia-es0",
      "transport_address" : "<HOST 2>:9300",
      "host" : "<HOST 2>",
      "ip" : "<HOST 2>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 2>:9200",
      "attributes" : {
        "master" : "true"
      }
    },
    "rT52-BfRRpSa4Td4R3eDXQ" : {
      "name" : "nostalgia-es1",
      "transport_address" : "<HOST 2>:9301",
      "host" : "<HOST 2>",
      "ip" : "<HOST 2>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 2>:9201",
      "attributes" : {
        "master" : "true"
      }
    },
    "0nFwPq0OSE6RA1rdkEfS2Q" : {
      "name" : "matrix-es1",
      "transport_address" : "<HOST 1>:9301",
      "host" : "<HOST 1>",
      "ip" : "<HOST 1>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 1>:9201",
      "attributes" : {
        "master" : "true"
      }
    }
  }
}

```

**Comment by KsaRedFx** [comment]
The `1.6` version operates without issue. 
The `2.1` version gives this exception; 

```py
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "core/pooling.py", line 6, in <module>
    es = elasticsearch.Elasticsearch(**config.db.elastic)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 150, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 130, in __init__
    self.sniff_hosts(True)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 237, in sniff_hosts
    raise TransportError("N/A", "Unable to sniff hosts - no viable hosts found.")
elasticsearch.exceptions.TransportError: TransportError(N/A, 'Unable to sniff hosts - no viable hosts found.')
```

The exact config it is given is as follows:
```json
        "elastic": {
            "hosts": "localhost", 
            "sniff_on_start": true, 
            "sniff_on_connection_fail": true,
            "sniffer_timeout": 60,
            "timeout": 60,
        }
```

Changing timeout does nothing. 
If I remove sniff_on_start then when the connection fails it raises the same error. 

I am able to do a CURL for the HTTP call it is making. 

```json
{
  "cluster_name" : "matrix.master",
  "nodes" : {
    "keIhPnGaTtS3iyLC-u_cgQ" : {
      "name" : "matrix-es0",
      "transport_address" : "<HOST 1>:9300",
      "host" : "<HOST 1>",
      "ip" : "<HOST 1>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 1>:9200",
      "attributes" : {
        "master" : "true"
      }
    },
    "M1lrcH-GTVm0YRnae-3Stw" : {
      "name" : "nostalgia-es0",
      "transport_address" : "<HOST 2>:9300",
      "host" : "<HOST 2>",
      "ip" : "<HOST 2>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 2>:9200",
      "attributes" : {
        "master" : "true"
      }
    },
    "rT52-BfRRpSa4Td4R3eDXQ" : {
      "name" : "nostalgia-es1",
      "transport_address" : "<HOST 2>:9301",
      "host" : "<HOST 2>",
      "ip" : "<HOST 2>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 2>:9201",
      "attributes" : {
        "master" : "true"
      }
    },
    "0nFwPq0OSE6RA1rdkEfS2Q" : {
      "name" : "matrix-es1",
      "transport_address" : "<HOST 1>:9301",
      "host" : "<HOST 1>",
      "ip" : "<HOST 1>",
      "version" : "2.0.0",
      "build" : "de54438",
      "http_address" : "<HOST 1>:9201",
      "attributes" : {
        "master" : "true"
      }
    }
  }
}

```

**Comment by HonzaKral** [comment]
Are you talking to the same ES version? It looks like there is a bug with the sniffing process that doesn't work with Elasticsearch 2.0.

Also I am a bit confused - are those nodes all master nodes only?

**Comment by KsaRedFx** [comment]
Yea, I'm using ElasticSearch 2.0 and the ElasticSearch 2.1 Python Library as they're both currently the suggested versions (And the ones that install automatically)

All those nodes are both master + data however it doesn't seem to display data anywhere.

**Comment by HonzaKral** [comment]
This should be fixed in master, could you please verify that on your environment before I do a release?

Thank you!

**Comment by KsaRedFx** [comment]
Sorry for my delay, been a bit busy. 

The modifications you made appear to work fine for me when setting sniff_on_start
I haven't had time to test to see if it actually sniffs properly and locates the other nodes, but it connects to the database and doesn't error when calling sniff_on_start or related parameters.

**Comment by KsaRedFx** [comment]
Is this merged in yet? @HonzaKral
