### ISSUE TITLE
Errors when using RequestsHttpConnection w/ Elasticsearch client

### ISSUE THREAD

**Issue by strife25** [elastic/elasticsearch-py#294]
When changing the `transport_class` of the Elasticsearch client in my code to `RequestsHttpConnection`, I am unable to get the client to work.

The following configurations fail for me:

## `localhost:9200'`
```
from elasticsearch import Elasticsearch
from elasticsearch.connection import RequestsHttpConnection

client = Elasticsearch(hosts=['localhost:9200'], transport_class=RequestsHttpConnection)
client.ping()
```

This results in the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 190, in ping
    self.transport.perform_request('HEAD', '/', params=params)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 73, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))) caused by: ConnectionError(('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known')))
```

## `http://localhost:9200'`
```
from elasticsearch import Elasticsearch
from elasticsearch.connection import RequestsHttpConnection

client = Elasticsearch(hosts=['http://localhost:9200'], transport_class=RequestsHttpConnection)
client.ping()
```

This results in the following exception:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 190, in ping
    self.transport.perform_request('HEAD', '/', params=params)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 73, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known'))) caused by: ConnectionError(('Connection aborted.', gaierror(8, 'nodename nor servname provided, or not known')))
```

## `{'host':'http://localhost', 'port':9200}`
```
from elasticsearch import Elasticsearch
from elasticsearch.connection import RequestsHttpConnection

client = Elasticsearch(
    hosts=[{'host':'http://localhost', 'port':9200}], 
    transport_class=RequestsHttpConnection
)
client.ping()
```

This results in the following exception, which looks to be related to parsing an IPv6 host:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 190, in ping
    self.transport.perform_request('HEAD', '/', params=params)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/elasticsearch/connection/http_requests.py", line 62, in perform_request
    response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/requests/sessions.py", line 451, in request
    prep = self.prepare_request(req)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/requests/sessions.py", line 382, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/requests/models.py", line 304, in prepare
    self.prepare_url(url, params)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/requests/models.py", line 355, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/Users/jryding/.virtualenvs/analytics_api/lib/python2.7/site-packages/requests/packages/urllib3/util/url.py", line 174, in parse_url
    host, url = url.split(']', 1)
ValueError: need more than 1 value to unpack
```

Am I doing something wrong with these configurations?

Ultimately, what I'm trying to do is send requests to AWS' hosted ES via elasticsearch-dsl by using the method and fix proposed in this issue: https://github.com/elastic/elasticsearch-py/issues/280

Thanks!

**Comment by HonzaKral** [comment]
You are using `transport_class` where you want to be using `connection_class` - you don't want to replcae the entire transport mechanism, just the connection class.

**Comment by strife25** [comment]
Holy awesome - that worked!!!! Thanks!
