### ISSUE TITLE
example load.py didn't work

### ISSUE THREAD

**Issue by xiaoping378** [elastic/elasticsearch-py#309]
➜  example git:(1527177) ✗ python load.py 
Traceback (most recent call last):
  File "load.py", line 190, in <module>
    load_repo(es)
  File "load.py", line 132, in load_repo
    create_git_index(client, index)
  File "load.py", line 91, in create_git_index
    'files': {'type': 'string', 'analyzer': 'file_path'}
  File "../elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "../elasticsearch/client/indices.py", line 291, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "../elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "../elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "../elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'illegal_argument_exception')

**Comment by HonzaKral** [comment]
can you please let me know what version of elasticsearch are you using? Also please verify that the fix in da1a8b9 doesn't help. Thank you!

**Comment by xiaoping378** [comment]
Thanks,  Perfect working.
