### ISSUE TITLE
mapping error with same field name

### ISSUE THREAD

**Issue by sho-suzuki** [elastic/elasticsearch-py#325]
i want to define 2 type mapping(manage and time).
```python
class ElasticsearchLib():
    def __init__(self, host, port):
        self.client = Elasticsearch('{}: {}'.format(host, port))  
        self.idxclient = IndicesClient(self.client) 
    
     def create_index_mapping(self, idx):
        self.timemap = {
            "time": {
                "properties": {
                    "db_id": {
                        "type": "string"
                    }
                }
            }
        }
        self.managemap = {
            "manage": {
                "properties": {
                    "db_id": {
                        "type": "long"
                    }
                }
            }
        }
    self.client.indices.create(index=idx, body=self.setting)
    self.idxclient.put_mapping(index=idx, doc_type='time', body=self.timemap)
    self.idxclient.put_mapping(index=idx, doc_type='manage', body=self.managemap)

def main():
    eslib = ElasticsearchLib(localhost,9200)
    eslib.create_index_mapping(idx_db)
```

but It can not be defined out the following error.
```
Traceback (most recent call last):
  File "./es_test.py", line 424, in <module>
    main()
  File "./es_test.py", line 408, in main
    eslib.create_index_mapping(idx_db)
  File "./es_test.py", line 362, in create_index_mapping
    self.idxclient.put_mapping(index=idx, doc_type='manage', body=self.kdb_managemap)
  File "/usr/local/pyenv/versions/devel-3.4.3/lib/python3.4/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/pyenv/versions/devel-3.4.3/lib/python3.4/site-packages/elasticsearch/client/indices.py", line 291, in put_mapping
    '_mapping', doc_type), params=params, body=body)
  File "/usr/local/pyenv/versions/devel-3.4.3/lib/python3.4/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/pyenv/versions/devel-3.4.3/lib/python3.4/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/pyenv/versions/devel-3.4.3/lib/python3.4/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'illegal_argument_exception')
```

if I set manage.type = time.type,  can solve this problem.
how to set different type same field-name's type?

**Comment by HonzaKral** [comment]
This is no longer possible in elasticsearch due to problems with the underlying lucene representation - all the types share the same lucene index to allow users to easily search across types. It is therefore forbidden to have the same field with different types with the same name. In pre 2.0 elasticsearch this was not explicitly forbidden but in rare cases it could result in unexpected behavior, that is why it is now (as of ES 2.0) explicitly checked for and forbidden.

Btw to make this kind of code easier we have created a DSL library that allows you to define your mappings in a declarative manner, you can check it out at http://elasticsearch-dsl.readthedocs.org/en/latest/persistence.html#doctype

**Comment by sho-suzuki** [comment]
Thank you to answer my questions! I understand.
I'll try DSL library.
