### ISSUE TITLE
Possible 2.1.0 -> 2.2.0 regression?

### ISSUE THREAD

**Issue by ApproximateIdentity** [elastic/elasticsearch-py#334]
Hello after upgrading to the newest version of elasticsearch-py, I started getting an error in my code. I stripped down the error to the following test case:

```python
from elasticsearch import Elasticsearch


apostrophe = "\xe2\x80\x98"

document = {
    "id": 1,
    "unicode_apostrophe": apostrophe.decode("utf-8"),
    "encoded_apostrophe": apostrophe}

es = Elasticsearch("http://127.0.0.1:9200")
es.index(index="test", doc_type="document", body=document, id=document["id"])
```

Running that on version 2.1.0 causes no errors and the values for `"unicode_apostrophe"` and `"encoded_apostrophe'"` show up the same in the index. Running it on 2.2.0 results in the following error:

```
Traceback (most recent call last):
  File "test2.py", line 12, in <module>
    es.index(index="test", doc_type="document", body=document, id=document["id"])
  File "/home/administrator/test/venv/local/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/administrator/test/venv/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 261, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/home/administrator/test/venv/local/lib/python2.7/site-packages/elasticsearch/transport.py", line 295, in perform_request
    body = self.serializer.dumps(body)
  File "/home/administrator/test/venv/local/lib/python2.7/site-packages/elasticsearch/serializer.py", line 50, in dumps
    raise SerializationError(data, e)
elasticsearch.exceptions.SerializationError: ({'encoded_apostrophe': '\xe2\x80\x98', 'id': 1, 'unicode_apostrophe': u'\u2018'}, UnicodeDecodeError('ascii', '"\xe2\x80\x98"', 1, 2, 'ordinal not in range(128)'))
```

The change that caused this seems to be in this commit: https://github.com/elastic/elasticsearch-py/commit/c305dc5587963bc9e41ae8cf35bb6eff5afb199e

I'm using Python 2.7.6 (the version that comes packaged with Ubuntu 14.04).

Aside: Obviously the best thing would be to _not_ mix `str` and `unicode` in this fashion (in fact, I'm going to clean up my code to change this which will remove the error for me), but I thought that the developers might want to be aware of this.

**Comment by HonzaKral** [comment]
Thanks for the report. I am not sure if we should do anything about this.

You are using `str` with `utf-8` encoded data in python 2 yet have system encoding set to `ascii`, it probably only worked due to a json-specific implementation detail somewhere. You solution, to use `unicode` (or move to python 3 :) ) is definitely the way to go.

What do people think?

**Comment by mvantellingen** [comment]
This also caused a unicode bug on my side when using the `RequestsHttpConnection`:

    >>> sync.product_update(product)                                  
    Traceback (most recent call last):
      File "<console>", line 1, in <module>
      File "/usr/local/lib/python2.7/dist-packages/something/apps/esindex/index.py", line 111, in product_update
        doc.save()
      File "/usr/local/lib/python2.7/dist-packages/something/apps/esindex/index.py", line 88, in save
        return super(ProductDocument, self).save(** kwargs)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch_dsl/document.py", line 251, in save
        **doc_meta
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
        return func(*args, params=params, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 261, in index
        _make_path(index, doc_type, id), params=params, body=body)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
        status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
      File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_requests.py", line 62, in perform_request
        response = self.session.request(method, url, data=body, timeout=timeout or self.timeout)
      File "/usr/local/lib/python2.7/dist-packages/opbeat/instrumentation/packages/base.py", line 63, in __call__
        args, kwargs)
      File "/usr/local/lib/python2.7/dist-packages/opbeat/instrumentation/packages/base.py", line 220, in call_if_sampling
        return wrapped(*args, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 468, in request
        resp = self.send(prep, **send_kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/sessions.py", line 576, in send
        r = adapter.send(request, **kwargs)
      File "/usr/local/lib/python2.7/dist-packages/requests/adapters.py", line 376, in send
        timeout=timeout
      File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 559, in urlopen
        body=body, headers=headers)
      File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/connectionpool.py", line 353, in _make_request
        conn.request(method, url, **httplib_request_kw)
      File "/usr/lib/python2.7/httplib.py", line 1001, in request
        self._send_request(method, url, body, headers)
      File "/usr/lib/python2.7/httplib.py", line 1035, in _send_request
        self.endheaders(body)
      File "/usr/lib/python2.7/httplib.py", line 997, in endheaders
        self._send_output(message_body)
      File "/usr/lib/python2.7/httplib.py", line 848, in _send_output
        msg += message_body
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 356: ordinal not in range(128)

`msg` is unicode and message_body is a utf-8 encoded string. The system encoding is indeed set to ascii (default python docker image)

**Comment by HonzaKral** [comment]
It is not really supported in python to use utf-8 encoded data in `str` when having system encoding set to `ascii`. The change we made only uncovers the problem - previously we were masking it, and it would break very unpredictably if other encoding that utf-8 were used.

The solution is to use `unicode` when working with non-ascii data or set your encoding properly. Or use Python 3.

I will add it into the Changelog to document the change.
