### ISSUE TITLE
cannot specify range in helpers.scan

### ISSUE THREAD

**Issue by lehuff** [elastic/elasticsearch-py#368]
I'm attempting to restrict searches using the scan helper, but when I add a body arg to restrict a date range on my RealTime field (sample return from a body'less' query: u'RealTime': u'2016-01-25T05:05:16.000Z') I get errors:

```
>>>test = helpers.scan(es, index='project_project_desktop', _source_include=('valueA', 'valueB', 'valueC', 'RealTime', 'valueD', 'valueE'), body={"query": {"range":{"RealTime":{"gte":"now-1d/d","lt":"30d/d"}}}}, scroll='5m')
>>> for each in test:
...     print each
... 
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 273, in scan
    resp = client.search(body=query, scroll=scroll, **kwargs)
TypeError: search() got multiple values for keyword argument 'body'

```

I've tried variations of this with different errors as well:

```
>>> test = helpers.scan(es, index='project_project_desktop', _source_include=('valueA', 'valueB', 'valueC', 'RealTime', 'valueD', 'valueE'), query={"range":{"RealTime":{"gte":"now-1d/d","lt":"30d/d"}}}, scroll='5m')
>>> for each in test:
...     print each
... 
/usr/lib/python2.7/site-packages/urllib3/connectionpool.py:790: InsecureRequestWarning: Unverified HTTPS request is being made. Adding certificate verification is strongly advised. See: https://urllib3.readthedocs.org/en/latest/security.html
  InsecureRequestWarning)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 273, in scan
    resp = client.search(body=query, scroll=scroll, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 530, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 106, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'search_phase_execution_exception', u'failed to parse search source. unknown search element [range]')
```

I've played around with the code a lot, but can't get it to filter down the data into the date ranges I need.

**Comment by HonzaKral** [comment]
the `query` parameter needs to contain the whole body of the request:
```
>>>test = helpers.scan(es, index='project_project_desktop', _source_include=('valueA', 'valueB', 'valueC', 'RealTime', 'valueD', 'valueE'), query={"query": {"range":{"RealTime":{"gte":"now-1d/d","lt":"30d/d"}}}}, scroll='5m')
```
should be the way to go.

Hope this helps

**Comment by lehuff** [comment]
So I executed this command:

test = helpers.scan(es, index='project_project_desktop', doc_type='nessusPOST', _source_include=('valueA', 'valueB', 'valueC', 'RealTime', 'valueD', 'valueE'), query={"query": {"range":{"RealTime":{"gte":"now/d","lt":"now+30d/d"}}}}, scroll='5m')


No errors this time, but no results are presented. When executing without the query I get a ton of data back.

**Comment by HonzaKral** [comment]
I am sorry, I cannot help you without further information unfortunately. Could you please share the code that you are using and some sampler data?

There is a test case verifying that this functionality works (https://github.com/elastic/elasticsearch-py/blob/master/test_elasticsearch/test_server/test_helpers.py#L231-L239)

thanks!

**Comment by HonzaKral** [comment]
Closing this issue since there is no information, feel free to reopen if you can provide more information for debugging. Thanks!
