### ISSUE TITLE
Search Template Example

### ISSUE THREAD

**Issue by Garito** [elastic/elasticsearch-py#376]
Hi!
Could someone put here and example of how to put and use a search template, please?
I need one with mustache conditional but I can't make it work

Thanks!

**Comment by lababidi** [comment]
I actually think the implementation of *_template() calls are wrong. they make a call to "/_search/template" when it should be "/_template"

**Comment by HonzaKral** [comment]
@lababidi the url is correct, there is no underscore in `template` - see https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html

@Garito you can use the examples from the same page and simply translate them to python:
```
es = Elasticsearch()
es.search_template(body={
    "inline" : {"query": { "match" : { "{{my_field}}" : "{{my_value}}" } } },
    "params" : {"field" : "foo", "my_value" : "bar"  }
})
```

Hope this helps

**Comment by lababidi** [comment]
My apologies, I was mixing this up with _template as in index templates.

**Comment by Garito** [comment]
Ok, thanks, it is sligthly quicker that the regular query, superawesome!

**Comment by Garito** [comment]
Could you point me why this query:
```mustache
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
      {{#path}}
        {"match": {"path": "{{path}}"}}
      {{/path}}
      ],
      "should": [
        {"match": {"_type": "section"}}
      ]
    }
  }
}
```
raises:
````python
TransportError(400, u"ElasticsearchIllegalArgumentException[failed to parse template script]; nested: JsonParseException[Unexpected character ('{' (code 123)): was expecting either valid name character (for unquoted name) or double-quote (for quoted) to start field name\n at [Source: [B@67e8245f; line: 6, column: 9]]; ")
```
when trying to put it in the elasticsearch?

**Comment by Garito** [comment]
My intention is that path is an optional parameter that adds the must match if existed

**Comment by HonzaKral** [comment]
@Garito can you please provide the entire API call that results in this exception?

thanks!

**Comment by Garito** [comment]
I've looking to the source code and, correct me if I'm wrong please, the body in the search_template must to be a python dict that then the transport serializes as a json object
am I right?
If so, the problem with the query above is that {{#path}} is not a correct dict object so it fails trying to serialize it

Is my assumption correct?

**Comment by HonzaKral** [comment]
It doesn't have to be a dict, a string will also work an din this case it might be required.

**Comment by Garito** [comment]
The error is a JsonParseException

**Comment by HonzaKral** [comment]
Try to pass it in as string. But I am afraid without the example code I won't be able to help you

**Comment by Garito** [comment]
The issue is that the transport tryies to serialize with it's default serializer even if I pass a string as body

**Comment by Garito** [comment]
with
es.put_template(template_name, unicode(template))
raises the same error in the same place

**Comment by Garito** [comment]
https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/transport.py#L291

**Comment by HonzaKral** [comment]
That is not an issue - https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/serializer.py#L43-L45

could you please provide a full example of what's going on including a stack trace? Otherwise I really cannot do anything at all to help you

**Comment by Garito** [comment]
The complete traceback:
```python
Traceback (most recent call last):
  File "manage.py", line 132, in <module>
    manager.run()
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_script/__init__.py", line 412, in run
    result = self.handle(sys.argv[0], sys.argv[1:])
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_script/__init__.py", line 383, in handle
    res = handle(*args, **config)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/flask_script/commands.py", line 216, in __call__
    return self.run(*args, **kwargs)
  File "manage.py", line 85, in addESTemplates
    es.put_template(template_name, unicode(template['_source']['description']))
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 1240, in put_template
    'template', id), params=params, body=body)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/garito/TimeFounder/App/0.3/env/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u"ElasticsearchIllegalArgumentException[failed to parse template script]; nested: JsonParseException[Unexpected character ('{' (code 123)): was expecting either valid name character (for unquoted name) or double-quote (for quoted) to start field name\n at [Source: [B@2743ce40; line: 6, column: 9]]; ")
```

The code that raises it is the one above where template is the one at https://github.com/elastic/elasticsearch-py/issues/376#issuecomment-196906315

**Comment by HonzaKral** [comment]
I have no idea what your code actually looks like, the comment you referrenced is not a valid python code so I don't assume you have that in your source. Either way, this works for me:
```
body = {
"template": {
  "query": {                                    
    "bool": {
      "must": [
      "{{#path}}",
        {"match": {"path": "{{path}}"}},
      "{{/path}}"
      ],
      "should": [
        {"match": {"_type": "section"}}
      ]
    }
  }
}
}
es.put_template(id='my_template', body=body)
```
If that doesn't work for you please open a new ticket. Otherwise please open a new ticket with a complete example of your code, your expected result and the error you are getting, thank you!

**Comment by Garito** [comment]
I'm trying to make a conditional while you are using path as an array like in here:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_conditional_clauses

**Comment by Garito** [comment]
Sorry, I mean:
your case with arrays:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_passing_an_array_of_strings
mine with conditionals:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html#_conditional_clauses

**Comment by Garito** [comment]
The point is that the template in this kind of searches is a mustache template not a dict or a json

**Comment by HonzaKral** [comment]
A string as the body works, the example I pasted above works. I am really sorry but I really cannot help you beyond what I already provided if you don't share the code that actually fails and the exception.

**Comment by Garito** [comment]
The complete code:
```python
@manager.command
def addESTemplates():
  """Search for Elasticsearch templates within the papers and update them to Elasticsearch if they aren't there yet"""
  query = {
    "query": {
      "wildcard": {
        "path": "/system/papers/*/elastic/templates"
      }
    }
  }

  templateNodes = es.search(index=app.config.get("DATABASE_NAME"), doc_type="section", body=query)

  for template in templateNodes['hits']['hits']:
    paper = template['_source']['path'].split('/')[3]
    name = template['_source']['slug']
    template_name = "{}_{}".format(paper, name)

    es.put_template(template_name, unicode(template['_source']['description']))

  app.logger.info("{} template{} added to elastic".format(templateNodes['hits']['total'], "" if templateNodes['hits']['total'] == 1 else "s"))
```
The template['_source'['description'] that fails:
```mustache
{
  "size": 0,
  "query": {
    "bool": {
      "must": [
      {{#path}}
        {"match": {"path": "{{path}}"}}
      {{/path}}
      ],
      "should": [
        {"match": {"_type": "section"}},
        {"match": {"_type": "investment"}},
        {"match": {"_type": "exit"}}
      ]
    }
  },
  "aggs": {
    "accepted": {
      "terms": {
        "field": "accepted"
      },
      "aggs": {
        "shares": {
          "sum": {
            "script": "doc[\"_type\"].value == \"investment\" ? doc[\"shares\"].value : -doc[\"points\"].value"
          }
        }
      }
    },
    "pending": {
      "filter": {
        "missing": {
          "field": "accepted"
        }
      },
      "aggs": {
        "types": {
          "terms": {
            "field": "_type"
          },
          "aggs": {
            "shares": {
              "sum": {
                "script": "doc[\"_type\"].value == \"investment\" ? doc[\"shares\"].value : doc[\"points\"].value"
              }
            }
          }
        }
      }
    },
    "types": {
      "terms": {
        "field": "_type"
      },
      "aggs": {
        "accepted": {
          "terms": {
            "field": "accepted"
          },
          "aggs": {
            "shares": {
              "sum": {
                "script": "doc[\"_type\"].value == \"investment\" ? doc[\"shares\"].value : doc[\"points\"].value"
              }
            }
          }
        },
        "pending": {
          "filter": {
            "missing": {
              "field": "accepted"
            }
          },
          "aggs": {
            "shares": {
              "sum": {
                "script": "doc[\"_type\"].value == \"investment\" ? doc[\"shares\"].value : doc[\"points\"].value"
              }
            }
          }
        },
        "finished": {
          "sum": {
            "script": "doc[\"finished\"] == \"T\" ? 1 : 0"
          }
        }
      }
    },
    "users": {
      "terms": {
        "script": "doc[\"_type\"].value == \"exit\" ? _source.reciever : (doc[\"_type\"].value == \"section\" ? _source.leaders[0] : _source.creator)"
      },
      "aggs": {
        "accepted_shares": {
          "sum": {
            "script": "doc[\"accepted\"].value == \"T\" ? (doc[\"_type\"].value == \"investment\" ? doc[\"shares\"].value : -doc[\"points\"].value) : 0"
          }
        },
        "pending_shares": {
          "sum": {
            "script": "doc[\"accepted\"].empty && doc[\"_type\"].value == \"investment\" ? _source.shares : 0"
          }
        },
        "pending_exits": {
          "sum": {
            "script": "doc[\"accepted\"].empty && doc[\"_type\"].value == \"exit\" ? _source.points : 0"
          }
        },
        "types": {
          "terms": {
            "field": "_type"
          },
          "aggs": {
            "finished": {
              "sum": {
                "script": "!doc[\"finished\"].empty ? 1 : 0"
              }
            },
            "accepted": {
              "terms": {
                "field": "accepted"
              },
              "aggs": {
                "shares": {
                  "sum": {
                    "script": "doc[\"_type\"].value == \"exit\" ? doc[\"points\"] : doc[\"shares\"]"
                  }
                }
              }
            },
            "pending": {
              "filter": {
                "missing": {
                  "field": "accepted"
                }
              },
              "aggs": {
                "shares": {
                  "sum": {
                    "script": "doc[\"_type\"].value == \"exit\" ? doc[\"points\"] : doc[\"shares\"]"
                  }
                }
              }
            }
          }
        }
      }
    },
    "units": {
      "terms": {
        "field": "unit.raw"
      },
      "aggs": {
        "accepted_shares": {
          "sum": {
            "script": "doc[\"accepted\"].value == \"T\" ? (doc[\"_type\"].value == \"investment\" ? doc[\"shares\"].value : -doc[\"points\"].value) : 0"
          }
        },
        "accepted_amounts": {
          "sum": {
            "script": "doc[\"accepted\"].value == \"T\" && doc[\"_type\"].value == \"investment\" ? _source.amount : 0"
          }
        },
        "users": {
          "terms": {
            "script": "doc[\"_type\"].value == \"investment\" ? _source.creator : _source.reciever" 
          },
          "aggs": {
            "accepted_shares": {
              "sum": {
                "script": "doc[\"accepted\"].value == \"T\" ? (doc[\"_type\"].value == \"investment\" ? doc[\"shares\"].value : -doc[\"points\"].value) : 0"
              }
            },
            "accepted_amounts": {
              "sum": {
                "script": "doc[\"accepted\"].value == \"T\" && doc[\"_type\"].value == \"investment\" ? _source.amount : 0"
              }
            }
          }
        }
      }
    },
    "activity": {
      "date_histogram": {
        "field": "created",
        "interval": "day"
      }
    }
  }
}
```

**Comment by HonzaKral** [comment]
put the `{{}}` elements in quotes and wrap the whole thing in `{"template": {}}` - follow the example that I sent that works - https://github.com/elastic/elasticsearch-py/issues/376#issuecomment-196942903

Thanks

**Comment by Garito** [comment]
It has nothing to do with the quotes and the example at #376 but with the fact that search_template expect a json
Wraping the whole MUSTACHE template with {"template": {}} solves the issue

Thanks

**Comment by raviada** [comment]
@Garito I created a template wrapping within ```{"template": {}}```, it works fine substituting params, but as soon as I try to add conditions ```{{#somethig}}{{/something}}```, I am getting parsing exception just like as you mentioned in the beginning. 
```
unchecked_i_o_exception: com.fasterxml.jackson.core.JsonParseException: Unexpected character ('{' (code 123)): was expecting double-quote to start field name\n at [Source: org.elasticsearch.common.bytes.BytesReference$MarkSupportingStreamInputWrapper@44a51b9b; line: 2, column: 19]
```

You mentioned that you solved it, but I followed the exact same way, still giving me that exception. Please let me know if it ever worked for you, this is a great way for me to manage queries initiated from webapp and sharing the same queries among other applications.

Thanks

**Comment by Garito** [comment]
Yeah, I've overcomed this by not using templates...
Sorry

**Comment by mwangersjo** [comment]
@raviada did you get somewhere with this? I'm having the same problem, but my string that I pass in looks fine to me..

**Comment by getorca** [comment]
I know it's old but was running into the smae issue, there's a note under the section on conditionals in the documentation, https://www.elastic.co/guide/en/elasticsearch/reference/current/search-template.html:

> As written above, this template is not valid JSON because it includes the section markers like {{#line_no}}. For this reason, the template should either be stored in a file (see Pre-registered template) or, when used via the REST API, should be written as a string:
