### ISSUE TITLE
ping(*args, **kwargs) does not return False when elasticsearch is not started

### ISSUE THREAD

**Issue by ninSmith** [elastic/elasticsearch-py#388]
Elasticsearch is not started and I tried to ping it with:    
```
>>> from elasticsearch import Elasticsearch
>>> es = Elasticsearch()
>>> es.ping()
```
I got the following exception:    
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 208, in ping
    self.transport.perform_request('HEAD', '/', params=params)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", line 329, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_urllib3.py", line 105, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x7fdc585ae090>: Failed to establish a new connection: [Errno 111] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x7fdc585ae090>: Failed to establish a new connection: [Errno 111] Connection refused)
```

However, when I started elasticsearch and pinged it again I got: 
```
>>> es.ping()
True
```

It seems that ping(*args, **kwargs) does not return False when elasticsearch is not started...    
For information:
```
~$ pip show elasticsearch
---
Name: elasticsearch
Version: 2.3.0
Location: /usr/local/lib/python2.7/dist-packages
Requires: urllib3
```

**Comment by rajeshyogeshwar** [comment]
Dont want to do "me too" here. But I tried it and it does happen that when elasticsearch service is down and ping is called it returns ConnectionError instead of simple False.

**Comment by rajeshyogeshwar** [comment]
@ninSmith Have you found any workaround for this?

**Comment by IreneSL** [comment]
ssss

**Comment by dirkschneemann** [comment]
Well, a clunky work around that I found at https://www.reddit.com/r/Python/comments/3a2erd/exception_catch_not_catching_everything/ is as follows:

```
import contextlib
import sys
import os

@contextlib.contextmanager
def nostderr():
    savestderr = sys.stderr
    sys.stderr = os.devnull
    try:
        yield
    finally:
        sys.stderr = savestderr

try:
    with nostderr():
        es.ping()
except (AttributeError, ConnectionRefusedError):
    print('Connection could not be established.')
    # react accordingly, e.g. with retrying or switching to a different host...
```

This suppresses the exceptions that are flying in the background when the connection could not be established so that you can concentrate on how you actually want to handle that case.
