### ISSUE TITLE
Python 3.5.1 - elasticsearch-2.3.0 - RequestError 'failed to parse'

### ISSUE THREAD

**Issue by naisanza** [elastic/elasticsearch-py#394]
I'm having trouble importing a JSON file into Elasticsearch. 

The JSON file is 51 MB, and works when imported into MongoDB

I was following this post https://bitquabit.com/post/having-fun-python-and-elasticsearch-part-1/

Python and Elasticsearch:
```
Python 3.5.1+ (default, Mar 30 2016, 22:46:26)
[GCC 5.3.1 20160330] on linux
Linux portal-python 4.4.0-16-generic #32-Ubuntu SMP Thu Mar 24 22:38:01 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux
```

Elasticsearch server:
```
python@portal-python:~$ curl -XGET http://10.0.2.149:9200?pretty
{
  "name" : "Illyana Rasputin",
  "cluster_name" : "elasticsearch",
  "version" : {
    "number" : "5.0.0-alpha1",
    "build_hash" : "7d4ed5b",
    "build_date" : "2016-04-04T10:39:25.841Z",
    "build_snapshot" : false,
    "lucene_version" : "6.0.0"
  },
  "tagline" : "You Know, for Search"
}
```

Error:
```
POST /l/data_feed [status:400 request:0.486s]
Traceback (most recent call last):
  File "data_json/python-test.py", line 40, in <module>
    main()
  File "data_json/python-test.py", line 36, in main
    es.index(index='kl', doc_type=ES_TYPE, body=data)
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/client/utils.py", line 69, in _wrapped
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/client/__init__.py", line 279, in index
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/transport.py", line 329, in perform_request
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/connection/base.py", line 108, in _raise_error
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse')
```

Python:
```
#!/usr/bin/env python
# -*- coding: utf8 -*-

from datetime import datetime
import elasticsearch
import json
import os

es_server = 'http://10.0.2.149:9200'
es = elasticsearch.Elasticsearch([es_server])

script_path = os.path.realpath(__file__)
working_path = os.path.split(script_path)[0]


def main():
    ES_TYPE = 'data_feed'
    ES_INDEX = 'l'

    for path, subdirs, files in os.walk(working_path):

        for file in files:
            path_file = os.path.join(path, file)

            if os.path.isfile(path_file):

                if os.path.splitext(path_file)[1] == '.json':
                    # ES_INDEX = os.path.splitext(file)[0]

                    with open(path_file, 'r') as f:
                        data = json.load(f)

                    print('Importing:', file, '(', int(os.stat(path_file).st_size / 1024 / 1024), 'MB', ')')
                    es.index(index='l', doc_type=ES_TYPE, body=data)


if __name__ == "__main__":
    main()
```

**Comment by naisanza** [comment]
Also, unable to use `curl -XPOST` either

curl -XPOST 'http://10.0.2.149:9200/l/data_feed' -d data_json/feed.json
```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse",
    "caused_by": {
      "type": "not_x_content_exception",
      "reason": "Compressor detection can only be called on some xcontent bytes or compressed xcontent bytes"
    }
  },
  "status": 400
}
```

**Comment by HonzaKral** [comment]
Could you please share what does `data` look like for the failed request? thanks!

**Comment by naisanza** [comment]
@HonzaKral Sure I'll grab a sample. Give me a minute. If I recall, it looks like the JSON file in one continuous string

**Comment by naisanza** [comment]
@HonzaKral Here's the full output

```
python@portal-python:~/data_json$ python3 python-test.py /tmp/test.json 
[{'yrs': '1016', 'nm': 'Edmund lronside', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '1016-1035', 'nm': 'Cnut', 'hse': 'House of Denmark', 'cty': 'United Kingdom'}, {'yrs': '1035-1040', 'nm': 'Harold I Harefoot', 'hse': 'House of Denmark', 'cty': 'United Kingdom'}, {'yrs': '1040-1042', 'nm': 'Harthacanut', 'hse': 'House of Denmark', 'cty': 'United Kingdom'}, {'yrs': '1042-1066', 'nm': 'Edward the Confessor', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '1066', 'nm': 'Harold II', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '1066-1087', 'nm': 'William I', 'hse': 'House of Normandy', 'cty': 'United Kingdom'}, {'yrs': '1087-1100', 'nm': 'William II', 'hse': 'House of Normandy', 'cty': 'United Kingdom'}, {'yrs': '1100-1135', 'nm': 'Henry I', 'hse': 'House of Normandy', 'cty': 'United Kingdom'}, {'yrs': '1135-1154', 'nm': 'Stephen', 'hse': 'House of Blois', 'cty': 'United Kingdom'}, {'yrs': '1154-1189', 'nm': 'Henry II', 'hse': 'House of Angevin', 'cty': 'United Kingdom'}, {'yrs': '1189-1199', 'nm': 'Richard I', 'hse': 'House of Angevin', 'cty': 'United Kingdom'}, {'yrs': '1199-1216', 'nm': 'John', 'hse': 'House of Angevin', 'cty': 'United Kingdom'}, {'yrs': '1216-1272', 'nm': 'Henry III', 'hse': 'House of Plantagenet', 'cty': 'United Kingdom'}, {'yrs': '1272-1307', 'nm': 'Edward I', 'hse': 'House of Plantagenet', 'cty': 'United Kingdom'}, {'yrs': '1307-1327', 'nm': 'Edward II', 'hse': 'House of Plantagenet', 'cty': 'United Kingdom'}, {'yrs': '1327-1377', 'nm': 'Edward III', 'hse': 'House of Plantagenet', 'cty': 'United Kingdom'}, {'yrs': '1377-1399', 'nm': 'Richard II', 'hse': 'House of Plantagenet', 'cty': 'United Kingdom'}, {'yrs': '1399-1413', 'nm': 'Henry IV', 'hse': 'House of Lancaster', 'cty': 'United Kingdom'}, {'yrs': '1413-1422', 'nm': 'Henry V', 'hse': 'House of Lancaster', 'cty': 'United Kingdom'}, {'yrs': '1422-1461', 'nm': 'Henry VI', 'hse': 'House of Lancaster', 'cty': 'United Kingdom'}, {'yrs': '1461-1483', 'nm': 'Edward IV', 'hse': 'House of York', 'cty': 'United Kingdom'}, {'yrs': '1483', 'nm': 'Edward V', 'hse': 'House of York', 'cty': 'United Kingdom'}, {'yrs': '1483-1485', 'nm': 'Richard III', 'hse': 'House of York', 'cty': 'United Kingdom'}, {'yrs': '1485-1509', 'nm': 'Henry VII', 'hse': 'House of Tudor', 'cty': 'United Kingdom'}, {'yrs': '1509-1547', 'nm': 'Henry VIII', 'hse': 'House of Tudor', 'cty': 'United Kingdom'}, {'yrs': '1547-1553', 'nm': 'Edward VI', 'hse': 'House of Tudor', 'cty': 'United Kingdom'}, {'yrs': '1553-1558', 'nm': 'Mary I', 'hse': 'House of Tudor', 'cty': 'United Kingdom'}, {'yrs': '1558-1603', 'nm': 'Elizabeth I', 'hse': 'House of Tudor', 'cty': 'United Kingdom'}, {'yrs': '1603-1625', 'nm': 'James I', 'hse': 'House of Stuart', 'cty': 'United Kingdom'}, {'yrs': '1625-1649', 'nm': 'Charles I', 'hse': 'House of Stuart', 'cty': 'United Kingdom'}, {'yrs': '1649-1653', 'nm': 'Commonwealth', 'hse': 'Commonwealth', 'cty': 'United Kingdom'}, {'yrs': '1653-1658', 'nm': 'Oliver Cromwell', 'hse': 'Commonwealth', 'cty': 'United Kingdom'}, {'yrs': '1658-1659', 'nm': 'Richard Cromwell', 'hse': 'Commonwealth', 'cty': 'United Kingdom'}, {'yrs': '1660-1685', 'nm': 'Charles II', 'hse': 'House of Stuart', 'cty': 'United Kingdom'}, {'yrs': '1685-1688', 'nm': 'James II', 'hse': 'House of Stuart', 'cty': 'United Kingdom'}, {'yrs': '1689-1694', 'nm': 'William III', 'hse': 'House of Orange', 'cty': 'United Kingdom'}, {'yrs': '1702-1714', 'nm': 'Anne', 'hse': 'House of Stuart', 'cty': 'United Kingdom'}, {'yrs': '1714-1727', 'nm': 'George I', 'hse': 'House of Hanover', 'cty': 'United Kingdom'}, {'yrs': '1727-1760', 'nm': 'George II', 'hse': 'House of Hanover', 'cty': 'United Kingdom'}, {'yrs': '1760-1820', 'nm': 'George III', 'hse': 'House of Hanover', 'cty': 'United Kingdom'}, {'yrs': '1820-1830', 'nm': 'George IV', 'hse': 'House of Hanover', 'cty': 'United Kingdom'}, {'yrs': '1830-1837', 'nm': 'William IV', 'hse': 'House of Hanover', 'cty': 'United Kingdom'}, {'yrs': '1837-1901', 'nm': 'Victoria', 'hse': 'House of Hanover', 'cty': 'United Kingdom'}, {'yrs': '1901-1910', 'nm': 'Edward VII', 'hse': 'House of Saxe-Coburg-Gotha', 'cty': 'United Kingdom'}, {'yrs': '1910-1936', 'nm': 'George V', 'hse': 'House of Windsor', 'cty': 'United Kingdom'}, {'yrs': '1936', 'nm': 'Edward VIII', 'hse': 'House of Windsor', 'cty': 'United Kingdom'}, {'yrs': '1936-1952', 'nm': 'George VI', 'hse': 'House of Windsor', 'cty': 'United Kingdom'}, {'yrs': '1952-', 'nm': 'Elizabeth II', 'hse': 'House of Windsor', 'cty': 'United Kingdom'}, {'yrs': '899-925', 'nm': 'Edward the Elder', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '925-940', 'nm': 'Athelstan', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '940-946', 'nm': 'Edmund', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '946-955', 'nm': 'Edred', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '955-959', 'nm': 'Edwy', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '959-975', 'nm': 'Edgar', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '975-978', 'nm': 'Edward the Martyr', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}, {'yrs': '978-1016', 'nm': 'Ethelred II the Unready', 'hse': 'House of Wessex', 'cty': 'United Kingdom'}]
Importing: /tmp/test.json ( 0 MB )
POST /l/data_feed [status:400 request:0.006s]
Traceback (most recent call last):
  File "python-test.py", line 57, in <module>
    main()
  File "python-test.py", line 33, in main
    es.index(index=ES_INDEX, doc_type=ES_TYPE, body=data)
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/client/utils.py", line 69, in _wrapped
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/client/__init__.py", line 279, in index
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/transport.py", line 329, in perform_request
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
  File "/home/python/virtualenv/elasticsearch/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/connection/base.py", line 108, in _raise_error
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse')
python@portal-python:~/data_json$ 
```

Python:
```
#!/usr/bin/env python
# -*- coding: utf8 -*-

from datetime import datetime
import elasticsearch
import json
import os
import sys

es_server = 'http://10.0.2.149:9200'
es = elasticsearch.Elasticsearch([es_server])

script_path = os.path.realpath(__file__)
working_path = os.path.split(script_path)[0]

ES_TYPE = 'data_feed'
ES_INDEX = 'l'


def main():
    if sys.argv[1]:
        path_file = os.path.join(working_path, sys.argv[1])

        if os.path.isfile(path_file):

            if os.path.splitext(path_file)[1] == '.json':
                with open(path_file, 'r') as f:
                    data = json.load(f)

                print(data)

                print('Importing:', path_file, '(', int(os.stat(path_file).st_size / 1024 / 1024), 'MB', ')')
                es.index(index=ES_INDEX, doc_type=ES_TYPE, body=data)

    else:

        for path, subdirs, files in os.walk(working_path):

            for file in files:
                path_file = os.path.join(path, file)

                if os.path.isfile(path_file):

                    if os.path.splitext(path_file)[1] == '.json':
                        # ES_INDEX = os.path.splitext(file)[0]

                        with open(path_file, 'r') as f:
                            data = json.load(f)

                        print(data)

                        print('Importing:', file, '(', int(os.stat(path_file).st_size / 1024 / 1024), 'MB', ')')
                        es.index(index=ES_INDEX, doc_type=ES_TYPE, body=data)


if __name__ == "__main__":
    main()

```

**Comment by HonzaKral** [comment]
Thanks! The issue is that documents need to be json objects where you are trying to use a list.

If you want to index all documents from that list you need another for loop to iterate over them or use something like the `bulk` helper to index multiple documents at the same time.

http://elasticsearch-py.readthedocs.org/en/master/helpers.html

**Comment by naisanza** [comment]
@HonzaKral What about large JSON files (> 4GB). How would you recommend importing those into elasticsearch?

**Comment by HonzaKral** [comment]
Definitely use the bulk api via the helper.
