### ISSUE TITLE
Cannot clear scroll over multiple indices

### ISSUE THREAD

**Issue by danielmitterdorfer** [elastic/elasticsearch-py#406]
**Elasticsearch version**: 5.0 (master)
**Elasticsearch Python version**: 2.3.0

**Description of the problem including expected versus actual behavior**:

When creating multiple indices (25 in the reproduction scenario) and doing a scroll search over the index, it is not possible to close it properly. 

**Steps to reproduce**:
 1. Start a fresh single-node Elasticsearch cluster
 2. Run the following script (requires Python3):

```python
import elasticsearch

es = elasticsearch.Elasticsearch()


doc = {
    "vendor": "Elastic",
    "package": "Elasticsearch",
    "version": "5.0.0"
}

num_indices = 25
print("Creating [%d] indices" % num_indices)

# create a few indices and add a document
for i in range(1, num_indices):
    index_name = "scroll-test-%d" % i
    es.indices.create(index=index_name, ignore=400)
    es.index(index=index_name, doc_type="packages", body=doc)


print("Performing a scroll search")

r = es.search(index="scroll-test-*", doc_type="packages", sort="_doc", scroll="10s", size=5)
scroll_id = r["_scroll_id"]
print("scroll_id length = [%d] characters" % len(scroll_id))

for page in range(5):
    hit_count = len(r["hits"]["hits"])
    print("Retrieving results for page [%d] ([%d] results)" % (page, hit_count))
    if hit_count == 0:
        # done
        break
    r = es.scroll(scroll_id=scroll_id, scroll="10s")

print("Clearing scroll")
es.clear_scroll(scroll_id=scroll_id)
```

**Provide logs (if relevant)**:

Server logs:

```
[2016-05-19 16:03:38,269][WARN ][http.netty               ] [Mister Fear] Caught exception while handling client http traffic, closing connection [id: 0xc3918b5e, /0:0:0:0:0:0:0:1:52468 => /0:0:0:0:0:0:0:1:9200]
org.jboss.netty.handler.codec.frame.TooLongFrameException: An HTTP line is larger than 4096 bytes.
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.readLine(HttpMessageDecoder.java:670)
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:184)
	at org.jboss.netty.handler.codec.http.HttpMessageDecoder.decode(HttpMessageDecoder.java:102)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:500)
	at org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:83)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Client logs:

```
dm@io: $ python3 scroll.py
Creating [25] indices
Performing a scroll search
scroll_id length = [4508] characters
Retrieving results for page [0] ([0] results)
Clearing scroll
[...]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/site-packages/elasticsearch-2.3.0-py3.5.egg/elasticsearch/connection/http_urllib3.py", line 94, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 609, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/site-packages/urllib3/util/retry.py", line 222, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/site-packages/urllib3/packages/six.py", line 309, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 559, in urlopen
    body=body, headers=headers)
  File "/usr/local/lib/python3.5/site-packages/urllib3/connectionpool.py", line 378, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1174, in getresponse
    response.begin()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 282, in begin
    version, status, reason = self._read_status()
  File "/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 251, in _read_status
    raise RemoteDisconnected("Remote end closed connection without"
urllib3.exceptions.ProtocolError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
DELETE http://localhost:9200/_search/scroll/cXVlcnlUaGVuRmV0Y2g7MTIwOzE1ODE6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNTgyOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTU4Mzo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE1ODQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNTg1OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTU4Njo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE1ODc6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNTg5OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTU5MDo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE1ODg6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNTkxOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYwMzo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2ODA6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNTkyOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTU5Mzo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE1OTQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNTk1OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTU5Njo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE1OTc6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNTk4OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTU5OTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MDA6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjAxOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYwMjo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MDQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjA2OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYwNTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MDc6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjA4OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYwOTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MTA6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjExOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYxMjo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MTM6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjE0OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYxNTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MTY6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjE3OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYxOTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MTg6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjIxOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYyMDo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MjI6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjIzOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYyNDo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MjU6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjI3OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYyNjo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2Mjg6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjI5OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYzMDo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MzE6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjMyOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYzMzo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2MzQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjM1OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYzNjo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2Mzc6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjM4OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTYzOTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NDA6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjQxOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY0Mjo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NDM6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjQ0OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY0NTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NDY6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjQ3OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY0ODo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NDk6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjUwOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY1MTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NTI6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjUzOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY1NTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NTQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjU3OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY1Njo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NTg6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjU5OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY2MDo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NjE6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjYyOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY2Mzo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NjQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjY1OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY2Njo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2Njc6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjY4OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY2OTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NzA6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjcxOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY3Mjo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NzM6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjc0OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY3Njo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2NzU6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjc3OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY3OTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2Nzg6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjkxOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY4MTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2ODI6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjgzOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY4NTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2ODQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjk3OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY4Njo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2ODc6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjg4OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY4OTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2OTA6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjkyOjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY5Mzo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2OTQ6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjk2OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTY5NTo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzE2OTg6OG5jeVhXc0NUeTI2akR5NGhNcmxNZzsxNjk5OjhuY3lYV3NDVHkyNmpEeTRoTXJsTWc7MTcwMDo4bmN5WFdzQ1R5MjZqRHk0aE1ybE1nOzA7 [status:N/A request:0.003s]
```

This indicates that the Python client provides the scroll id in the URL but the [Elasticsearch documentation](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html#_clear_scroll_api) says that the scroll id has to be provided in the body when using the clear scroll API:

```
curl -XDELETE localhost:9200/_search/scroll -d '
{
    "scroll_id" : ["c2Nhbjs2OzM0NDg1ODpzRlBLc0FXNlNyNm5JWUc1"]
}'
```

So the fix seems to be to put the scroll id in the body instead of the URL.

**Comment by HonzaKral** [comment]
Thanks for the report. The workaround is to send it via the body manually for now:
`es.clear_scroll(body={'scroll_id': scroll_id})`

Also note that there is a `scan` helper in the client itself that already contains the logic necessary to consume the entire scroll:  http://elasticsearch-py.readthedocs.io/en/master/helpers.html#scan

And for completeness `elasticsearch-py` 2.x is not guaranteed compatible with elasticsearch 5.x, for that you need to use code from the `master` branch, though it should be fine in most cases.

**Comment by danielmitterdorfer** [comment]
> Also note that there is a scan helper in the client itself that already contains the logic necessary to consume the entire scroll: http://elasticsearch-py.readthedocs.io/en/master/helpers.html#scan

I wasn't aware of the scroll helper. That's maybe worth investigating for our benchmarks though.

> And for completeness elasticsearch-py 2.x is not guaranteed compatible with elasticsearch 5.x, for that you need to use code from the master branch, though it should be fine in most cases.

Yes, I am aware of this.

Thanks for the super-fast fix!
