### ISSUE TITLE
Elasticsearch object has no attribute 'analyze'

### ISSUE THREAD

**Issue by SergeyBondarenko** [elastic/elasticsearch-py#428]
I want to use the analyze method. But I get the following error:
```
Traceback (most recent call last):
  File "analyze.py", line 19, in <module>
    main()
  File "analyze.py", line 13, in main
    result = es.analyze(index = index, analyzer = analyzer, \
AttributeError: 'Elasticsearch' object has no attribute 'analyze'
```

Here is my code:
```
import pdb, json
from elasticsearch import Elasticsearch

def main():
    index = "index1"
    port = 9200
    hosts = ["myhost.com"]
    analyzer = "standard"
    explain = "true"
    text = "rebbit"

    es = Elasticsearch(hosts = [{'hosts': hosts, 'port': port}])
    result = es.analyze(index = index, analyzer = analyzer, \
                    explain = explain, text = text)

    print(json.dumps(result, indent = 2))

if __name__ == "__main__":
    main()
```

**Comment by HonzaKral** [comment]
The analyze api is in the `indices` namespace so you need to use: `es.indices.analyze` instead of `es.analyze`.

Hope this helps.

**Comment by SergeyBondarenko** [comment]
It works, thank you @HonzaKral
