### ISSUE TITLE
Logging from Connection class breaks if exception text contains "%s"

### ISSUE THREAD

**Issue by ymost** [elastic/elasticsearch-py#435]
This happens every once and a while on our production servers, and I don't know the exception that causes it because the logging breaks.
However, here is a snippet that reproduces the problem:
```
from elasticsearch import Connection
conn = Connection()
try:
    raise RuntimeError("Some error %s")
except RuntimeError as e:
    conn.log_request_fail("GET", "http://localhost", None, 3.0, 404, e)
```

Output:
```
Traceback (most recent call last):
  File "c:\code\python27\Lib\logging\__init__.py", line 853, in emit
    msg = self.format(record)
  File "c:\code\python27\Lib\logging\__init__.py", line 726, in format
    return fmt.format(record)
  File "c:\venv\jupyter\lib\site-packages\alertsengine\utils\logger.py", line 52, in format
    result += FILE_LINE_FORMAT.format(record).ljust(25) + ' ' + (MINION_MESSAGE_FORMAT if self.minion_format else MESSAGE_FORMAT).format(record)
  File "c:\code\python27\Lib\logging\__init__.py", line 465, in format
    record.message = record.getMessage()
  File "c:\code\python27\Lib\logging\__init__.py", line 329, in getMessage
    msg = msg % self.args
TypeError: not enough arguments for format string
Logged from file base.py, line 82
```

**Comment by HonzaKral** [comment]
Thanks for the report, I am having some trouble replicating it though:
```
>>> from elasticsearch import Connection
>>> conn = Connection()
>>> try:
...     raise RuntimeError('%s')
... except Exception as e:
...     conn.log_request_fail("GET", "http://localhost", None, 3.0, 404, e)
WARNING:elasticsearch:GET http://localhost [status:404 request:3.000s]
DEBUG:elasticsearch:> None
DEBUG:elasticsearch:< %s
```

Could you please specify which version of `elasticsearch-py` you are using? Thanks!

**Comment by ymost** [comment]
Sorry, I had a mistake,
I had some buggy code that messed with the logging in the background. I tried running the snippet in a fresh environment, but I accidentally ran it with the same buggy code in the background.
My bad.
