### ISSUE TITLE
anyway to customize timeout when bulk, it always fail by timeout

### ISSUE THREAD

**Issue by eromoe** [elastic/elasticsearch-py#446]
```
Traceback (most recent call last):
  File "./mongo_2_es.py", line 86, in <module>
    main()
  File "./mongo_2_es.py", line 80, in main
    article_index.save_bulk(mongo_articile_iter(resultdb, start_date, end_date))
  File "/mnt/apps/elk/code/article_index.py", line 90, in save_bulk
    elasticsearch.helpers.bulk(self.es, actions, chunk_size=10000, max_chunk_bytes=500 * 1024 * 1024)
  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 190, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/usr/local/python27/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 91, in _process_bulk_chunk
    raise e
elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='127.0.0.1', port=9200): Read timed out. (read timeout=10))
```

I ship data from mongo to es, because it is local, so I turn `chunk_size=10000, max_chunk_bytes=500 * 1024 * 1024` to make trasfer faster. It seems too large that hit timeout limit 10. But `elasticsearch.helpers.streaming_bulk` doesn't has a timeout parameter.

**Comment by HonzaKral** [comment]
You can supply a `request_timeout` parameter to `streaming_bulk` which should help.
