### ISSUE TITLE
Traceback when using raise_on_error attribute

### ISSUE THREAD

**Issue by dolohow** [elastic/elasticsearch-py#462]
This code causes library to blow

``` python
a = elasticsearch.helpers.streaming_bulk(self._es, action_iterator, raise_on_error=False)
elasticsearch.helpers.bulk(self._es, a)
```

```
Traceback (most recent call last):
  File "./layer.py", line 10, in <module>
    module.default().run()
  File "/vagrant/app/abstraction/actions.py", line 21, in run
    elasticsearch.helpers.bulk(self._es, a)
  File "/home/ubuntu/.virtualenvs/updatelayer/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 190, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/home/ubuntu/.virtualenvs/updatelayer/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 161, in streaming_bulk
    for bulk_actions in _chunk_actions(actions, chunk_size, max_chunk_bytes, client.transport.serializer):
  File "/home/ubuntu/.virtualenvs/updatelayer/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 55, in _chunk_actions
    for action, data in actions:
  File "/home/ubuntu/.virtualenvs/updatelayer/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 34, in expand_action
    data = data.copy()
AttributeError: 'tuple' object has no attribute 'copy'
```

while

``` python
a = elasticsearch.helpers.streaming_bulk(self._es, action_iterator)
elasticsearch.helpers.bulk(self._es, a)
```

works perfectly fine as well as:

``` python
a = elasticsearch.helpers.streaming_bulk(self._es, action_iterator, raise_on_error=True)
elasticsearch.helpers.bulk(self._es, a)
```

**Comment by HonzaKral** [comment]
What is it that you are trying to achieve here? The code you are using is running a `bulk` operation via `streaming_bulk` and then trying to index the results of the operation by using another `bulk` operation. I assume that is not what you want.

If you just want to index your documents just choose one - either `streaming_bulk` or `bulk`. They act a little differently - `streaming_bulk` returns an iterator that will iterate over the results for individual documents whereas `bulk` will just return the number of documents that succeeded and failed.

Hope this helps,
Honza

**Comment by HonzaKral** [comment]
I am closing this issue since there is no information, please feel free to reopen with additional details.
