### ISSUE TITLE
Elasticsearch 5.0.0 does not work with sniffing

### ISSUE THREAD

**Issue by ShaneHarvey** [elastic/elasticsearch-py#477]
See https://github.com/elastic/elasticsearch/issues/21292.

Elasticsearch 5.0.0 does not return the http_address field on _nodes/_all/clear. Therefore, https://github.com/elastic/elasticsearch-py/blob/5.0.1/elasticsearch/transport.py#L206 needs to use `/_nodes/_all/http` or some other mechanism to determine which nodes have http interfaces.

This bug causes causes all sniffing to fail against a 5.0.0 server:
```python
>>> import elasticsearch
>>> from pprint import pprint
>>> elasticsearch.__version__
(5, 0, 1)
>>> es = elasticsearch.Elasticsearch('localhost:9200')
>>> pprint(es.transport.perform_request('GET', '/_nodes/_all/clear')['nodes'])
{u'EFrXB9v-SC6EgISgHyQK5w': {u'build_hash': u'253032b',
                             u'host': u'127.0.0.1',
                             u'ip': u'127.0.0.1',
                             u'name': u'EFrXB9v',
                             u'roles': [u'master', u'data', u'ingest'],
                             u'transport_address': u'127.0.0.1:9300',
                             u'version': u'5.0.0'}}
>>> pprint(es.transport.perform_request('GET', '/_nodes/_all/http')['nodes'])
{u'EFrXB9v-SC6EgISgHyQK5w': {u'build_hash': u'253032b',
                             u'host': u'127.0.0.1',
                             u'http': {u'bound_address': [u'[fe80::1]:9200',
                                                          u'[::1]:9200',
                                                          u'127.0.0.1:9200'],
                                       u'max_content_length_in_bytes': 104857600,
                                       u'publish_address': u'127.0.0.1:9200'},
                             u'ip': u'127.0.0.1',
                             u'name': u'EFrXB9v',
                             u'roles': [u'master', u'data', u'ingest'],
                             u'transport_address': u'127.0.0.1:9300',
                             u'version': u'5.0.0'}}
>>> es = elasticsearch.Elasticsearch('localhost:9200', sniff_on_start=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/shane/venv/elastic2-doc-manager/python2.7/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 171, in __init__
    self.transport = transport_class(_normalize_hosts(hosts), **kwargs)
  File "/Users/shane/venv/elastic2-doc-manager/python2.7/lib/python2.7/site-packages/elasticsearch/transport.py", line 126, in __init__
    self.sniff_hosts(True)
  File "/Users/shane/venv/elastic2-doc-manager/python2.7/lib/python2.7/site-packages/elasticsearch/transport.py", line 257, in sniff_hosts
    raise TransportError("N/A", "Unable to sniff hosts - no viable hosts found.")
elasticsearch.exceptions.TransportError: TransportError(N/A, 'Unable to sniff hosts - no viable hosts found.')
```

**Comment by daveio** [comment]
Subscribing: experienced this issue, spent far too long trying to work out why it was failing. My own dumb luck that I decided to start playing with ES a couple of days after a new major version!

**Comment by xavierp** [comment]
I'm experiencing this issue too.
Looks like ```helper.bulk()``` is not working too because of this, even with an ES client using ```sniff_on_start = False```.
Thanks @daveio, I hope your patch will be merged soon.

**Comment by daveio** [comment]
@xavierp Could you give me repro steps for the issue you're seeing with `helper.bulk()` please? I'd like to test my patch against it.

**Comment by xavierp** [comment]
@daveio : With a little more digging i found out that i was setting my client with ```sniffer_timeout=10``` and this parameter is used in ```transport.Transport.get_connection()``` as show below:
```python
def get_connection(self):
        """
        Retreive a :class:`~elasticsearch.Connection` instance from the
        :class:`~elasticsearch.ConnectionPool` instance.
        """
        if self.sniffer_timeout:
            if time.time() >= self.last_sniff + self.sniffer_timeout:
                self.sniff_hosts()
        return self.connection_pool.get_connection()
```
Setting ```sniffer_timeout=0```fixed it.
So while waiting for your patch i totally disabled sniffing using:
```python
client = elasticsearch.Elasticsearch(
    host=[...], sniff_on_start=False, sniffer_timeout=0, sniff_on_connection_fail=False)
```

**Comment by daveio** [comment]
@xavierp Ah, great. Elasticsearch is new to me, as is this Python library, so as much as I tried to find any likely breakage when I wrote the code, with CI misbehaving I was eager to check :)

**Comment by travisp** [comment]
@HonzaKral I believe this is still an issue. Sniffing will not work with ES 5
