### ISSUE TITLE
Unexpected not found when using elasticsearch-py but not with curl

### ISSUE THREAD

**Issue by braoru** [elastic/elasticsearch-py#479]
Hello,

I have some trouble using elasticsearch-py.
Our current els version :  "2.3.3"

I have a very simple test code here : https://gist.github.com/braoru/f4facb9bf93cb99dbc67c4ebf12ce07c

When I run it several time, I get unexpected result : Some the index exist, sometime not and sometime it end-up with 404 ..

```Bash
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
False
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
False
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
False
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
True
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
True
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
True
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
True
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
11/04/2016 09:21:31 AM elasticsearch WARNING 26933 log_request_fail() MainThread GET http://mtbclientp02:9200/_nodes/_all/clear [status:N/A request:0.065s]
Traceback (most recent call last):
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/util/retry.py", line 251, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0ecc28c198>: Failed to establish a new connection: [Errno -2] Name or service not known
False
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ python test_els.py 
11/04/2016 09:21:33 AM elasticsearch WARNING 26941 log_request_fail() MainThread GET http://mtbclientp02:9200/_nodes/_all/clear [status:N/A request:0.016s]
Traceback (most recent call last):
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connection.py", line 138, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/util/connection.py", line 75, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib64/python3.5/socket.py", line 732, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 109, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/util/retry.py", line 251, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connectionpool.py", line 594, in urlopen
    chunked=chunked)
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connectionpool.py", line 361, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib64/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/usr/lib64/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/usr/lib64/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connection.py", line 163, in connect
    conn = self._new_conn()
  File "/home/sebastien/Documents/dev/elasticsearch-tools/lib64/python3.5/site-packages/urllib3/connection.py", line 147, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f0250f01160>: Failed to establish a new connection: [Errno -2] Name or service not known
False
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ 
```

When I test with curl, it's constantly working no matter how many request I do.

```Bash
(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ curl -I  http://mtblbclientp01:9200/prod-audit-logstash-b-2016.09.16/
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 0

(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ curl -I  http://mtblbclientp02:9200/prod-audit-logstash-b-2016.09.16/
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 0

(elasticsearch-tools) [sebastien@ecudspa elasticsearch-tools]$ curl -I  http://mtalbclientp01:9200/prod-audit-logstash-b-2016.09.16/
HTTP/1.1 200 OK
Content-Type: text/plain; charset=UTF-8
Content-Length: 0
```

Any idea if its me doing something wrong ?

**Comment by braoru** [comment]
My fault .. I used sniff in front of a Tribe node and then it was a bad idea. Disabling scan make it work better :-)

**Comment by GlenRSmith** [comment]
Thanks, @braoru. Closing.
