### ISSUE TITLE
Elasticsearch.delete_by_query(...) method results in TransportError: No handler found for uri [...] and method [DELETE]

### ISSUE THREAD

**Issue by dirkschneemann** [elastic/elasticsearch-py#494]
[The delete_by_query API](https://www.elastic.co/guide/en/elasticsearch/reference/current/docs-delete-by-query.html) is back in Elasticsearch 5.0 and hence [is also included in elasticsearch-py 5.0.x](https://elasticsearch-py.readthedocs.io/en/master/api.html#elasticsearch.Elasticsearch.delete_by_query).

However, when I try to use it in its simplest forms

```
from elasticsearch import Elasticsearch
es = Elasticsearch(['http://localhost:9200'])

es.delete_by_query(index='my_index', q='*')
# or
es.delete_by_query(index='my_index', body={"query": { "match_all": {} }})
```

then I get the following exception:

```
DELETE /my_index/_query [status:400 request:0.001s]
Traceback (most recent call last):
  File "/test.py", line 321, in <module>
    es.delete_by_query(index='my_index', body={"query": { "match_all": {} }})
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/utils.py", line 69, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/client/__init__.py", line 841, in delete_by_query
    params=params, body=body)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/transport.py", line 307, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 93, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/base.py", line 105, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'No handler found for uri [/my_index/_query] and method [DELETE]')
```

I assume that this is the case because the Elasticsearch API actually uses "POST" instead of "DELETE" (see documentation linked above) but I am not familiar with the elasticsearch-py internals.

**Comment by GlenRSmith** [comment]
@dirkschneemann 
I can't reproduce this. What version of the client are you using? Can you reproduce using 5.0.1?

**Comment by dirkschneemann** [comment]
Yeah, I must have used an older version of the library by accident. With 5.0.1 this works as expected, sorry for any inconvenience caused.

**Comment by hoaphanFox** [comment]
At runtime how do you know which version is it?
