### ISSUE TITLE
Can't establish SSL conection with custom CA certificate

### ISSUE THREAD

**Issue by ericofusco** [elastic/elasticsearch-py#535]
I'm trying to establish a connection with a custom CA certificate, but it doesn't work. It only works when `verify_certs = False` is passed. Apparently is a problem with SSL library but I'm not sure.

I tested with Python 2.7 and 3.4. Both with same issue.

```
from elasticsearch import Elasticsearch

host = 'https://user:pass@me.local:9200'
ca_cert = '/usr/local/share/ca-certificates/CA.crt';

es = Elasticsearch([host], ca_certs = ca_cert)
es.indices.delete(index='test')
```

It gives me the following error:

```
DELETE https://me.local:9200/test [status:N/A request:0.051s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.4/dist-packages/elasticsearch/connection/http_urllib3.py", line 113, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.4/dist-packages/urllib3/connection.py", line 333, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.4/ssl.py", line 671, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
SystemError: error return without exception set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./test.py", line 7, in <module>
    es.indices.delete(index='iris_test')
  File "/usr/local/lib/python3.4/dist-packages/elasticsearch/client/utils.py", line 71, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/elasticsearch/client/indices.py", line 200, in delete
    params=params)
  File "/usr/local/lib/python3.4/dist-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/local/lib/python3.4/dist-packages/elasticsearch/connection/http_urllib3.py", line 122, in perform_request
    raise ConnectionError('N/A', str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(error return without exception set) caused by: SystemError(error return without exception set)
```

**Comment by akhilputhiry** [comment]
@ericofusco I don't think that's an issue with elastic search. As per the stack trace your certificate verification is failing. Are you using a self signed certificate? If yes, this behaviour is expected.

**Comment by ericofusco** [comment]
@akhilputhiry,

You're right. It doesn't seem to be ES related. 

I am using a self-signed certificate. That's why I'm passing the CA certificate as parameter. But for some reason urllib3 throws an error while reading the certificate. I'm sure the file format is correct since I use on kibana config file to connect to elasticsearch.

**Comment by georgepsarakis** [comment]
Did you try the guidelines from the documentation for [SSL and Authentication](https://github.com/elastic/elasticsearch-py/blob/master/docs/index.rst#ssl-and-authentication) ?

**Comment by alesnav** [comment]
Hello @ericofusco , I have the same problem.

It is related to certifi Python module... for some rare reason, it doesn't like my CA root certificate. I tried to follow one good guide (https://incognitjoe.github.io/adding-certs-to-requests.html) to add my CA to the certifi CA bundle, but it throws the same error message than loading CA file via `ca_certs` param...

```Checking connection...
Traceback (most recent call last):
  File "add_ca_certifi.py", line 5, in <module>
    test = requests.get('https://es01.demo:9200')
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 72, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 513, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 623, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib64/python2.7/ssl.py", line 681, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
```

So, I am sure that it is a problem or bug related directly to certifi.

If I find a solution, I will post it here. Hope someone could help us :)

Thanks!

**Comment by GlenRSmith** [comment]
As this seems unrelated to the client code, I think it can be closed.

**Comment by alesnav** [comment]
@ericofusco can you confirm your OpenSSL version? If it it not 1.0.2+ I think that this issue should be closed based on the reasons described above.

Thanks!

**Comment by fxdgear** [comment]
@ericofusco a branch which allows for the use of SSLContext was just merged into master. Would you mind giving that a try to see if the verification of self-signed certs behaves better? If so would you please close this issue?

**Comment by fxdgear** [comment]
Closing this issue as I believe that using SSLContext now will solve this issue. If you continue to have problems please open a new ticket.
