### ISSUE TITLE
an error about epoll when I use the bulk 

### ISSUE THREAD

**Issue by levylll** [elastic/elasticsearch-py#540]
When I use bulk especially in the second batch, it turns out the error.
I don't know what have happened with my es....
There is the error info:
```
AttributeError: 'module' object has no attribute 'epoll'
WARNING:elasticsearch:Connection <Urllib3HttpConnection: http://bbb.xxxxx.link:9200> has failed for 1 times in a row, putting on 60 second timeout.
WARNING:elasticsearch:POST http://c2-db-6.ricebook.link:9200/_bulk [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 241, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/usr/lib/python2.7/site-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/usr/lib/python2.7/site-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/usr/lib/python2.7/site-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/usr/lib/python2.7/site-packages/urllib3/util/selectors.py", line 364, in __init__
    self._epoll = select.epoll()
AttributeError: 'module' object has no attribute 'epoll'
WARNING:elasticsearch:Connection <Urllib3HttpConnection: http:///bbb.xxxxx.link:9200> has failed for 1 times in a row, putting on 60 second timeout.
```

**Comment by georgepsarakis** [comment]
Seems like a known issue with [urllib3](https://github.com/shazow/urllib3/issues/1104).

**Comment by levylll** [comment]
@georgepsarakis 
Yeah, It seems like that.
When I change my connection_class as RequestsHttpConnection, everything is OK.
So I want to know what's wrong with my system.

**Comment by HonzaKral** [comment]
From the issue it looks like you monkey patched some of the system libraries via `gevent` or other similar library and now its behavior is changed.

I am closing this issue since the problem lies outside of `urllib3`.
