### ISSUE TITLE
elasticsearch.exceptions.ConnectionError: ConnectionError([('SSL routines', 'ssl3_write_pending', 'bad write retry')])

### ISSUE THREAD

**Issue by bakztfuture** [elastic/elasticsearch-py#545]
Hi,

I'm getting the following error when using the bulk streaming api:
```
Traceback (most recent call last):
  File "post.py", line 112, in <module>
    helpers.bulk(es, send_data)
  File "/home/****/Desktop/******/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 194, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/home/********/Desktop/*******/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 162, in streaming_bulk
    for result in _process_bulk_chunk(client, bulk_actions, raise_on_exception, raise_on_error, **kwargs):
  File "/home/********/Desktop/**********/venv/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 91, in _process_bulk_chunk
    raise e
elasticsearch.exceptions.ConnectionError: ConnectionError([('SSL routines', 'ssl3_write_pending', 'bad write retry')]) caused by: Error([('SSL routines', 'ssl3_write_pending', 'bad write retry')])
```

I have installed the pyopenssl library and am running `Python 2.7` on `lubuntu 16.04 xenial`.  Here's are all the libraries I have installed in this virutal environment:
```
algoliasearch==1.11.0
amqp==2.1.4
appdirs==1.4.2
beautifulsoup4==4.5.1
begins==0.9
billiard==3.5.0.2
boto==2.45.0
boto3==1.4.3
botocore==1.4.91
celery==4.0.2
cffi==1.9.1
cryptography==1.7.2
Cython==0.25.2
docutils==0.13.1
easycython==1.0.4
elasticsearch==5.2.0
enum34==1.1.6
envoy==0.0.3
funcsigs==1.0.2
futures==3.0.5
gg=gzipstream
idna==2.4
ipaddress==1.0.18
jmespath==0.9.0
kombu==4.0.2
numpy==1.12.0
packaging==16.8
pexpect==4.2.1
Pillow==3.4.2
ptyprocess==0.5.1
pyasn1==0.2.3
pycparser==2.17
pymongo==3.4.0
Pympler==0.4.3
pyOpenSSL==16.2.0
pyparsing==2.1.10
python-dateutil==2.6.0
pytz==2016.10
redis==2.10.5
requests==2.12.5
requests-aws4auth==0.9
s3transfer==0.1.10
selenium==3.0.2
six==1.10.0
urllib3==1.20
vine==1.1.3
```

This is a connection to an AWS elasticsearch service instance, here's how I'm connecting (as per the docs):
```
host = '*****************'
awsauth = AWS4Auth("***", "**********************", 'us-east-1', 'es')
es = Elasticsearch(
	hosts=[{'host': host, 'port': 443}],
	http_auth=awsauth,
	use_ssl=True,
	verify_certs=True,
	timeout=60,
	connection_class=RequestsHttpConnection
)
```

Also following the docs, here's how I'm calling the bulk API:
`helpers.bulk(es, send_data)`

I have not had this error when using the single document insert/index API and have been able to connect just fine.  So far, I've tried updating my pyopenssl library and turning off a proxy I had running on my machine for another script.  I also tried switching into the bulk_streaming API but kept running into timeout issues.  I also tried switching to a larger elasticsearch instance because I thought the error might have to do with the [10 mb/http network limit](http://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/aes-limits.html#network-limits). 

I am transferring ~ 55 mb of documents.  Any idea where this error is happening?  Thank you in advance!

**Comment by bakztfuture** [comment]
Turns out this error was being caused by my own ISP upload rate limits ... lesson learned!!!  Sorry for the post guys, closing now.
