### ISSUE TITLE
method get error

### ISSUE THREAD

**Issue by mokrea** [elastic/elasticsearch-py#651]
when I use
es.get(index="my-index", doc_type="test-type", id="ADKEDKRX') and there is no ADKEDKRX document I got a error. When there is a ID the get method returns the document and the code runs normally.

the error:

`Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
    current.result = callback(current.result, *args, **kw)
  File "/opt/crawlers/coletores/pipelines.py", line 101, in process_item
    res = es.get(index='scrapy', doc_type='item', id="Americanas2")
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 409, in get
    doc_type, id), params=params)
  File "/usr/lib/python2.7/site-packages/elasticsearch/transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File "/usr/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
NotFoundError: TransportError(404, u'{"_index":"scrapy","_type":"item","_id":"Americanas2","found":false}')`

**Comment by HonzaKral** [comment]
Yes, if you try to `get` a document that doesn't exist, you get a `NotFoundError`. If you do not wish to have an exception raised you can use the `ignore` (0) parameter to ignore all `404` errors:

`es.get(index="my-index", doc_type="test-type", id="ADKEDKRX', ignore=404) `

0 - http://elasticsearch-py.readthedocs.io/en/master/api.html#ignore

**Comment by mokrea** [comment]
thanks @HonzaKral.
Could I use try and except?
`try:
   es.get(index="my-index", doc_type="test-type", id="ADKEDKRX')
 except error: 
`
this error is handled by python?

**Comment by HonzaKral** [comment]
Yes, it is a regular python exception so `try`/`except` will work:

```python
try:
    es.get(index="my-index", doc_type="test-type", id="ADKEDKRX')
except NotFoundError:
    # handle exception here
```

**Comment by ShwethaThakur** [comment]
doc_type, '_mtermvectors'), params=params, body=body)
File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/transport.py", line 318, in perform_request
status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 185, in perform_request
self._raise_error(response.status, raw_data)
File "/home/thoshith/.local/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, u'too_long_frame_exception', u'An HTTP line is larger than 4096 bytes.')

Hey there! i am trying to use multitemvectors in elasticsearch to get most frequent unigrams, bigrams and trigrams across an entire index. The number of documents is approx. 50000. When i give 300 IDs, it works fine. But When i give all IDs of 50000 documents, it raises this error. Doesn't multitermvectors work with large no. of documents? or is there a way to figure out this error?
