### ISSUE TITLE
Persisting raw JSON data in field doesn't work

### ISSUE THREAD

**Issue by Djoels** [elastic/elasticsearch-py#663]
I'm trying to add a field with dynamically created (and according to JSON lint website correctly formatted) dictionary / JSON content to a class and persist this to elasticsearch. With dynamic I mean that it's some kind of (nested) tree of dictionaries with text items for keywords and numbers for leaf elements. This data doesn't need any indexing for search, but is purely for persistence...

Is this possible? It appears not when I use the "Nested" type for the variable:

```
class Tree(DocType):
    id = String()
    root = Nested(dynamic=True, enabled=False)
    delimiter = String()
    created = Date()

    @classmethod
    def from_obj(cls, obj):
        return cls(
            id=obj.id,
            root=obj.root,
            delimiter=obj.delimiter,
            created=datetime.now()
        )
```
The error I receive when persisting the full JSON (about 2MB) is a parsing error (see below). When I take smaller fragments of the JSON, it appeared to have troubles with a limit in the depth of the hierarchical json, which I then set to a larger value.

Any ideas for debugging this?
```
Traceback (most recent call last):
  File "Tree.py", line 449, in <module>
    t.write_to_ES()
  File "Tree.py", line 388, in write_to_ES
    doc.save()
  File "***\Continuum\Anaconda3\lib\site-packages\elasticsearch_dsl\document.py", line 410, in save
    **doc_meta
  File "***\Continuum\Anaconda3\lib\site-packages\elasticsearch\client\utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "***\Continuum\Anaconda3\lib\site-packages\elasticsearch\client\__init__.py", line 298, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "***\Continuum\Anaconda3\lib\site-packages\elasticsearch\transport.py", line 312, in perform_request
    status, headers, data = connection.perform_request(method, url, params, body, ignore=ignore, timeout=timeout)
  File "***\Continuum\Anaconda3\lib\site-packages\elasticsearch\connection\http_urllib3.py", line 128, in perform_request
    self._raise_error(response.status, raw_data)
  File ***\Continuum\Anaconda3\lib\site-packages\elasticsearch\connection\base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: TransportError(400, 'mapper_parsing_exception', 'failed to parse')
```

**Comment by Djoels** [comment]
Update: As suggested on stackoverflow: 
https://stackoverflow.com/questions/41923760/how-to-store-large-json-strings-in-elasticsearch
I used the Text(index= "no") type for this variable and it seems to do the trick.

PS: Shall I close this myself or leave this open for additional comments or tips? 
I don't know if there are best practices regarding what I'm doing here.
