### ISSUE TITLE
Parallel docs creation fails sometimes - OSError: [Errno 17] File exists: '/tmp/1/elasticsearch-py-6.0.0/docs/_build/doctrees'

### ISSUE THREAD

**Issue by hydrapolic** [elastic/elasticsearch-py#698]
````
# make -C docs -j8 man html
make: Entering directory '/tmp/1/elasticsearch-py-6.0.0/docs'
sphinx-build -b man -d _build/doctrees   . _build/man
sphinx-build -b html -d _build/doctrees   . _build/html
Running Sphinx v1.6.3
Running Sphinx v1.6.3
making output directory...
making output directory...

Exception occurred:
loading pickled environment... not yet created
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/1/elasticsearch-py-6.0.0/docs/_build/doctrees'
The full traceback has been saved in /tmp/sphinx-err-U8ZNHu.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
building [mo]: targets for 0 po files that are out of date
make: *** [Makefile:131: man] Error 1
make: *** Waiting for unfinished jobs....
building [html]: targets for 7 source files that are out of date
updating environment: 7 added, 0 changed, 0 removed
reading sources... [ 14%] Changelog
reading sources... [ 28%] api
reading sources... [ 42%] connection
reading sources... [ 57%] exceptions
reading sources... [ 71%] helpers
reading sources... [ 85%] index
reading sources... [100%] transports

/tmp/1/elasticsearch-py-6.0.0/docs/connection.rst:53: WARNING: Unknown interpreted text role "function".
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [ 14%] Changelog
writing output... [ 28%] api
writing output... [ 42%] connection
writing output... [ 57%] exceptions
writing output... [ 71%] helpers
writing output... [ 85%] index
writing output... [100%] transports

generating indices... genindex py-modindex
writing additional pages... search
copying static files... WARNING: html_static_path entry u'/tmp/1/elasticsearch-py-6.0.0/docs/_static' does not exist
done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 2 warnings.

Build finished. The HTML pages are in _build/html.
make: Leaving directory '/tmp/1/elasticsearch-py-6.0.0/docs'
````

````
# cat sphinx-err-U8ZNHu.log 
# Sphinx version: 1.6.3
# Python version: 2.7.14 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 226, in __init__
    self.builder = self.create_builder(buildername)
  File "/usr/lib64/python2.7/site-packages/sphinx/application.py", line 306, in create_builder
    return self.registry.create_builder(self, name)
  File "/usr/lib64/python2.7/site-packages/sphinx/registry.py", line 82, in create_builder
    return self.builders[name](app)
  File "/usr/lib64/python2.7/site-packages/sphinx/builders/__init__.py", line 83, in __init__
    os.makedirs(self.doctreedir)
  File "/usr/lib64/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/1/elasticsearch-py-6.0.0/docs/_build/doctrees'
````

**Comment by HonzaKral** [comment]
I am sorry, building docs in parallel is not something that we support. What I would recommend is to have two copies of the repository or at least the `docs` folder for separation.

**Comment by hydrapolic** [comment]
Ok, thanks for the info @HonzaKral. We currently have a workaround on Gentoo Linux to build in a single thread.

**Comment by HonzaKral** [comment]
I love Gentoo Linux, thank you for the work on it!

If you want to use different directories (which is imho the best way) then you should also be able to pas sin the `builddir` to `sphinx-build` - as long as you pass different value for each, you should be fine. Looks like you can pass it via cmdline args (0)

0 - http://www.sphinx-doc.org/en/stable/tutorial.html#running-the-build

**Comment by hydrapolic** [comment]
Thanks for the hints :)
