### ISSUE TITLE
Error running on python 3.6

### ISSUE THREAD

**Issue by diegopereiraeng** [elastic/elasticsearch-py#702]
I'm running perfectly in python 2.6

But running on 3.6 I got this error:

:/home/diegpae> python3.6 criaPicos.py
Traceback (most recent call last):
  File "criaPicos.py", line 2, in <module>
    from elasticsearch import Elasticsearch
  File "/usr/local/lib/python3.6/site-packages/elasticsearch-6.0.0-py3.6.egg/elasticsearch/__init__.py", line 17, in <module>
  File "/usr/local/lib/python3.6/site-packages/elasticsearch-6.0.0-py3.6.egg/elasticsearch/client/__init__.py", line 4, in <module>
  File "/usr/local/lib/python3.6/site-packages/elasticsearch-6.0.0-py3.6.egg/elasticsearch/transport.py", line 4, in <module>
  File "/usr/local/lib/python3.6/site-packages/elasticsearch-6.0.0-py3.6.egg/elasticsearch/connection/__init__.py", line 3, in <module>
  File "/usr/local/lib/python3.6/site-packages/elasticsearch-6.0.0-py3.6.egg/elasticsearch/connection/http_urllib3.py", line 2, in <module>
  File "/usr/local/lib/python3.6/ssl.py", line 101, in <module>
    import _ssl             # if we can't import it, let the error propagate
ModuleNotFoundError: No module named '_ssl'

Running on 2.6:

/home/diegpae> python criaPicos.py
{u'_type': u'picos', u'_seq_no': 65, u'_shards': {u'successful': 2, u'failed': 0, u'total': 3}, u'_index': u'pico-index', u'_version': 6, u'_primary_term': 1, u'result': u'updated', u'_id': u'24'}
updated
{u'@timestamp': u'2018/01/01 02:00:00', u'pico': u'01/01/18', u'valor': 10}
Got 24 Hits:
2018/01/01 03:00:00 01/01/18: 10
2018/01/01 05:00:00 01/01/18: 10
2018/01/01 06:00:00 01/01/18: 10
2018/01/01 07:00:00 01/01/18: 10
2018/01/01 08:00:00 01/01/18: 10
2018/01/01 12:00:00 01/01/18: 10
2018/01/01 14:00:00 01/01/18: 10
2018/01/01 19:00:00 01/01/18: 10
2018/01/01 21:00:00 01/01/18: 10
2018/01/01 22:00:00 01/01/18: 10
2018/01/02 01:00:00 01/01/18: 10
2018/01/01 09:00:00 01/01/18: 10
2018/01/01 13:00:00 01/01/18: 10
2018/01/01 15:00:00 01/01/18: 10
2018/01/01 16:00:00 01/01/18: 10
2018/01/01 17:00:00 01/01/18: 10
2018/01/01 18:00:00 01/01/18: 10
2018/01/01 02:00:00 01/01/18: 10
2018/01/01 04:00:00 01/01/18: 10
2018/01/01 10:00:00 01/01/18: 10
2018/01/01 11:00:00 01/01/18: 10
2018/01/01 20:00:00 01/01/18: 10
2018/01/01 23:00:00 01/01/18: 10
2018/01/02 00:00:00 01/01/18: 10

**Comment by fxdgear** [comment]
It looks like maybe you don't have the SSL libs installed on the machine running python 3.6. 

If instead of using your script. Try opening a Python3.6 shell. Then try to `import ssl`. 

If you get the same error then you will need to either rebuild/reinstall Python 3.6 with SSL. 

please see this stackoverflow: https://stackoverflow.com/questions/5128845/importerror-no-module-named-ssl

> Depending on your distro, please make sure either `openssl-devel` or `libssl-dev` are installed.

**Comment by fxdgear** [comment]
@diegopereiraeng I'm going to close this issue now due to lack of feedback. 

IF you are still experiencing issues, please feel free to re-open the issue with any additional  information.
