### ISSUE TITLE
Add multiple doc_types in an index with custom analyzer

### ISSUE THREAD

**Issue by deepankermishra** [elastic/elasticsearch-py#719]
I have defined an index with two doc_types, posts and people. Both these types have a title and a name field respectively. I have defined a custom analyzer for these fields.

`ngram_analyzer = analyzer('ngram_analyzer',
                          tokenizer=tokenizer('standard', 'nGram', min_gram=2, max_gram=20),
                          filter=['lowercase']
                          )
`
When I try to insert docs of type people after adding docs of type posts (or vice versa), I get the following error:

>Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/Users/deepankermishra/Documents/startup/src/version-one/eduminati/account/management/commands/index_profile_data.py", line 19, in handle
    index_profile(profile)
  File "/Users/deepankermishra/Documents/startup/src/version-one/eduminati/account/es_docs.py", line 28, in index_profile
    ESProfile.init()
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 150, in init
    cls._doc_type.init(index, using)
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/elasticsearch_dsl/document.py", line 97, in init
    self.mapping.save(index or self.index, using=using or self.using)
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/elasticsearch_dsl/mapping.py", line 79, in save
    return index.save()
  File "/Users/deepankermishra/Documents/startup/lib/python3.6/site-packages/elasticsearch_dsl/index.py", line 239, in save
    'You cannot update analysis configuration on an open index, you need to close index %s first.' % self._name)
elasticsearch_dsl.exceptions.IllegalOperation: You cannot update analysis configuration on an open index, you need to close index MyIndex first.
>
Why is it trying to update my analysis configuration?

**Comment by HonzaKral** [comment]
You are calling `ESProfile.init()` which should only be done once to create the index - it uploads the settings into the cluster. Looks like you are using an old version of `elasticsearch-dsl` that doesn't have a good detection of whether a settings update is needed so it always tries to update.

The solution is to not call `ESProfile.init()` every time and also upgrade to the latest version of `elasticsearch-dsl`.

I am closing this issue, if problem persists please reopen the issue on the proper repository instead - this is related to `elasticsearch-dsl` and not `elasticsearch-py`. Thank you!
