### ISSUE TITLE
Error trace-back: elasticsearch configuration error trace-back always printed back!

### ISSUE THREAD

**Issue by AMR-KELEG** [elastic/elasticsearch-py#740]
I am trying to catch elasticsearch exceptions but i am facing problems.
Here is a short snippet that doesn't respond in the way that i expect.
```
from elasticsearch import Elasticsearch

try:
	es = Elasticsearch(['localhost'],
	                    scheme="https",
	                    port=9200000,
	                    sniff_on_start=True)
except:
	print("Print only me!!")
```
I expect that only the `Print only me!` message is printed however this isn't the case.
Here is the output i get:
```
GET https://localhost:9200000/_nodes/_all/http [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 147, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f40e3d69240>: Failed to establish a new connection: [Errno 111] Connection refused
GET https://localhost:9200000/_nodes/_all/http [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 147, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connectionpool.py", line 357, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/home/amr/.conda/envs/scikit/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connection.py", line 166, in connect
    conn = self._new_conn()
  File "/home/amr/.conda/envs/scikit/lib/python3.5/site-packages/urllib3/connection.py", line 150, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f40e3d69390>: Failed to establish a new connection: [Errno 111] Connection refused
Print only me!!
```
Am i misunderstanding something?

**Comment by fxdgear** [comment]
This is working as intended. What you're seeing is a result of the logger. 

if you were to run:

```
In [9]: try:
   ...:     es = Elasticsearch(port=99999, sniff_on_start=True)
   ...: except Exception as e:
   ...:     xx = e

In [10]: print(xx)
TransportError(N/A, 'Unable to sniff hosts.')
```

You would see that your exception was caught.

**Comment by fxdgear** [comment]
for example you can disable logging. But remember that you will have to enable logging later if you want to see the log messages again. 

```
 logger = logging.getLogger('elasticsearch')
 logger.disabled=True
```

**Comment by AMR-KELEG** [comment]
@fxdgear Thanks :smile:
