### ISSUE TITLE
mapper of different type

### ISSUE THREAD

**Issue by serg666** [elastic/elasticsearch-py#742]
Hi!

I use elastic for storing [tornado](http://www.tornadoweb.org/en/stable/) logs. So, in my app I use [CMRESHandler](https://pypi.python.org/pypi/CMRESHandler/1.0.0) handler. This handler use https://pypi.python.org/pypi/elasticsearch/6.1.1

So, when logs go to elastic I see something like this:

```
2018-03-12 13:09:11,120 INFO    tornado.access: [abf2949a-ddf0-4e3a-b99b-acbf499abbd1] 200 POST /cards (127.0.0.1) 132.16ms
2018-03-12 13:09:12,131 DEBUG   urllib3.connectionpool: [None] Starting new HTTP connection (1): localhost
2018-03-12 13:09:12,140 DEBUG   urllib3.connectionpool: [None] http://localhost:9200 "POST /_bulk HTTP/1.1" 200 277
2018-03-12 13:09:12,141 INFO    elasticsearch: [None] POST http://localhost:9200/_bulk [status:200 request:0.019s]
2018-03-12 13:09:12,141 DEBUG   elasticsearch: [None] > {"index":{"_index":"cardstorage_app-2018.03.12","_type":"python_log"}}
{"App":"Test","Environment":"Dev","host":"linux-2jg5","host_ip":"127.0.0.1","name":"tornado.access","msg":"%d %s %.2fms","args":[200,"POST /cards (127.0.0.1)",132.16304779052734],"levelname":"INFO","pathname":"/home/mamonov/env-cardstorage/lib64/python3.6/site-packages/tornado/web.py","filename":"web.py","module":"web","exc_info":"","exc_text":"","stack_info":"","lineno":2064,"funcName":"log_request","thread":139772935673152,"threadName":"MainThread","processName":"MainProcess","process":14840,"request_id":"abf2949a-ddf0-4e3a-b99b-acbf499abbd1","message":"200 POST /cards (127.0.0.1) 132.16ms","asctime":"2018-03-12 13:09:11","timestamp":"2018-03-12T10:09:11.120Z"}
2018-03-12 13:09:12,142 DEBUG   elasticsearch: [None] < {"took":5,"errors":true,"items":[{"index":{"_index":"cardstorage_app-2018.03.12","_type":"python_log","_id":"FzevGWIBu_PvIONXdSzG","status":400,"error":{"type":"illegal_argument_exception","reason":"mapper [args] of different type, current_type [text], merged_type [long]"}}}]}
```
It can be reproduced like this:
```
>>> from elasticsearch import Elasticsearch
>>> from elasticsearch import helpers as eshelpers
>>> 
>>> 
>>> es = Elasticsearch(hosts=[{'host':'localhost', 'port':9200}])
>>> eshelpers.bulk(client=es,actions=({'_index':'some_new_index1','_type':'some_type','_source':{"args":[20000,"ddfsdssds",454.6666, "ddfd"]}},),stats_only=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/mamonov/env-cardstorage/lib64/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/home/mamonov/env-cardstorage/lib64/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
    raise_on_error, **kwargs)
  File "/home/mamonov/env-cardstorage/lib64/python3.6/site-packages/elasticsearch/helpers/__init__.py", line 137, in _process_bulk_chunk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)
elasticsearch.helpers.BulkIndexError: ('1 document(s) failed to index.', [{'index': {'_index': 'some_new_index1', '_type': 'some_type', '_id': 'MzfvGWIBu_PvIONXayz8', 'status': 400, 'error': {'type': 'illegal_argument_exception', 'reason': 'mapper [args] of different type, current_type [long], merged_type [text]'}, 'data': {'args': [20000, 'ddfsdssds', 454.6666, 'ddfd']}}}])
>>>
```

But if I insert data with strings only, then I can insert mixed data:

```
>>> eshelpers.bulk(client=es,actions=({'_index':'some_new_index1','_type':'some_type','_source':{"args":["ddfd"]}},),stats_only=True)
(1, 0)
>>> eshelpers.bulk(client=es,actions=({'_index':'some_new_index1','_type':'some_type','_source':{"args":[20000,"ddfsdssds",454.6666, "ddfd"]}},),stats_only=True)
(1, 0)
>>> 
```

How can I fix it?

**Comment by fxdgear** [comment]
@serg666 

So in your example at the bottom of your issue, this is ok because Elasticsearch will attempt to index the data `"foo"` as a type `text`. Then in the second index request you're sending an integer and Elasticsearch will just do a type conversion for you. 

In the issue you're having what's happening is the first value that gets index is of type `long` and Elasticearch will create the field with the `long` type. Then the when it sees a value of type `text` it can't convert a `somestring` to an interger. 

going from `123` to `"123"` is ok. 
Going from `"foobar"` to `foobar` is not ok. 

So in order to fix what you have to do is create a [mapping](https://www.elastic.co/guide/en/elasticsearch/reference/current/mapping.html) for your index at index creation time or create a [template](https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-templates.html) for which any index created matching the `index_pattern` will use a mapping that you defined in the template. And in your mapping you'll have to define the field type as `text` or `keyword` so that your data can get index appropriately.

**Comment by serg666** [comment]
Thank you!
