### ISSUE TITLE
security variability from python 2.7 to python 3.5?

### ISSUE THREAD

**Issue by regisoc** [elastic/elasticsearch-py#785]
Hello,

I am trying to use elasticsearch with secure connection but I have a nasty `ConnectionError` everytime. What is wierd is that it is only in python3...

The code:

```
$ pip install elasticsearch==5.5.1
$ python2.7
>>> from elasticsearch import Elasticsearch
>>> es = Elasticsearch("https://xxxxxx:9200", use_ssl=True,ca_certs='/my/cert.crt', http_auth=('foo','bar'))
>>> result = es.cluster.health() 
>>> print result 
```

This one works fine! but ....

```
$ python3.5
>>> from elasticsearch import Elasticsearch
>>> es = Elasticsearch("https://xxxxxx:9200", use_ssl=True,ca_certs='/my/cert.crt', http_auth=('foo','bar'))
>>> result = es.cluster.health() 
```

Will print: 

```
GET https://xxxxxx:9200/_cluster/health [status:N/A request:0.022s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/elasticsearch/connection/http_urllib3.py", line 114, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 345, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 844, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 337, in connect
    cert = self.sock.getpeercert()
  File "/usr/lib/python3.5/ssl.py", line 818, in getpeercert
    return self._sslobj.getpeercert(binary_form)
  File "/usr/lib/python3.5/ssl.py", line 595, in getpeercert
    return self._sslobj.peer_certificate(binary_form)
SystemError: <built-in method peer_certificate of _ssl._SSLSocket object at 0x7f3da980c5d0> returned NULL without setting an error

```
... for each node. Did I miss something? Can you reproduce it?

**Comment by fxdgear** [comment]
@regisoc What version of `elasiticsearch-py` are you running in the 3.5 instance?

**Comment by regisoc** [comment]
Hi, same one ! 

```
>>> import elasticsearch
>>> elasticsearch.__version__
(5, 5, 1)
```

**Comment by fxdgear** [comment]
@regisoc I'm sorry I'm struggling to reproduce the error. 

My test env:

1. Created Elasticsearch cluster using Docker. 
2. Created self signed cert using the [`certutil`](https://www.elastic.co/guide/en/elasticsearch/reference/current/certutil.html) tool
3. Created a 2nd container, on the same network as the elastic cluster running python 3.5
4. installed `elasticsearch==5.5.1` via pip
5. ran your same commands:

```
root@e5b9ae13391d:/ca# ipython
Python 3.5.5 (default, May  5 2018, 03:15:21) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.3.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: pwd
Out[1]: '/ca'

In [2]: from elasticsearch import Elasticsearch

In [3]: es = Elasticsearch("https://elasticsearch:9200", use_ssl=True,ca_certs='/ca/ca.crt', http_auth=('elastic',
   ...: 'changeme'))

In [4]: result = es.cluster.health() 

In [5]: result
Out[5]: 
{'active_primary_shards': 30,
 'active_shards': 30,
 'active_shards_percent_as_number': 54.54545454545454,
 'cluster_name': 'docker-cluster',
 'delayed_unassigned_shards': 0,
 'initializing_shards': 0,
 'number_of_data_nodes': 1,
 'number_of_in_flight_fetch': 0,
 'number_of_nodes': 1,
 'number_of_pending_tasks': 0,
 'relocating_shards': 0,
 'status': 'yellow',
 'task_max_waiting_in_queue_millis': 0,
 'timed_out': False,
 'unassigned_shards': 25}
```

My question is now how did you setup your cert? 
Can you try using the latest version of `elasticsearch-py`?

**Comment by sethmlarson** [comment]
Going to close this issue as no additional information was supplied. If you're still experiencing this issue please reopen.
