### ISSUE TITLE
Following redirects does not work in es-py

### ISSUE THREAD

**Issue by jarajapu** [elastic/elasticsearch-py#786]
I tried my best to follow the documentation and code to figure out how to enable redirects for an ES client, but keep getting an HTTP 302 response for my request. Here is my code:

```
headers={'connection': 'keep-alive', 'redirects': True}
es = Elasticsearch([{'host': cluster, 'port': 80}], http_auth=(user, secret), scheme='http', headers=headers)
res = es.exists(index=myIndex, doc_type='test', id='ABCDEF1234')
```

Here is the error message I see:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "~/x-9GQQSZlO/lib/python2.7/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "~/x-9GQQSZlO/lib/python2.7/site-packages/elasticsearch/client/__init__.py", line 357, in exists
    doc_type, id), params=params)
  File "~/x-9GQQSZlO/lib/python2.7/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "~/x-9GQQSZlO/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "~/x-9GQQSZlO/lib/python2.7/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(302, u'')
```

Based on the code in es-py GitHub under connection/http_requests.py, headers set this way below should have worked. I tried these variations below but without success.

```
headers={'connection': 'keep-alive', 'redirects': True}
headers={'connection': 'keep-alive', 'redirects': 'true'}
```

What am I missing ?

**Comment by jarajapu** [comment]
As a side note, using scheme='https' is not helpful either and results in an error message about 'unknown protocol'. 

```
elasticsearch.exceptions.SSLError: ConnectionError([SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590)) caused by: SSLError([SSL: UNKNOWN_PROTOCOL] unknown protocol (_ssl.c:590))
```

**Comment by fxdgear** [comment]
@jarajapu Thanks for the issue. 

Where did you find documentation about that header? 

re using `scheme` I don't think you should really worry about that. Just instantiate the object with a string of  your cluster url. 

```
es = Elasticsearch("https://mycluster.domain.com:9200", http_auth=('username', 'password'))
```

**Comment by fxdgear** [comment]
Also I'm wondering if not using the requests lib would be better for you. Requests adds some complexity to each request to the cluster so in the long run requests becomes slower than using `http_urlib3` module. It's the prefered way of doing things. But requests is provided in situations where people can't use urllib3. And if that's the case it's ok. I just wanted to make sure first.

**Comment by mateusz-blaszkowski** [comment]
Hi. Any update on this issue? It affects me as well. We have a proxy between a client and Elasticsearch - it redirects all the requests (with 308 HTTP code). I can't find any way to allow redirects. 

```
.tox/py27/local/lib/python2.7/site-packages/elasticsearch_dsl/search.py:704: in execute
    **self._params
.tox/py27/local/lib/python2.7/site-packages/elasticsearch/client/utils.py:76: in _wrapped
    return func(*args, params=params, **kwargs)
.tox/py27/local/lib/python2.7/site-packages/elasticsearch/client/__init__.py:660: in search
    doc_type, '_search'), params=params, body=body)
.tox/py27/local/lib/python2.7/site-packages/elasticsearch/transport.py:318: in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
.tox/py27/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py:186: in perform_request
    self._raise_error(response.status, raw_data)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <Urllib3HttpConnection: http://nb.10.91.209.155.xip.io:80>, status_code = 308
raw_data = '<html>
<head><title>308 Permanent Redirect</title></head>
<body bgcolor="white">
<center><h1>308 Permanent Redirect</h1></center>
<hr><center>nginx/1.13.12</center>
</body>
</html>
'

    def _raise_error(self, status_code, raw_data):
        """ Locate appropriate exception and raise it. """
        error_message = raw_data
        additional_info = None
        try:
            if raw_data:
                additional_info = json.loads(raw_data)
                error_message = additional_info.get('error', error_message)
                if isinstance(error_message, dict) and 'type' in error_message:
                    error_message = error_message['type']
        except (ValueError, TypeError) as err:
            logger.warning('Undecodable raw error response from server: %s', err)
    
>       raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
E       TransportError: TransportError(308, u'<html>\r\n<head><title>308 Permanent Redirect</title></head>\r\n<body bgcolor="white">\r\n<center><h1>308 Permanent Redirect</h1></center>\r\n<hr><center>nginx/1.13.12</center>\r\n</body>\r\n<
/html>\r\n')

.tox/py27/local/lib/python2.7/site-packages/elasticsearch/connection/base.py:125: TransportError
```

**Comment by fxdgear** [comment]
Have you tried using the requests backend instead of using the yelling backend?

**Comment by mateusz-blaszkowski** [comment]
That helped, thanks!

**Comment by MarcDAFrame** [comment]
@mateusz-blaszkowski what did you do to use requests?

**Comment by fxdgear** [comment]
@MarcDAFrame It's built into the library already all you have to do is instantiate your connection using the requests transport class.  https://elasticsearch-py.readthedocs.io/en/master/transports.html#transport-classes

**Comment by MarcDAFrame** [comment]
@fxdgear that doesn't seem to work for me. I can access it through a browser / curl just fine.

here is the NGINX that i have a proxy
```
server {
 listen 80;
 server_name es.<MY URL>.ca;
 location / {
  proxy_set_header Host <MY INSTANCE>.us-east-1.aws.found.io:9243;
  proxy_pass https://<MY INSTANCE>.us-east-1.aws.found.io:9243;
 }
}
```
and here is what I am trying to do w/ elasitcsearch python
```
Elasticsearch(["http://es.<MY IP>.ca/"], http_auth=('<MY USER>', '<MY PASSWORD>'), connection_class=RequestsHttpConnection)
```

could you help me figure out what I am doing wrong here?

Cheers,
Marc

**Comment by sethmlarson** [comment]
Closing this issue as "solved" by using the Requests HTTP connection.
