### ISSUE TITLE
Handling TransportError(500, 'refresh_failed_engine_exception', 'Refresh failed')

### ISSUE THREAD

**Issue by duhaime** [elastic/elasticsearch-py#804]
I'm using [image-match](https://github.com/ascribe/image-match), a library that stores hashes of images in ElasticSearch. I'm running an index refresh after every insertion to facilitate immediate queries, and have started to see a refresh error:

`Handling TransportError(500, 'refresh_failed_engine_exception', 'Refresh failed')`

Full stacktrace:

```
Traceback (most recent call last):
  File "/Users/doug/anaconda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "chapters/print-piracy/detect-image-reuse/cluster_groups.py", line 210, in process_image_cluster
    for image_group in get_similar_image_groups(image_cluster):
  File "chapters/print-piracy/detect-image-reuse/cluster_groups.py", line 65, in get_similar_image_groups
    ses.add_image(i, refresh_after=True)
  File "/Users/doug/anaconda/lib/python3.6/site-packages/image_match/signature_database_base.py", line 203, in add_image
    self.insert_single_record(rec, refresh_after=refresh_after)
  File "/Users/doug/anaconda/lib/python3.6/site-packages/image_match/elasticsearch_driver.py", line 88, in insert_single_record
    self.es.index(index=self.index, doc_type=self.doc_type, body=rec, refresh=refresh_after)
  File "/Users/doug/anaconda/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/doug/anaconda/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 319, in index
    _make_path(index, doc_type, id), params=params, body=body)
  File "/Users/doug/anaconda/lib/python3.6/site-packages/elasticsearch/transport.py", line 314, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/Users/doug/anaconda/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 180, in perform_request
    self._raise_error(response.status, raw_data)
  File "/Users/doug/anaconda/lib/python3.6/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.TransportError: TransportError(500, 'refresh_failed_engine_exception', 'Refresh failed')
```

Would it be possible / desirable to add an `ignore` parameter to the `refresh()` method in `elasticsearch.indices` in a way that's similar to the `ignore` parameter users can pass to the `delete()` method in `elasticsearch.indices`? That way users could ignore 500 responses on refresh requests without having to manually try/catch.

**Comment by duhaime** [comment]
Digging a bit further on this it looks like `es.indices.refresh` delegates to `transport.make_request` which accepts a `retry_on_status` argument that should solve this. Thanks very much for the wrapper!
