### ISSUE TITLE
Query for huge result truncates the data

### ISSUE THREAD

**Issue by tivvit** [elastic/elasticsearch-py#805]
```
s = Search(using=self.es, index=index, doc_type=doc_type)
s = s.query(self.queryParser(query))
res = s.execute()
for h in res.hits.hits:
    ...
```

```
JSONDecodeError("Expecting ',' delimiter or '}': line 1 column 524050 (char 524049)",))
```

It works with `curl` doing the same query

```
curl --cacert ca.crt --cert client-dev.crt --key client-dev.key -XGET https://a6es-e25.ng.seznam.cz:9200/email-probe-day-scanner-2018-06-11/_search/ -d '{"query": {"bool": {"must": [{"query_string": {"query": " *"}}]}}, "from": 0, "size": 999}' -H "Content-Type: application/json" | jq ".hits.hits | length"
```

```
999
```

**Comment by Robitx** [comment]
@tivvit full trace might be useful..

```Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/elasticsearch/serializer.py", line 38, in loads
    return json.loads(s)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Unterminated string starting at: line 1 column 507729 (char 507728)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/zaloha/szngit/stuff/getffq", line 348, in <module>
    main(sys.argv[1:])
  File "/zaloha/szngit/stuff/getffq", line 282, in main
    field=str(t), query=query, size=size, asc=ascend)
  File "/zaloha/szngit/stuff/TESDSL.py", line 312, in getTerms
    res = s.execute()
  File "/usr/lib/python3.6/site-packages/elasticsearch_dsl/search.py", line 606, in execute
    **self._params
  File "/usr/lib/python3.6/site-packages/elasticsearch/client/utils.py", line 73, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/usr/lib/python3.6/site-packages/elasticsearch/client/__init__.py", line 623, in search
    doc_type, '_search'), params=params, body=body)
  File "/usr/lib/python3.6/site-packages/elasticsearch/transport.py", line 342, in perform_request
    data = self.deserializer.loads(data, headers.get('content-type'))
  File "/usr/lib/python3.6/site-packages/elasticsearch/serializer.py", line 76, in loads
    return deserializer.loads(s)
  File "/usr/lib/python3.6/site-packages/elasticsearch/serializer.py", line 40, in loads
    raise SerializationError(s, e)
elasticsearch.exceptions.SerializationError: (__HUGE_DATA__, JSONDecodeError('Unterminated string starting at: line 1 column 507729 (char 507728)',))```

**Comment by tivvit** [comment]
@fxdgear do you think that this is a bug or is there another way how to solve it?

**Comment by fxdgear** [comment]
Sorry I was on holiday for the last 2 weeks. I'm back to work today and catching up on emails. I'll address this and all other issues/PR's asap :)

thanks

**Comment by tivvit** [comment]
@fxdgear should I prepare more extensive report or are you able to replicate the problem?

**Comment by fxdgear** [comment]
@tivvit I'm struggling to reproduce. Do you by chance have some sample data. 

My next question would be to replicate your "curl" example but throw it into python's json parser. 

To rule out that the issue is with the json decoder. In the meantime I'll continue to try to create super large data sets. 

Also, your issue says "truncates the data". How do you know the data is getting truncated? Do you have an example of how it's getting truncated?

**Comment by fxdgear** [comment]
@tivvit oh one more thing. Can you try removing the `elasticsearch_dsl` aspect from your example and just use `elasticsearch`. 

I want to verify that this issue belongs here of if it belongs in https://github.com/elastic/elasticsearch-dsl-py/

**Comment by tivvit** [comment]
Hi I am preparing sandbox for simulating this problem.

For now I can confirm that the problem that the problem is in `elasticsearch-py`
More precisely it seems like `urllib3` problem

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 380, in read
    data = self._fp.read()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(524122 bytes read, 420043 more expected)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 149, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.6/site-packages/urllib3/util/retry.py", line 333, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 617, in urlopen
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 467, in from_httplib
    **response_kw)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 159, in __init__
    self._body = self.read(decode_content=decode_content)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 401, in read
    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 320, in _error_catcher
    raise ProtocolError('Connection broken: %r' % e, e)
urllib3.exceptions.ProtocolError: ('Connection broken: IncompleteRead(524122 bytes read, 420043 more expected)', IncompleteRead(524122 bytes read, 420043 more expected))
Connection <Urllib3HttpConnection: https://a6es-e26.ng.seznam.cz:9200> has failed for 1 times in a row, putting on 60 second timeout.
GET https://a6es-e20.ng.seznam.cz:9200/email-probe-day-scanner-2018-06-26/scanner/_search [status:N/A request:0.058s]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 302, in _error_catcher
    yield
  File "/usr/local/lib/python3.6/site-packages/urllib3/response.py", line 380, in read
    data = self._fp.read()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 462, in read
    s = self._safe_read(self.length)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/http/client.py", line 614, in _safe_read
    raise IncompleteRead(b''.join(s), amt)
http.client.IncompleteRead: IncompleteRead(524122 bytes read, 420043 more expected)
```

**Comment by tivvit** [comment]
The test is here https://gist.github.com/tivvit/a08ba7da12ea7236d46ba025361a995b 

So far the problem did not occur, the data is the same only anonymized.
I was able to read 2k documents and the problem occurs with 10 before.

I think the problem will be with SSL.
I will try if the problem is in Ngnix or in the python client and add that to the example.

**Comment by tivvit** [comment]
It seems now that the problem is with the reverse proxy (but it did not show in testing env). It seems that the content length header is set incorrectly. I will inform you about the result (and maybe close)

**Comment by fxdgear** [comment]
@tivvit thanks for your work on this :) 

let me know if theres anything else I can help you with. I'll leave this open till you're 100% certain.
