### ISSUE TITLE
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9e5db5d208>: Failed to establish a new connection: [Errno 113] No route to host

### ISSUE THREAD

**Issue by laurentvv** [elastic/elasticsearch-py#836]
I often have this error, but script works :

GET http://x.x.x.x:9200/_nodes/_all/http [status:N/A request:2.992s]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib64/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f9e5db5d208>: Failed to establish a new connection: [Errno 113] No route to host

**Comment by fxdgear** [comment]
It sounds like there might be some problem in the connection between your python program and your Elasticsearch cluster. 

Unfortunately I can't offer any advice here because there's not enough information. 

How many nodes are in your cluster. Do you have them sitting behind a proxy or not? are you using x-pack or not? are you using a hosted service or hosting it your self. 

There's a lot of factors here going on that can cause HTTP connection errors. 

Any more info would be helpful. 

thanks

**Comment by laurentvv** [comment]
More info :
3 nodes : 3 VM 8cpu 20go config script with these 3 nodes
No proxy
Not xpack
Hosting myself
No problem when i use rest with EL.

Laurent

**Comment by fxdgear** [comment]
@laurentvv thanks for that. This is helpful. 

My next question is you say you have 3 nodes, 3 VM's. Where are those VM's running? Are they all on one computer? On 3 computers? In a data center? On your desk?

**Comment by fxdgear** [comment]
On a related note:

If you use `curl` instead of the python client. Do you experience similar errors?

**Comment by laurentvv** [comment]
Datacenter
No error with curl
These error don't block my script.
I have a result i don't understand why i have these error

**Comment by fxdgear** [comment]
the error you're getting is a result of a network connection or firewall rule or something. 
It is actually not an error related to 
1. Elasticsearch
2. Elasticsearch-py (this library)

This error is coming from urllib3. And the reason you're getting this error is because python can not make a connection to the HTTP host it's trying to connect to. 

If we take out Elasticsearch and Elasticsearch-py. This error happens because a python process using URLlib3 can not connect to a networked host. 

This is why I asked all the questions, because somewhere you have a network configuration that's causing the python process to not be able to connect to a host in your cluster. It could be related to anything from the VM firewall rules, the host firewall rules, the data center firewall rules, routers, etc..

**Comment by Roskgp96** [comment]
@laurentvv  did you solve this issue?

**Comment by laurentvv** [comment]
Yes firewall problem, its ok now. thks

**Comment by johnprakashgithub** [comment]
How did you solve this issue? Is this really a firewall issue. I too face the same issue. Getting success in curl and failed in urllib3 HTTP connection.

**Comment by laurentvv** [comment]
Firewall block because too many connection, change rule of block

**Comment by isharamadhawa** [comment]
Close the connection every time you made a request.

**Comment by manasatmicro** [comment]
How you blocked that can you explain?

**Comment by MLaure19** [comment]
Hello, I am also experimenting the same issue. Would be great to get some help. 
Many thanks
Marie-Laure

**Comment by pointtester** [comment]
Hello, I am also experimenting with the same issue. Would be great to get some help.
Many thanks

**Comment by filiperivelli** [comment]
Same issue here. I'm using Lubuntu 18. How can I change the firewall rules? @laurentvv

**Comment by clarabez** [comment]
This happens when you have parallel competition for the connection. Try to finish opened connections from appium and run it again.

**Comment by ibanua** [comment]
Hi everyone. i am trying to solve the same problem. i closed the firewall but it didnt work..i am using windows

**Comment by Manju-xenon0172** [comment]
"elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x00000188E25C6B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x00000188E25C6B20>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed)"
I'm getting this error. can you resolve this?

**Comment by MiguelQuintero59** [comment]
Hi, currently I am experiencing this problem. I did try to modify the firewall rule block but was not successful. I'm using macOS. Does anyone have an update?

**Comment by ABC00012345** [comment]
same issue ubuntu 22.04. i hope solve it

**Comment by pquentin** [comment]
As a maintainer of urllib3 and elasticsearch-py, there is zero evidence so far that this is a bug in either library. While I understand that this issue likely ranks high in your search engine results, we use GitHub for verified bug reports, feature requests, and pull requests. If you believe you have found an issue, please open a new GitHub issue.

However, if you have a general question, please head to the [forums](https://discuss.elastic.co/tag/language-clients) instead. If you can stop by there, we'd appreciate it. There's an active community that should be able to help get an answer to your question.

As such, to avoid future frustration and to get you better help in the future, I hope you don't mind the lock on this issue.
