### ISSUE TITLE
HTTP DELETE raises "elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Rejecting mapping update to [brwnppr.dev] as the final mapping would have more than 1 type: [x, doc]')"

### ISSUE THREAD

**Issue by bastbnl** [elastic/elasticsearch-py#845]
Hi,
I'm using `elasticsearch==6.3.1` with an elasticsearch cluster running on my poor-mans elasticsearch cluster using version 6.4.0 on each node. I ran into an unexpected exception while testing the removal of a non-existing document. 

The documents are indexed as a rather original `doc` doc_type. I ran something similar to this:
```
es = Elasticsearch(hosts=['censored.brwnppr.com', ], timeout=1.0, sniff_on_start=False,)
es.delete(index='brwnppr.dev', doc_type='x', id='u3111')
```

Running this raises: 
```
DELETE http://<censored>:9200/brwnppr.dev/x/u3111 [status:400 request:0.085s]
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 1070, in delete
    doc_type, id), params=params)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/elasticapm/instrumentation/packages/base.py", line 105, in call_if_sampling
    return wrapped(*args, **kwargs)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/var/www/brownpapersession/dev/env/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'illegal_argument_exception', 'Rejecting mapping update to [brwnppr.dev] as the final mapping would have more than 1 type: [x, doc]')
```

Which is unexpected; I would expect to receive the `NotFoundError`.

**Comment by HonzaKral** [comment]
Unfortunately this is just an exception from elasticsearch, not elasticsearch-py, we just translate whatever is in the response code. You will have to open an issue on the main repo.

Thank you!
