### ISSUE TITLE
bulk() request_timeout higher than 60 is not respected

### ISSUE THREAD

**Issue by melissachang** [elastic/elasticsearch-py#859]
If I [set bulk() request_timeout to 60](https://github.com/DataBiosphere/data-explorer-indexers/blob/master/indexer_util/indexer_util/indexer_util.py#L147), it works -- requests that take longer than 10s are allowed.

But if I change it to 120, requests longer than 60s timeout:
```
indexer_1        | 2018101621:03:08    base.py:83 INFO POST http://elasticsearch:9200/_bulk [status:200 request:15.324s]
indexer_1        | 2018101621:03:37    base.py:83 INFO POST http://elasticsearch:9200/_bulk [status:200 request:28.642s]
indexer_1        | 2018101621:04:05    base.py:83 INFO POST http://elasticsearch:9200/_bulk [status:200 request:27.661s]
indexer_1        | 2018101621:04:31    base.py:83 INFO POST http://elasticsearch:9200/_bulk [status:200 request:26.057s]
indexer_1        | 2018101621:05:31    base.py:97 WARNING POST http://elasticsearch:9200/_bulk [status:N/A request:60.061s]
indexer_1        | Traceback (most recent call last):
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/connection/http_urllib3.py", line 149, in perform_request
indexer_1        |     response = self.pool.urlopen(method, url, body, retries=False, headers=request_headers, **kw)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 639, in urlopen
indexer_1        |     _stacktrace=sys.exc_info()[2])
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/urllib3/util/retry.py", line 333, in increment
indexer_1        |     raise six.reraise(type(error), error, _stacktrace)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 601, in urlopen
indexer_1        |     chunked=chunked)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 389, in _make_request
indexer_1        |     self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/urllib3/connectionpool.py", line 309, in _raise_timeout
indexer_1        |     raise ReadTimeoutError(self, url, "Read timed out. (read timeout=%s)" % timeout_value)
indexer_1        | ReadTimeoutError: HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=60)
indexer_1        | Index name: encode
indexer_1        | Elasticsearch took 0 seconds to come up.
indexer_1        | Traceback (most recent call last):
indexer_1        |   File "indexer.py", line 344, in <module>
indexer_1        |     main()
indexer_1        |   File "indexer.py", line 334, in main
indexer_1        |     sample_id_column, sample_file_columns)
indexer_1        |   File "indexer.py", line 231, in index_table
indexer_1        |     indexer_util.bulk_index_scripts(es, index_name, scripts_by_id)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/indexer_util/indexer_util.py", line 126, in bulk_index_scripts
indexer_1        |     bulk(es, es_actions(scripts_by_id), request_timeout=60)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 257, in bulk
indexer_1        |     for ok, item in streaming_bulk(client, actions, **kwargs):
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 192, in streaming_bulk
indexer_1        |     raise_on_error, **kwargs)
indexer_1        |   File "/usr/local/lib/python2.7/site-packages/elasticsearch/helpers/__init__.py", line 99, in _process_bulk_chunk
indexer_1        |     raise e
indexer_1        | elasticsearch.exceptions.ConnectionTimeout: ConnectionTimeout caused by - ReadTimeoutError(HTTPConnectionPool(host='elasticsearch', port=9200): Read timed out. (read timeout=60))
bigquery_indexer_1 exited with code 1
```
I also tried adding `timeout=120` where I [create Elasticsearch object](https://github.com/DataBiosphere/data-explorer-indexers/blob/master/indexer_util/indexer_util/indexer_util.py#L93); I get the same error.

**Comment by melissachang** [comment]
N/m, turns out I hadn't set bulk() request_timeout after all.
