### ISSUE TITLE
Tests fail on Elasticsearch version 6.4.2

### ISSUE THREAD

**Issue by fxdgear** [elastic/elasticsearch-py#866]
```
11:14:19 ======================================================================
11:14:19 FAIL: test_elasticsearch.test_server.test_common:TestNodesReloadSecureSettings10Basic.test_from_yaml_0 (nodes.reload_secure_settings/10_basic.yml): node_reload_secure_settings test
11:14:19 ----------------------------------------------------------------------
11:14:19 Traceback (most recent call last):
11:14:19   File "/code/elasticsearch-py/test_elasticsearch/test_server/test_common.py", line 266, in m
11:14:19     self.run_code(definition)
11:14:19   File "/code/elasticsearch-py/test_elasticsearch/test_server/test_common.py", line 112, in run_code
11:14:19     getattr(self, 'run_' + action_type)(action)
11:14:19   File "/code/elasticsearch-py/test_elasticsearch/test_server/test_common.py", line 129, in run_do
11:14:19     self.assertTrue(hasattr(api, m))
11:14:19 nose.proxy.AssertionError: False is not true
```

**Comment by fxdgear** [comment]
Closing this. New API endpoint introduced. We've included it now.
