### ISSUE TITLE
blocked by: [FORBIDDEN/12/index read-only / allow  delete (api)

### ISSUE THREAD

**Issue by flipchan** [elastic/elasticsearch-py#874]
Hello im getting a read only error when i try to add data to a elasticsearch index

```
>>> import elasticsearch
>>> es = elasticsearch.Elasticsearch() 
>>> es.index(index='testindex', doc_type='test-type', body=body)                
Traceback (most recent call last):                                           
  File "<stdin>", line 1, in <module>                                        
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/utils.py"
 line 76, in _wrapped                                                        
    return func(*args, params=params, **kwargs)                              
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/client/__init__.py", line 319, in index                                                       
    _make_path(index, doc_type, id), params=params, body=body)               
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/transport.py", l
ne 318, in perform_request                                                   
    status, headers_response, data = connection.perform_request(method, url, 
arams, body, headers=headers, ignore=ignore, timeout=timeout)                
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/http_
rllib3.py", line 186, in perform_request                                     
    self._raise_error(response.status, raw_data)                             
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/connection/base.y", line 125, in _raise_error                                                
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error
message, additional_info)                                                    
elasticsearch.exceptions.AuthorizationException: AuthorizationException(403,'cluster_block_exception', u'blocked by: [FORBIDDEN/12/index read-only / allo
 delete (api)];')                                                            



```

**Comment by deepakmahapatra** [comment]
https://discuss.elastic.co/t/forbidden-12-index-read-only-allow-delete-api/110282/2

this might be an issue with your elastic cluster storage.

**Comment by flipchan** [comment]
thanks
