### ISSUE TITLE
Wheel for 6.3.1 installs elasticsearch5 (next to elasticsearch)

### ISSUE THREAD

**Issue by telendt** [elastic/elasticsearch-py#880]
```
$ virtualenv /tmp/elasticsearch-wheel
$ source /tmp/elasticsearch-wheel/bin/activate
$ pip install 'elasticsearch==6.3.1'
$ python -c 'import elasticsearch; import elasticsearch5'
```

So wheel installs elasticsearch5 on top of (latest) elasticsearch. Not sure if previous wheel packages are also affected.

Installation from tarball is fine on the other hand:

```
$ virtualenv /tmp/elasticsearch-tarball
$ source /tmp/elasticsearch-tarball/bin/activate
$ pip install --no-binary ':all:' 'elasticsearch==6.3.1'
$ python -c 'import elasticsearch; import elasticsearch5'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'elasticsearch5'
```

This difference is visible on PyPi download page - both tarball and wheel distribute sources and (AFAIK) use gzip compression, so they should be similar in size:

<img width="805" alt="pypi-download" src="https://user-images.githubusercontent.com/85191/49795239-ca12e800-fd39-11e8-9cd6-a1f4d319258b.png">

**Comment by zachgoulet** [comment]
I ran into a very similar issue for the only release of `elasticsearch2`. It looks like the wheel is incorrectly including the `elasticsearch` directory at `5.4.0`. When installing `elasticsearch2` from the wheel, I also get `elasticsearch`:

```
$ python -m venv ./venv
$ source venv/bin/activate
$ pip install elasticsearch2
$ python -c 'import elasticsearch2; import elasticsearch; print(elasticsearch.__version__)'
(5, 4, 0)
```

When installing from source, only `elasticsearch2` is installed.

```
$ python -m venv ./venv
$ source venv/bin/activate
$ pip install --no-binary ':all:' elasticsearch2
$ python -c 'import elasticsearch2; import elasticsearch; print(elasticsearch.__version__)'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'elasticsearch'
```

The file sizes on PyPI are similarly suspect:

![image](https://user-images.githubusercontent.com/24616340/58498104-52037780-814b-11e9-8541-d365f2c6407e.png)

**Comment by PhilMarsh** [comment]
Going purely by archive size, it looks like this is a transient issue in packaging that has popped up at least twice.

I downloaded all the wheels for all versions of elasticsearch-py:
```bash
~/es_whl
$ for major in ""{,1,2,5,6};
do
    for url in $(curl -s -XGET "https://pypi.org/simple/elasticsearch${major}/" | grep -P 'http.*\.whl(?=#)' -o); 
    do
        wget "${url}";
    done;
done
```
Then simply list by file timestamp:
```
$ ls -ltrh
total 11M
-rw-r--r-- 1 ajacobs dev  41K Apr 19  2016 elasticsearch-0.4.4-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  57K Apr 19  2016 elasticsearch-1.5.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  50K Apr 20  2016 elasticsearch-1.1.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  57K Apr 21  2016 elasticsearch-1.6.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  56K Apr 21  2016 elasticsearch-1.4.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  58K Apr 21  2016 elasticsearch-1.7.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  59K Apr 22  2016 elasticsearch-2.2.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  59K Apr 23  2016 elasticsearch-1.9.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  51K Apr 23  2016 elasticsearch-2.3.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  55K Apr 23  2016 elasticsearch-1.3.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  42K Apr 23  2016 elasticsearch-0.4.5-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  57K Apr 23  2016 elasticsearch-2.0.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  47K Apr 23  2016 elasticsearch-1.0.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  51K Apr 23  2016 elasticsearch-1.2.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  59K Apr 23  2016 elasticsearch-1.8.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  50K Apr 23  2016 elasticsearch-1.1.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  58K Apr 24  2016 elasticsearch-2.1.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  51K Jul 31  2016 elasticsearch1-1.10.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  53K Aug 17  2016 elasticsearch-2.4.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  56K Oct 19  2016 elasticsearch-5.0.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  56K Nov  2  2016 elasticsearch-5.0.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  54K Jan  3  2017 elasticsearch-2.4.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  57K Jan 11  2017 elasticsearch-5.1.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  57K Feb 12  2017 elasticsearch-5.2.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  65K Mar 31  2017 elasticsearch-5.3.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  58K May 18  2017 elasticsearch-5.4.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 104K May 30  2017 elasticsearch2-2.5.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  59K Nov 10  2017 elasticsearch-5.5.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 110K Nov 10  2017 elasticsearch5-5.5.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 110K Nov 10  2017 elasticsearch-5.5.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 110K Nov 10  2017 elasticsearch5-5.5.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 110K Nov 14  2017 elasticsearch-6.0.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  59K Jan  5  2018 elasticsearch-6.1.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  59K Jan 12  2018 elasticsearch5-5.5.2-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  59K Jan 16  2018 elasticsearch-5.5.2-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  68K Mar 20  2018 elasticsearch-6.2.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 118K Jun 20  2018 elasticsearch-6.3.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 117K Jun 20  2018 elasticsearch5-5.5.3-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 117K Jun 22  2018 elasticsearch-5.5.3-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 118K Aug  9  2018 elasticsearch-6.3.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 117K Aug  9  2018 elasticsearch5-5.5.4-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev 117K Aug 14  2018 elasticsearch5-5.5.5-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  79K Apr 11 15:56 elasticsearch-7.0.0-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  73K May  9 18:34 elasticsearch6-6.4.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  82K May 10 18:52 elasticsearch-7.0.1-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  82K May 28 13:33 elasticsearch-7.0.2-py2.py3-none-any.whl
-rw-r--r-- 1 ajacobs dev  74K May 28 13:54 elasticsearch6-6.4.2-py2.py3-none-any.whl
```
Looks like anything >100K probably has this packaging issue.

The biggest takeaway to me is that the last version of `elasticsearch5` and (as @zachgoulet noted) the only version of `elasticsearch2` both have this problem. Can we get these repackaged?

**Comment by fxdgear** [comment]
new versions of 2 and 5 pushed.

**Comment by PhilMarsh** [comment]
looks good from here. thanks!
