### ISSUE TITLE
elasticsearch.client.Elasticsearch.scroll causes Validation Failed: 1: scrollId is missing

### ISSUE THREAD

**Issue by k3v142** [elastic/elasticsearch-py#890]
When I execute this row:
```python
page = es.scroll(scroll_id = scroll_id, scroll = '1m')
```
I get:
```
Traceback (most recent call last):
  File "es.py", line 19, in <module>
    for hit in response:
  File "/home/osboxes/Desktop/test/lib/python3.5/site-packages/elasticsearch_dsl/search.py", line 726, in scan
    **self._params
  File "/home/osboxes/Desktop/test/lib/python3.5/site-packages/elasticsearch/helpers/__init__.py", line 379, in scan
    **scroll_kwargs)
  File "/home/osboxes/Desktop/test/lib/python3.5/site-packages/elasticsearch/client/utils.py", line 76, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/home/osboxes/Desktop/test/lib/python3.5/site-packages/elasticsearch/client/__init__.py", line 1016, in scroll
    params=params, body=body)
  File "/home/osboxes/Desktop/test/lib/python3.5/site-packages/elasticsearch/transport.py", line 318, in perform_request
    status, headers_response, data = connection.perform_request(method, url, params, body, headers=headers, ignore=ignore, timeout=timeout)
  File "/home/osboxes/Desktop/test/lib/python3.5/site-packages/elasticsearch/connection/http_urllib3.py", line 186, in perform_request
    self._raise_error(response.status, raw_data)
  File "/home/osboxes/Desktop/test/lib/python3.5/site-packages/elasticsearch/connection/base.py", line 125, in _raise_error
    raise HTTP_EXCEPTIONS.get(status_code, TransportError)(status_code, error_message, additional_info)
elasticsearch.exceptions.RequestError: RequestError(400, 'action_request_validation_exception', 'Validation Failed: 1: scrollId is missing;')
```
In this case `elasticsearch-py` puts `scroll_id` to the body ([`elasticsearch-py/elasticsearch/client/__init__.py:998`](https://github.com/elastic/elasticsearch-py/blob/master/elasticsearch/client/__init__.py#L998)), but `scroll_id` in `body` also doesn't pass validation even during manual testing, but if I put it to the GET params it work OK. 
Then it tried to modify `elasticsearch.client.Elasticsearch.scroll` from:
```python
if scroll_id in SKIP_IN_PATH and body in SKIP_IN_PATH:
    raise ValueError("You need to supply scroll_id or body.")
elif scroll_id and not body:
    body = {'scroll_id':scroll_id}
elif scroll_id:
    params['scroll_id'] = scroll_id
```
to
```python
if scroll_id in SKIP_IN_PATH and body in SKIP_IN_PATH:
    raise ValueError("You need to supply scroll_id or body.")
elif scroll_id:
    params['scroll_id'] = scroll_id
```
and it work as expected.

So why is `scroll_id` pushed to `body`?

**Comment by sethmlarson** [comment]
Scroll ID is pushed to body in this scenario because if you have too large a query-string in your URL you can cause issues on certain proxies. By pushing to the HTTP request body you side-step that issue.
