### ISSUE TITLE
elasticsearch.helpers.scan fails without preserve_order=True

### ISSUE THREAD

**Issue by anottrott** [elastic/elasticsearch-py#931]
`res = scan(es, query=query_body, index=index_name, preserve_order=True)`
`results_list = []`
`for item in res: results_list.append(item)`
Correctly returns a list of 16850 documents from the index as expected

However
`res = scan(es, query=query_body, index=index_name, preserve_order=False)`
`results_list = []`
`for item in res: results_list.append(item)`

Returns the following error:
`Traceback (most recent call last):
  File "***", line 50, in <module>
    for item in res:
  File "/home/user_name/anaconda3/envs/py3_env/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 428, in scan
    query = query.copy() if query else {}
AttributeError: 'str' object has no attribute 'copy'`

**Comment by tpmccallum** [comment]
I have this same issue

```
res = elasticsearch.helpers.scan(client=es, index="fairplay", query=json.dumps(dQuery))
```

produces
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.7/site-packages/elasticsearch/helpers/actions.py", line 428, in scan
    query = query.copy() if query else {}
AttributeError: 'str' object has no attribute 'copy'
```

While 
```
res = elasticsearch.helpers.scan(client=es, index="fairplay", query=json.dumps(dQuery), preserve_order=True)

for i, doc in enumerate(res):
    source = doc.get('_source')
    print(source)
```

Returns the data i.e. 

```
{'contractAddress': '0x5Efa94B9183Aa1B4Dd3fb6fC06E792533CeC075b'}
{'contractAddress': '0x8f5fbb1f077344784347Bee6606df8D2dc8D171A'}
{'contractAddress': '0x3EaceE10a61Adda8C08735bD8522E6059AD6383F'}
{'contractAddress': '0x3915A0B21a337a9d038b3c9FA0748fA7Caff9E05'}
{'contractAddress': '0xDfe30eAb47025F488ff20Fc79B5a5BEaE845e8b9'}
{'contractAddress': '0x8467F9fD3cdf267f71A0262599Ad0DAE9ABF855D'}
{'contractAddress': '0xFb49CF44C38D95d3263b6CCFe366d275B80453F2'}
{'contractAddress': '0x320F0Ae79A851874a80D5B8139fa31fCa6eE6514'}
{'contractAddress': '0xC5366ADE0cf3E44a520D2C8d4712abD89cD2387d'}
{'contractAddress': '0x5a4F1383b9892ca0C9A962D9A715f615A7286234'}
{'contractAddress': '0xaFA336a6800af3B570e27194d79DB3a5F55d8e80'}
{'contractAddress': '0xEE4B892d25A53C28866cDe48095aB220F2C33715'}
{'contractAddress': '0xf438C9e2409d2192daA51f6be710321eb298458d'}
{'contractAddress': '0x0Fd37B5367CCD8eAD38bCb470Fea227BafDD312f'}
{'contractAddress': '0x37175C1B038F654ec3691FEa8BC35E4D0CBbA4c7'}
{'contractAddress': '0xD27D7058cd5fBd2De863A3fCBb5Bd28f4C05d3D0'}
{'contractAddress': '0x7e38f41F7562720D1F219D474C78d98152382BFe'}
{'contractAddress': '0xA9FF458442bBaB1E0b29C2AC14e4988f8F764eB3'}
{'contractAddress': '0x38AA9236B84A5019c77fA37B73afF23F2e442817'}
{'contractAddress': '0xE74D31bC4F7ac38629B4ff6fF3F8C7E4EbcC49A9'}
{'contractAddress': '0x9FDB79aA29aa6f0D541aFC7164d0B03a46536BE1'}
{'contractAddress': '0xe59598872B6dB7c687cFD81C53A6B867f77225c7'}
{'contractAddress': '0xb3d56fE1bd23d4b06536DE40394e6c2584412f11'}
{'contractAddress': '0x8f982C59312E87e7A0Ad15a6d14D35e4E8780cbb'}
{'contractAddress': '0x0fEB15a0F7029b0F4aF355aa2Fc3CFa6Df7C8483'}
```

**Comment by vtslab** [comment]
elasticsearch.helpers.scan expects the query parameter to be a dictionary (so do not do a json.dumps() call on the search nody), but, confusingly, the method still works with a string body, provided that preserve_order=True. I suggest the maintainers add an assert on the type(query) and add a more helpful error message (even if the AttributeError leaves little to the imagination).

**Comment by HonzaKral** [comment]
Thank you, @vtslab, that is indeed the correct answer. There should never be a need to serialize bodies into json as that is what the library does for you...
