### ISSUE TITLE
JSONDecodeError('Extra data: line 1 column ...

### ISSUE THREAD

**Issue by xsolo** [elastic/elasticsearch-py#967]
Elastic search python client is version 6.3.1
I have a gunicorne flask app with 4 workers. I use gevents to search multiple indices in 'parallel'. From time to time, I get the JSONDecodeError('Extra data: line 1 column 98726 (char 98725)',)) error while pulling data from Elasticsearch. 

The result set is large (about 3MB)

The elastic search is 6.4.2

**Comment by Winterflower** [comment]
Hi @xsolo - can you post a stacktrace to see which part of the codebase this error is coming from? It's hard to say without more information, but it looks like you might be returning multiple documents and trying to decode them at once, which is resulting in this error.

**Comment by xsolo** [comment]
Hello Winterflowr, here are more details.
We have 28 indices that we query individually using the elasticsearch-dsl==6.4.0
The search happens using the gevents. Here is the code
`        try:
            futures = []
            for index in self.index_aliases:
                s = search.using(get_elasticsearch_client()).index(index)
                futures.append(gevent.spawn(s.execute))

            gevent.joinall(futures)

            result = functools.reduce(operator.add, [self._transform_result(f.get()) for f in futures])`
The result set that each index returns is about 500 records. Here is the stack trace.

`JSONDecodeError('Expecting property name enclosed in double quotes: line 1 column 8436 (char 8435)',))
Traceback (most recent call last):
  File "/wayfair/data/recsvc/d96c2f4e1fc1bd8fff83697d2ac41a7ccb2d41cb/virtenv/lib/python3.6/site-packages/elasticsearch/serializer.py", line 40, in loads
    return json.loads(s)
  File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib64/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 8436 (char 8435)`

**Comment by xsolo** [comment]
More info, here is the additional stack traces
```python

Traceback (most recent call last):

  File "/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)

  File "/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)

  File "<string>", line 2, in raise_from

  File "/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()

  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()

  File "/usr/lib64/python3.6/http/client.py", line 260, in _read_status
    raise LineTooLong("status line")

http.client.LineTooLong: got more than 65536 bytes when reading status line


During handling of the above exception, another exception occurred:


Traceback (most recent call last):

  File "/venv/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 217, in perform_request
    method, url, body, retries=Retry(False), headers=request_headers, **kw

  File "/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])

  File "/venv/lib/python3.6/site-packages/urllib3/util/retry.py", line 343, in increment
    raise six.reraise(type(error), error, _stacktrace)

  File "/venv/lib/python3.6/site-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)

  File "/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)

  File "/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)

  File "<string>", line 2, in raise_from

  File "/venv/lib/python3.6/site-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()

  File "/usr/lib64/python3.6/http/client.py", line 1331, in getresponse
    response.begin()

  File "/usr/lib64/python3.6/http/client.py", line 297, in begin
    version, status, reason = self._read_status()

  File "/usr/lib64/python3.6/http/client.py", line 260, in _read_status
    raise LineTooLong("status line")

urllib3.exceptions.ProtocolError: ('Connection aborted.', LineTooLong('got more than 65536 bytes when reading status line',))

```

**Comment by sethmlarson** [comment]
It sounds like there's something funky happening on the socket / HTTP level with gevent with that `ProtocolError`. I don't know how nicely urllib3 pool management works with gevent as I've never done anything with it.

**Comment by sethmlarson** [comment]
Closing this without additional information.
