### ISSUE TITLE
Catch Exceptions without Traceback

### ISSUE THREAD

**Issue by ry1015** [elastic/elasticsearch-py#972]
Hi,
I'm using elasticsearch v7. And I'm using put_user() to create a user using the following code:
from elasticsearch.client.xpack.security import SecurityClient.put_user()

If the elasticsearch server isn't running, I get an error `ConnectionRefusedError: [Errno 111] Connection refused`. Is there a possibility of eliminating the traceback when I catch the error?

Below is my traceback.
```
Traceback (most recent call last):
  File "/home/.local/lib/python3.6/site-packages/elasticsearch/connection/http_urllib3.py", line 115, in perform_request
    response = self.pool.urlopen(method, url, body, retries=False, headers=self.headers, **kw)
  File "/home/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 641, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/.local/lib/python3.6/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 603, in urlopen
    chunked=chunked)
  File "/home/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 355, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.6/http/client.py", line 1239, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1285, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1234, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 964, in send
    self.connect()
  File "/home/.local/lib/python3.6/site-packages/urllib3/connection.py", line 183, in connect
    conn = self._new_conn()
  File "/home/.local/lib/python3.6/site-packages/urllib3/connection.py", line 169, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f5d32d11ac8>: Failed to establish a new connection: [Errno 111] Connection refused
CAUGHT ROLE CONNECTION ERROR!!!
```

Thanks in advance,
Ry

**Comment by 0xdade** [comment]
Posting my desire for this as well. If I'm catching the exception, I really don't want my lower level libraries spewing tracebacks all over the place. If I catch the exception and choose to print it, then I should get the traceback. But if I catch the exception and don't want to print it, the elasticsearch library shouldn't be spewing all over my terminal or logs. This is abnormal behavior -- most libraries that expose exceptions do not proceed to print the exception traceback regardless of what the application wants to do with it. I mean, look at how excessive this is...

```
>>> try:
...     es.es.cluster.health(wait_for_status='yellow', request_timeout=1)
... except elasticsearch.ElasticsearchException as e:
...     print("Caught the ElasticsearchException")
... 
GET http://localhost:9200/_cluster/health?wait_for_status=yellow [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f502f716eb8>: Failed to establish a new connection: [Errno 111] Connection refused
GET http://localhost:9200/_cluster/health?wait_for_status=yellow [status:N/A request:0.000s]
Traceback (most recent call last):
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/elasticsearch/connection/http_urllib3.py", line 172, in perform_request
    response = self.pool.urlopen(method, url, body, retries=Retry(False), headers=request_headers, **kw)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/util/retry.py", line 344, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/packages/six.py", line 686, in reraise
    raise value
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.7/http/client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.7/http/client.py", line 1026, in _send_output
    self.send(msg)
  File "/usr/lib/python3.7/http/client.py", line 966, in send
    self.connect()
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connection.py", line 181, in connect
    conn = self._new_conn()
  File "/home/dade/natlas/natlas-server/venv/lib/python3.7/site-packages/urllib3/connection.py", line 168, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f502f716f60>: Failed to establish a new connection: [Errno 111] Connection refused
Caught the ElasticsearchException
```

@HonzaKral Can you please look into this? I've complained about it on twitter before but I'd really like to see motion on the issue.

**Comment by HonzaKral** [comment]
`elasticsearch-py` uses standard logging library (0) so you can just configure the `elasticsearch` logger to be silent and not log the tracebacks. 

Hope this helps!

0 - https://docs.python.org/3/library/logging.html
